### ISSUE TITLE
Playthrough section sometimes have GS Tokens even if logic_skulltulas = 0

### ISSUE THREAD

**Issue by lambdan** [TestRunnerSRL/OoT-Randomizer#10]
[OoT_ZD8XDAASASJA_3ETEJN3TFB_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2242932/OoT_ZD8XDAASASJA_3ETEJN3TFB_Spoiler.txt)

Note `logic_skulltulas: 0` among the settings at the top, and then scroll down to the Playthrough section and see all the Gold Skulltula Tokens. 
There are no required for completion Gold Skulltula Rewards though so it shouldn't be a problem when actually playing, it's just in the Playthrough section of the Spoiler log.

Doesn't always happen. Out of 14 seeds I generated only 1 got it (1/14).

**Comment by TestRunnerSRL** [comment]
The playthrough is currently shows items that you don't need sometimes. A fix is in the works that should resolve this

**Comment by TestRunnerSRL** [comment]
The new spoiler log has been pushed now
