### ISSUE TITLE
Logic bug ?

### ISSUE THREAD

**Issue by Tantalus-X** [TestRunnerSRL/OoT-Randomizer#1005]
I stuck in Goronia City can not stop the litte roling Goronen hav not bombs/Bombchus and Strength Upgrade is a bug or did I miss something ?

[Savegame and Spoiler .zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4273347/Savegame.and.Spoiler.zip)

**Comment by Zannick** [comment]
The rolling Goron can be stopped by shooting the bomb flowers.

Next time please ask instead in the #gameplay-support channel in [our Discord](discord.gg/ootrandomizer).

**Comment by Tantalus-X** [comment]
> 
> 
> The rolling Goron in adult Goron City can be stopped by shooting the bomb flowers.
> 
> Next time please ask instead in the #gameplay-support channel in [our Discord](discord.gg/ootrandomizer).

hmm ok i have test shoot of the bomb flowers make is didn't explode ater messge from you again now  explode Oo
