### ISSUE TITLE
"Open Forest" tooltip is written from an undisclosed perspective

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#101]
The tooltip is written from the perspective of a closed forest but this isn't clarified in the tooltip making it ambiguous which state the tooltip is regarding (closed/open).

**Comment by TestRunnerSRL** [comment]
Hopefully made it it more clear in 3a410408dee3d0a44427c2c9131704438f0e88d4
