### ISSUE TITLE
Ganondorf can hint unreachable Light Arrows

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1015]
On plentiful with all locations reachable off.

I'm also not convinced that which lights is chosen for the hint is chosen fairly.

**Comment by Zannick** [comment]
The fix for hinting unreachable arrows would be to check reachability of the location, or use the playthrough arrows. The fix for choosing fairly would be to randomly pick. So either:

* shuffle the light arrows locations, then pick the first that's reachable
* run a Search, filter to reachable light arrows locations, and pick one randomly

If none are reachable, we fall back to the same thing we do when light arrows don't exist

**Comment by Zannick** [comment]
I guess technically picking a "reachable" light arrows location could still hint a location locked behind the other light arrows.

**Comment by r0bd0g** [comment]
I don't think that hurts anything b/c you have to pass by all the light arrows requirements to get there anyway, so either you have light arrows or don't care about the logical ones. Regardless it's probably best if it hints one that could be first logical.

**Comment by r0bd0g** [comment]
I was thinking about this some more and it's actually kind of complicated? Imagine a scenario where it's like, multiple light arrows, and player 1 has a light arrows locked by player 2's light arrows, while player 2 has a light arrows locked by player 1's light arrows. What if Ganondorf were to hint both of those locked lights? You'd be forced to find at least one light arrows that he hasn't hinted.

(But does this even matter? The only thing lights can lock is Ganon's castle or Ganon's tower, and you must be able to access both of those areas already anyway to be able to get the hint. But if you're doing glitches it actually could matter. Both players hover over to Ganon's and get the hint, then they both run out of chus with no more explosives available without finding lights. Now we're in a situation where one of the players will be required to find a light arrows other than the one Ganondorf has hinted. I had to reach a bit to think of this situation, but the point is that it probably is something we should try to get right.)

So I think what you'd have to do is something like... Start by shuffling the order that you will go through each of the worlds to hopefully not introduce any bias for one world over the other. Then, for each world, if you start with light arrows, hint that. Otherwise, get a shuffled list of all lights arrow locations for this world. Remove all light arrows from those locations. Test each location for reachability and hint the first one that's found. Replace only this light arrows back into the world (other worlds will only be able to have their lights locked by this one copy of this world's lights). If no lights are reachable, use the validation chest text instead.

**Comment by Zannick** [comment]
So, the playthrough spheres pre-culling are probably the right way overall, and would have less impact than running whole searches. This way, it's just the first time we pick up light arrows for a world, or a random one from the first sphere with any light arrows. This means we're always hinting one of the earliest possible light arrows, so it's not possible for Ganondorf to hint mutually locked lights--he has to hint one of the lights that starts the chain.

**Comment by r0bd0g** [comment]
I think I'd prefer it to be more random than just picking the first one the playthrough can find. But it definite seems like it'd be a lot of effort for very little.

**Comment by Zannick** [comment]
Fixed this in 5.2.100.
