### ISSUE TITLE
@

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1016]
flag(pleasereadtheguide)ramaToday at 5:07 PM
from @Komus 
When the Triforce Pieces Acquired count reaches 100 in a seed with more than 100 pieces in it, on the pause screen (and just the pause screen) an '@' symbol is displayed several spaces to the right of the triforce sprite.
Currently only confirmed to happen on Bizhawk due to multiworld being the only normal method for people to run into situations where they have more than 100 required pieces
https://puu.sh/Fu1Oc/e1def23a57.png
this behaviour can also be witnessed using the VODs from the recent CoS multiworld streams
(just don't be dumb like me and watch the dotzo video, dude is too efficient with his pauses :P)

Cubsrule21Today at 5:21 PM
I have seen this myself as well
figured there was a purpose to it, so ignored it, tbh

**Comment by flagrama** [comment]
Can confirm the same behaviour exists on actual N64 hardware
![image](https://user-images.githubusercontent.com/634079/78605220-23edca00-7829-11ea-95a8-15fda95c02f1.png)
