### ISSUE TITLE
[Suggestion] Sword Progression

### ISSUE THREAD

**Issue by friedpen** [TestRunnerSRL/OoT-Randomizer#103]
Would it be possible to have an option for Kokiri Sword > Master Sword > Biggoron Sword progression with Hammer or Giant's Knife, Wallet 1 + Explosives/Strength 1, as logic for Adult combat? Or is there too many issues with Blank B as Adult or forced Master Sword on turning Adult?

**Comment by TestRunnerSRL** [comment]
There is no real plan to have the Master Sword not at pedestal. I'm not sure what would be involved to make it possible, and it's probably not easy. It also doesn't really make complete sense for the swords to be progressive, seeing as kokiri is child only, and biggoron isn't strictly better than mastersword
