### ISSUE TITLE
Stone of Agony Indicator is behind the small key count

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1032]
It doesn't only react to hidden grottos, but also to chests that haven't been spawned. So in dungeons it can go behind the small key count.

**Comment by Hamsda** [comment]
> but also to chests that haven't been spawned

TIL oO

**Comment by flagrama** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stone of Agony Indicator Appears Behind Small Key Count](https://trello.com/c/g5kC5L58/15-stone-of-agony-indicator-appears-behind-small-key-count)

**Comment by rlbond86** [comment]
I could easily fix this if someone can give an easy way to reproduce.

**Comment by r0bd0g** [comment]
It was discovered using the chest in the silver block hallway in MQ Spirit.

**Comment by rlbond86** [comment]
Sorry, which room is that exactly?

**Comment by r0bd0g** [comment]
The hallway with the silver block. There's only one silver block in mq spirit.
