### ISSUE TITLE
Using ocarina on d-pad while hookshotting to something cancels the hookshot mid-flight

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1034]
You can also change your boot equips during hookshotting, while normally you would not be able to pause to change equips.

This bug has been around for a while but I can't remember if I submitted an issue for it or not.

**Comment by flagrama** [comment]
#546?

**Comment by r0bd0g** [comment]
Maybe that is what happened there? I had something weird once where I clipped oob hookshotting some vines out of water and trying to change boots. Regardless it all seems to stem from the use of the d-pad while hookshotting.
