### ISSUE TITLE
Bug: shop items set via plandomizer get duped in seed generation

### ISSUE THREAD

**Issue by vmrosetta** [TestRunnerSRL/OoT-Randomizer#1035]
Commit I'm using: https://github.com/TestRunnerSRL/OoT-Randomizer/commit/c9df46ecf0be8b9695878418393344bf4d02daab

Sample plandomizer: https://cdn.discordapp.com/attachments/274186223147417600/708586135005298688/pyfgcrlaoeuidhtnsqjkxbmwvz.json
Spoiler generated from above file: https://cdn.discordapp.com/attachments/274186223147417600/708587981820264468/OoT_F3623_300JLMLDO5_Spoiler.json

In this example, Nocturne of Shadow is set to Zora Shop Item 8 and there is one NoS specified in the item pool, but in the spoiler there are 2.

This issue is not present in the stable release.

**Comment by Zannick** [comment]
I wonder if this is a weird conflict between having an item set in `locations` and specified in `item_pool` being interpreted differently, as in: the Nocturne in the item pool is interpreted as an *additional* Nocturne to place beyond the one set in the location. Or if we're just mishandling the locations placement somewhere. @flagrama
