### ISSUE TITLE
Crash during credits on PJ64 2.3

### ISSUE THREAD

**Issue by GrahamBenHarper** [TestRunnerSRL/OoT-Randomizer#1037]
I haven't had this issue before, but I'm using the dev build for PJ64 2.3 and the randomizer crashes when the credits start. It seems like a textbox starts to load. It also happened for my mod when he was running a dev build randomizer.

Here's a link to a VOD where it happens. See the 6h50m mark:
https://www.twitch.tv/videos/622210033

**Comment by Cuphat** [comment]
Please go to #setup-support first. This is a known issue with Shopsanity 4.

**Comment by GrahamBenHarper** [comment]
Ah okay. As long as it's a documented issue then I'm happy. I didn't see it when I skimmed the open issues here, which is why I decided to submit a new issue.

**Comment by flagrama** [comment]
PJ64 2.3.2 is also ancient and we don't support it. We only started supporting PJ64 as of one of the 2.4 dev builds. It's clearly stated that PJ64 is heavily discouraged in the README still even.

**Comment by Zannick** [comment]
Credits crash is a known issue #745. I don't think it's worth keeping a separate PJ64 issue open.
