### ISSUE TITLE
Golden Scale logic error

### ISSUE THREAD

**Issue by GhostlyDark** [TestRunnerSRL/OoT-Randomizer#1038]
I think this seed is unbeatable.

The issue here is that there are two unreachable Golden Skulltula Tokens in the Fire Temple. The Fire Temple has to be entered by entering the Water Temple (entrance randomizer). The Water Temple cannot be entered, as the Iron Boots are part of Ganon's Castle (100 Token requirement for rainbow bridge). The trick to enter the Water Temple with the Golden Scale + Hookshot is enabled. However, the Golden Scale can only be found after defeating Morpha. This means that the trick to enter the Water Temple with the Golden Scale is rendered useless, as the water level is back up again and the Fire Temple is unreachable. Thus, there can only be collected 98 tokens and Ganon's Castle cannot be entered without performing a bombchu hover.

[OoT_EFE0A_17CM62PKMP_Spoiler.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4662942/OoT_EFE0A_17CM62PKMP_Spoiler.zip)

**Comment by flagrama** [comment]
Please go to the Discord to ask about logic issues.

**Comment by flagrama** [comment]
You can use scarecrow's song + longshot to get the hylia sun item.

**Comment by BeeLuigi** [comment]
Rando adds a gossip stone to lake hylia (close to the serenade warp point) that allows you to lower/raise the water level after you've defeated Morpha. That way you can still enter the Water Temple entrance with Gold Scale.

**Comment by GhostlyDark** [comment]
I don't think Scarecrow + Longshot works as long as Morpha isn't killed. How do I shoot the sun if the skybox is hiding the sun?

I didn't know about the gossip stone function. Sorry for the inconvenience. I guess that's why such questions should be asked on Discord instead.

**Comment by aofengen** [comment]
@GhostlyDark it does work - you shoot the sun as it rises over the horizon, once the chicken crows.
