### ISSUE TITLE
Shop Softlocks

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#104]
https://cdn.discordapp.com/attachments/438698093354156032/488477861351522315/snap0001.jpg

https://cdn.discordapp.com/attachments/438698093354156032/488478782790041630/Screen_Shot_09-09-18_at_04.40_PM.PNG

Seed: J4HD2QCA3V

"So, if I hover to that empty spot there, the game won't let me advance the shown text box. I try pressing everything, but nothing."

**Comment by r0bd0g** [comment]
Somebody else reported a similar-looking issue.

https://cdn.discordapp.com/attachments/438698093354156032/488502401545011215/OoT_DJGMYRAXSA4DA5B_Redria_W2P1-comp.2018-09-08_01.54.55.png

(text not randomized)

**Comment by r0bd0g** [comment]
Somebody else reported the same issue, shopsanity not on.

**Comment by r0bd0g** [comment]
Another.
Settings: RJQDSDAXSCN6TCB
Seed: FS1WQ5Q5RO
Occurred in one of the Market Shops and the Kokiri Shop.

**Comment by r0bd0g** [comment]
I think a big culprit (perhaps not the only culprit, I think there was at least one person said one of the softlocks was actually supposed to be weird egg) is bought bombchus with bombchus in logic on.

**Comment by TestRunnerSRL** [comment]
Should be fixed now. It was an issue with adding bombchus to shop but not updating the model in the shop
