### ISSUE TITLE
Spoiler Playthrough Doesn't Get First Available Progressive Item

### ISSUE THREAD

**Issue by Kirkq** [TestRunnerSRL/OoT-Randomizer#1042]
The following seed from 5.2 Release has what I perceive to be an incorrect playthrough, though interpretations may vary.  https://ootrandomizer.com/seed/get?id=463833

[Spoiler_463833.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/4713945/Spoiler_463833.txt)

A bow is available in "Goron City Left Maze Chest" in the second sphere, right next to the Magic Meter acquired in the second sphere at "Goron City Right Maze Chest".  The first available Bow is skipped, which seems like a bug.  The third sphere gets the bow at "Zora River Lower Freestanding PoH"

I perceive this as incorrect or unexpected due to the following comment in Main.py:
    # Reduce each sphere in reverse order, by checking if the game is beatable
    # when we remove the item. We do this to make sure that progressive items
    # like bow and slingshot appear as early as possible rather than as late as possible.

I saw Zannick making changes to this code on the dev branch here, though I did not see explicit mention of fixing playthrough logic: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/992

I saw Testrunner was looking at playthrough changes here: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/896

I'm not clear to what extent Testrunner's proposed playthrough changes would affect the generated playthrough routes.  I find it very interesting and nuanced that "Way of the Hero" is intertwined with "earliest available shell logic", as it allows you to solve for small improvements on information if you can count shells.  "Is this bow the thing Way of the Hero was talking about? - No, I got one one shell earlier, there must be something else here"  If the logic were to be changed such that it did not prioritize minimum spheres followed by earliest item, some of the nuance may be lost.  I'm not clear if changing that logic is part of the future plan or not.

**Comment by flagrama** [comment]
Playthrough is not intended to be an efficient path. It is *only* to prove to the generator that the seed is beatable. It can still be helpful if you get completely stuck too.

**Comment by aofengen** [comment]
The playthrough does not care which progressive item is available first, only that more than one are available. The order the playthrough is generated is not the fastest or most optimized-  rather just one possible way through the seed

**Comment by Kirkq** [comment]
Shouldn't it be the case that a piece of code working from end to beginning removing unnecessary items should pick up the earliest progressive item?  Is the code comment inaccurate or am I misinterpreting the code?  

Why does the playthrough trimming generate this result even though the code appears to be written and commented as though it should not generate this result.

**Comment by flagrama** [comment]
No, it should only do that if it is the only option and the other options are locked behind it. It just pulls a random one of an item for the playthrough. This is *strictly* for proving the seed is beatable. In this case it's seeing the bow from Child Link's perspective, so it needs the bomb bag first.

**Comment by flagrama** [comment]
I'm pretty sure it goes in order of the LocationList for this, which is why this would be found before the other one.

**Comment by flagrama** [comment]
Ideally a different implementation for Playthrough will be created, and some attempts towards it have already started, but it is by no means high priority.

**Comment by r0bd0g** [comment]
Zora river Lower pieces of heart is obtainable in sphere 2 also, using the sphere 1 scale from Man on Roof. This bow was selected as the bow that the playthrough would collect. Then the scale was deleted from the playthrough as an unnecessary item. Finally, the playthrough items were reordered to reflect that the river bow could not be obtained so early without a scale.

**Comment by Kirkq** [comment]
Thanks, that makes a lot of sense.

So then, would it be true that a playthrough does collect the actual earliest shell items, but it may not always collect it in the earliest shell in the playthrough due to removing prerequisites that sped it up but weren't actually required items.  Way of the Hero effectively points at earliest shell progressive items, but the playthrough may not represent that.  In this sense Way of the Hero wouldn't actually select "random" Bows.

**Comment by Zannick** [comment]
r0bd0g has it right here, but the basic gist is this:

The playthrough first selects the "earliest possible" required items at specific locations, then recalculates the order in which to collect those specific items **only**. So the Bow it does collect here is the earliest, under the original assumption of collecting everything available. But when we remove that assumption, it ends up not being the earliest available.

I agree that it looks a little silly. One potential option is to choose required items but not their locations (so all Bows are available), and then trim excess later, although this would cost some performance.

**Comment by Zannick** [comment]
Way of the Hero is a special case, actually, because it only selects individual locations that **alone** are required to win.

**Comment by Zannick** [comment]
The Area Sphere algorithms do intend to improve this, but at the moment it's not really a bug, so I'm closing. If you have ideas for improvements, let's discuss them in the dev channels and we can put an item on the trello.
