### ISSUE TITLE
Error Help on install

### ISSUE THREAD

**Issue by ThomasCapella** [TestRunnerSRL/OoT-Randomizer#1066]
Every time I try to run the program I get this
I dont know what to do
(It says Nick by the way because its not my hard drive)

Building: C:\Program Files (x86)\nodejs\node.exe E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'E:\\Nick\\Games\\Emulator Stuff\\New folder\\oot\\GUI\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.7.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files (x86)\Python38-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "E:\\Nick\\Games\\Emulator Stuff\\New folder\\oot\\GUI\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\node-sass
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm verb lifecycle node-sass@4.12.0~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle node-sass@4.12.0~postinstall: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\node-sass\node_modules\.bin;E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\.bin;C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Python38\Scripts\;C:\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\nodejs\;C:\Users\thoma.DESKTOP-VAGC4TB\AppData\Local\Microsoft\WindowsApps;C:\Users\thoma.DESKTOP-VAGC4TB\AppData\Roaming\npm
npm verb lifecycle node-sass@4.12.0~postinstall: CWD: E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\node-sass
npm info lifecycle node-sass@4.12.0~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 2103ms
npm verb unlock done using C:\Users\thoma.DESKTOP-VAGC4TB\AppData\Roaming\npm-cache\_locks\staging-c369b557d8ece8c9.lock for E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 247ms
npm timing stage:runTopLevelLifecycles Completed in 118385ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.7.0","npm":"6.14.7"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm verb notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm verb notsup Required: {"node":"<8.10.0"}
npm verb notsup Actual:   {"npm":"6.14.7","node":"14.7.0"}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: ia32
npm WARN ootr-electron-gui@5.2.0 No repository field.
npm WARN ootr-electron-gui@5.2.0 No license field.

npm verb stack Error: node-sass@4.12.0 postinstall: `node scripts/build.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:314:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1051:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid node-sass@4.12.0
npm verb cwd E:\Nick\Games\Emulator Stuff\New folder\oot\GUI
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
npm verb node v14.7.0
npm verb npm  v6.14.7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 119417ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thoma.DESKTOP-VAGC4TB\AppData\Roaming\npm-cache\_logs\2020-08-01T01_06_00_679Z-debug.log
Child Process failed with exit code: 1
Last message: Building: C:\Program Files (x86)\nodejs\node.exe E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

Error: Environment setup failed
    at E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\run.js:246:107
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async setupNodeEnvironment (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\run.js:246:5)
    at async main (E:\Nick\Games\Emulator Stuff\New folder\oot\GUI\run.js:346:9)

**Comment by aofengen** [comment]
@ThomasCapella We do not yet support node 14. Use the latest version of Node 12 (12.X.X), and that should fix your issue

**Comment by ThomasCapella** [comment]
Thank you
