### ISSUE TITLE
False hint from dev build 5.2.38

### ISSUE THREAD

**Issue by xlogisticsx** [TestRunnerSRL/OoT-Randomizer#1067]
I got a false hint in the seed https://ootrandomizer.com/seed/get?id=518291 "They say that a single scrub in the crater sells a Strength Upgrade." However, the strength upgrades were: kak redead grotto, Fire Temple Big Lava Room Lower Open Door Chest, and Colossus Deku Scrub Grotto Front. The DMC scrub sold Requiem of Spirit.

**Comment by Cuphat** [comment]
Yeah, the hint currently points to Colossus Deku Scrub Grotto Front. Not sure how that happened, probably just never got caught in the mass renaming of locations and hint work.

**Comment by LostThePirate** [comment]
We've got another one, this time on 5.2.47.

P6 Hint: " "ToT (Right-Center)":              {"text": "They say that a spider under a #crate in the crater# holds #the Weird Egg#.", "colors": ["Green", "Red"]} "

    "World 6": {
      "DMC GS Crate":                                          {"item": "Deku Nuts (10)", "player": 6},

      "Kak Man on Roof":                                       {"item": "Weird Egg", "player": 1},
      "GC GS Boulder Maze":                                    {"item": "Weird Egg", "player": 2},

[OoT_6CBFF_SVUBGAG95M_W6_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/5160079/OoT_6CBFF_SVUBGAG95M_W6_Spoiler.txt)
