### ISSUE TITLE
Deku Scrub Salesman Miscount?

### ISSUE THREAD

**Issue by OlafurKrH** [TestRunnerSRL/OoT-Randomizer#107]
So it said that it adds 31 new item locations, but after looking at a list of them, I counted 33, not including the one that is supposed to sell a Heart Piece or the two capacity upgrade ones. Are there any I'm missing here?

**Comment by r0bd0g** [comment]
I also count 33.

**Comment by TestRunnerSRL** [comment]
Dodongo: 4
Jabu: 1
Ganon: 4
Hyrule Field Grotto: 1
Zora River Grotto: 2
Sacred Forest Meadow Grotto: 2
Lake Hylia Grotto: 3
Gerudo Valley Grotto: 2
Lost Woods: 3
Lost Woods Grotto: 2
Desert Colossus Grotto: 2
Death Mountain Crater Grotto: 3
Death Mountain Crater: 1
Goron City Grotto: 3
Lon Lon Ranch Grotto: 3
-------
Total = 36

Something I should note that 3 of there were previously shuffled (HP, and ammo upgrades), so it's 33 additional locations.

**Comment by OlafurKrH** [comment]
yeah i thought so. it's just weird that this is what it says when you hover over it. 
![image](https://user-images.githubusercontent.com/33912658/45426670-67ec0d80-b68c-11e8-9815-422399843791.png)

**Comment by TestRunnerSRL** [comment]
This is likely a because I originally had not known about the gerudo valley grotto, which has 2.

**Comment by OlafurKrH** [comment]
alright, to be fair, until this latest run I did I did not know about it either.  Nor the ones in SFM, Lon Lon or Child Death Mountain

**Comment by TestRunnerSRL** [comment]
Fixed the tooltip
