### ISSUE TITLE
Shuffled text makes Cow in House impossible

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1070]
andypanther Today at 3:47 PM
Am I doing something wrong or can the fence hopping minigame with epona become impossible if you have random text and the text for starting lap 2 is too long?
I got Ruto's text for meeting her in the water temple, that means 13 A presses and I just can't get through it fast enough before I get stuck on the second fence.

--

I recommend excepting this text from shuffle in all cases.

**Comment by matthewkirby** [comment]
My question is what makes it impossible, I assume just length? If so, are there any other offending text boxes?

**Comment by r0bd0g** [comment]
If it has too many boxes, apparently you can't get control of your carrots back in time to jump a fence.

**Comment by matthewkirby** [comment]
Would it be better to exclude the long messages or just not have the those two text boxes shuffled at all? I can look at fixing this if there is a consensus
