### ISSUE TITLE
Progress Bar uses generation count when generating from file

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1074]
This despite the fact that that option is greyed out when generate from file is selected.

**Comment by ETR-BTF** [comment]
![gencount](https://user-images.githubusercontent.com/63906538/89883891-137ba080-dbc9-11ea-969a-02d258514e62.png)
![gencount2](https://user-images.githubusercontent.com/63906538/89884247-8f75e880-dbc9-11ea-86db-a6cf1a717b7c.png)

**Comment by ETR-BTF** [comment]
For the record it only creates 1 file, not whatever the generation count was.

**Comment by Cuphat** [comment]
Fixed in commit 46e812a02e38d94d2e4fd8a5178d4f63a6de3534.
