### ISSUE TITLE
Model Colors Match Cosmetics - Patch Files

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1075]
if you use a patched file with item Model Colors Match Cosmetics turned on and then patch it with your own cosmetics, the item models still reflect the cosmetics of whoever made the patch file

**Comment by ETR-BTF** [comment]
![cosmetics](https://user-images.githubusercontent.com/63906538/89884494-ed0a3500-dbc9-11ea-95fe-24ae1cf84f72.png)

**Comment by Cuphat** [comment]
To clarify, this only happens if you patch over custom colors with the defaults, as restoring the originals isn't currently handled.
