### ISSUE TITLE
Piece of Heart and Heart Containers

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#108]
I started new rando and I got so far 2 whole heart containers and 4-6 pieces of heart but its not counting right. I just have 5 hearts with out pieces adding to it.

**Comment by r0bd0g** [comment]
Please post which seed, which settings, and which console/emulator you're using.

**Comment by TopHatMan** [comment]
I am using bizhawk 2.3 and my seed is  OoT_CNGQY9MXUCAAAUA_m09d11y2018-28-comp

I notice that tunic is in castle town so I can not buy it as adult. As well. I went to all dungeons , did all scrubs . Lacking Zelda letter and wierd egg. No Zelda song.

**Comment by r0bd0g** [comment]
I guess I forgot to ask for which randomizer version.

**Comment by TopHatMan** [comment]
You know We minds well close this because I tried to replicate my seed and its not the same. I never made a spoiler log. I feel like Something is missing here. I was using latest dev branch. I will pay close attention to my next fresh seed and record data.
