### ISSUE TITLE
Solved: Putting Important Items in Disabled Locations

### ISSUE THREAD

**Issue by autumnnflowers** [TestRunnerSRL/OoT-Randomizer#1081]
I disabled the Dampe Race Freestanding POH because I struggle with getting the race done in under 1 minute. However, in my most recent randomizer, the Song of Storms was in that spot. I ran out of things to do because I could not get that, and the only "accessible" things for me were some skulltulas that I could not actually get to because I could not reach them with a sword.
Seed: https://ootrandomizer.com/seed/get?id=542222

**Comment by ETR-BTF** [comment]
Can you post your spoiler log or a link to the seed you generated?

**Comment by autumnnflowers** [comment]
> Can you post your spoiler log or a link to the seed you generated?

Edited, sorry about that!

**Comment by ETR-BTF** [comment]
It says that dampe race 2 ("Dampe Race Freestanding PoH" / aka dampe race in under a minute) gives a recovery heart and that storms is inside the crate in the graveyard (on the ledge near dampe's grave). Are you sure you weren't mistaken?

**Comment by Cuphat** [comment]
`    "Dampe Race Freestanding PoH":                           "Recovery Heart",`
`    "Graveyard Freestanding PoH":                            "Song of Storms",`

Yeah, Song of Storms is in the crate that you need to plant a bean or use longshot for (or an out of logic boomerang throw).

**Comment by autumnnflowers** [comment]
> It says that dampe race 2 ("Dampe Race Freestanding PoH" / aka dampe race in under a minute) gives a recovery heart and that storms is inside the crate in the graveyard (on the ledge near dampe's grave). Are you sure you weren't mistaken?

I am genuinely confused because I swear it said it was in the Dampe race, but you are right! Must have mixed the words up somehow.
I must just be missing something then, So sorry to waste your time!

**Comment by ETR-BTF** [comment]
No worries. :) We also have 2 dedicated support channels in the main ootr discord if you encounter any issues. There's an invite at the bottom of the homepage of the ootr website.

**Comment by autumnnflowers** [comment]
> No worries. :) We also have 2 dedicated support channels in the main ootr discord if you encounter any issues. There's an invite at the bottom of the homepage of the ootr website.

Thank you so much! I'll join that right away :)
