### ISSUE TITLE
Mask of Truth hints broken

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1088]
Thom RainierToday at 5:29 AM

https://discord.com/channels/274180765816848384/274186223147417600/750608101975130153

Here's a quick seed to test: https://discord.com/channels/274180765816848384/274186223147417600/750632058572767303
"Every single seed generated: All the Gossip Stones say the same thing. Settings are "Very Strong Hints" and "Requires Mask of Truth"

https://cdn.discordapp.com/attachments/438698093354156032/750633715423510599/unknown.png

Text rando not shuffled either.

This is the current dev build on website, btw

These other seeds are also buggy, according to Whimsical: https://discord.com/channels/274180765816848384/274186223147417600/750626381611794483

**Comment by r0bd0g** [comment]
Random settings league would like to have the possibility of hints requiring mask of truth, but this issue is currently preventing us from having it.

**Comment by Zannick** [comment]
So, the spoilers both locally and on the site for this seed say the gossip stones have different texts. Maybe the patch applied has given them all the wrong text? Or the spoiler entries were actually generated after the patches? I'll try this seed out later to see.

**Comment by Zannick** [comment]
Yeah, it reproduces locally. So we have an issue retrieving the patch content for reading the stones while wearing a mask; probably writing it in the wrong place or the data has been bumped out of the way.

**Comment by Zannick** [comment]
Looks like this was introduced in 32cc6e0 attempting to remove the initial text box for mask hints, but it appears to have only had the effect of showing the text for receiving the Broken Sword and no hint. I'm not familiar enough with the asm to understand why or how to fix it (aside from reverting the particular skip-text feature here).

**Comment by r0bd0g** [comment]
Alright my guess is v0 has your message ID. But then jal 0x79B44 returns your current mask in v0, maybe? It tests you're wearing mask 08, but then the message id has been overwritten so you get the 08'th text. No idea if any of this is true but it sounds like a good guess idk.
