### ISSUE TITLE
Multiplayer Shopsanity Refillables

### ISSUE THREAD

**Issue by friedpen** [TestRunnerSRL/OoT-Randomizer#109]
It appears to be the case that refillables are only granted to the purchasing player despite the Spoiler log stating they are for [Player 1] or [Player 2], unless I am misreading this. This has created a weird scenario in a current coop where my seed contains both 200 rupee Goron Tunics. However, since theirs is sold within a child shop, I do not know if refillables in other worlds are taken into account as this also falls into Issue #90 . Another scenario I haven't seen but wonder is whether or not you can buy a teammate a tunic from the left one-four slots if you already own the tunic or if shop dialogue prevents this. 

Edit: You can buy One Time Deals even if you own them in the case of shields.

Settings : 9J2D2RMVU497RBK
Seed : refilltest
Kokiri Shop Item 4 is Deku Nut (5) [Player 1] on W2P2 in Spoiler Log
Deku Nuts are received on P2 with bizhawk script running.

Edit 2: Zora's Shop within this run contained both 300 rupee Zora Tunics. I checked the spoiler log to test purchasing the one for Player 1 and it went to me instead. Once you have a copy of Zora Tunic it prevents you from buying the other Tunic which may or may not be for another player. Checking the spoiler log at the end of our run it seemed that the playthrough expected Player 2 to buy both tunics.
9: {
  Zora Shop Item 2 [World 2]: Buy Zora Tunic [Player 1]
  Zora Shop Item 6 [World 2]: Buy Zora Tunic [Player 2]
}
This testing was done on 2.16.22 f.LUM with 
Settings : 9J2DS9KXUU3PDCB
Seed: RyanRuinedEverythingWithArcheryPepehands
on W2P2

**Comment by TestRunnerSRL** [comment]
Refillable items are supposed to only spawn in their own world, this is a bug

**Comment by TestRunnerSRL** [comment]
Ok, should be good now
