### ISSUE TITLE
Crash when plandoing Ice Trap without specifying what it looks like

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1090]
ETR_BTF Today at 5:30 AM
"Ocarina of Time": "Ice Trap"
on ocarina shuffle would you need to specify the ice trap model when plandoing? because someone was able to generate a seed from a plando that had this and it kept crashing

ETR_BTF Today at 5:31 AM
"crash happened shortly after the cs starts"
relevant plando file:
https://discordapp.com/channels/274180765816848384/274180765816848384/752443884134727792

Dusk The Umbreon Today at 5:31 AM
https://ootrandomizer.com/seed/get?id=555652 The seed

**Comment by ETR-BTF** [comment]
https://www.twitch.tv/videos/733949626

**Comment by Zannick** [comment]
Should be fixed by 001d782.
