### ISSUE TITLE
BGS and GS Tokens cannot appear in Shops

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#111]
https://youtu.be/criCPAUJr6E

Settings: CEGLC9PWUCA6BG5

Seed: HXLA9CBLQXWLBJNDUMRJWJMBDCYNVEWAPWUUXTRMLURQRIXK9JGYC9XEGFWPUNLAXJUJAPQIBNQMSG9BB

**Comment by r0bd0g** [comment]
Here's another one:

OoT Randomizer Version 2.20.2 f.LUM  -  Seed: X8A5F2OB6M
Settings (V2EQSRNLHHSH36HEQA)

https://cdn.discordapp.com/attachments/438698093354156032/496402749983031328/Capture.PNG

Apparently the text he got was not the same randomized text as he normally gets from buying a GS token.

**Comment by r0bd0g** [comment]
Do GS Token work fine at Chu bowling? I feel like GS Tokens in shops softlocking was an intermittent issue? I never tried it myself though... So who knows if chu bowling works right.

**Comment by TestRunnerSRL** [comment]
I haven't been able to have it happen, so unsure, probably

**Comment by r0bd0g** [comment]
>           I received the same lock (purchasing a token from the Hyrule potion store), without randomized text.
> OoT Randomizer Version 2.20.2 f.LUM  -  Seed: TF5Y522RWC

goldencow2 please supply the settings string for this seed

**Comment by mzxrules** [comment]
> Here's another one:
> 
> OoT Randomizer Version 2.20.2 f.LUM - Seed: X8A5F2OB6M
> Settings (V2EQSRNLHHSH36HEQA)
> 
> https://cdn.discordapp.com/attachments/438698093354156032/496402749983031328/Capture.PNG
> 
> Apparently the text he got was not the same randomized text as he normally gets from buying a GS token.

Looking into this seed now. Made a small but important discovery: There are two dialogs with identical text that are displayed when obtaining Gold Skulltulas: 00B4, and 00B5. In this screenshot, dialog 00B5 is being displayed

**Comment by TestRunnerSRL** [comment]
Something else that is possibly involved? GS Tokens have a separate injection for overriding the item and showing the textbox than other items do. I don't think it's related since the injection is on collecting the GS Token Actor, not from the item, but maybe I'm wrong.

**Comment by goldencow2** [comment]
Sorry
OoT Randomizer Version 2.20.2 f.LUM  -  Seed: TF5Y522RWC
Settings (V22R39NWF49HSNRCGA)

**Comment by TestRunnerSRL** [comment]
Ok fixed, finally. BGS and GS can appear in the bombchu bowling as well

**Comment by r0bd0g** [comment]
Nice
