### ISSUE TITLE
Problems warping after Malon

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1119]
https://clips.twitch.tv/KathishAgileTapirWTRuck

**Comment by fig02** [comment]
is this on romans branch or something? the reload should happen unless it has my malon change

**Comment by r0bd0g** [comment]
Roman's, yes.

**Comment by r0bd0g** [comment]
I believe this has been fixed? Something I noticed with the new malon tho is you get a fair amount of time to control link as the reload occurs? (Feels similar to after opening the silver gauntlet's chest in vanilla.) I dunno if there might be something weird you could do in that time.
