### ISSUE TITLE
"Outside my castle" is on the way of the hero

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#115]
The gossip stone has a castle? It seems to be using the same text as Ganondorf.

(Also, at least in the spoiler log, most locations are not capitalized?)

**Comment by TestRunnerSRL** [comment]
It's using the region's hint property, which I guess has weird names for some stuff. Like 'my castle' for ganon's castle and a few other weird things.

**Comment by TestRunnerSRL** [comment]
Updated the hint texts

**Comment by r0bd0g** [comment]
I'm not sure this is resolved?

Now the light arrows hint, Ganon will say "Ganon's Castle" instead of "my castle."

**Comment by TestRunnerSRL** [comment]
How about this eb4d4fa4097775894fc56839b4f68224202f96ee

**Comment by r0bd0g** [comment]
Look good! Thanks, tr.
