### ISSUE TITLE
Hint reachability method "can_reach_stone" not functioning correctly.

### ISSUE THREAD

**Issue by Cuphat** [TestRunnerSRL/OoT-Randomizer#1155]
`can_reach_stone` sets the item in the location to `None` and then runs a `Search.max_explore` on the worlds. However, the location used for this process still seemingly has the item attached.

![image](https://user-images.githubusercontent.com/15843710/98668879-81e21300-231e-11eb-9823-b912ae0e9692.png)

**Comment by r0bd0g** [comment]
I guess I have a question about hint reachability that I've been meaning to ask, so I'll ask it here. What happens if all remaining stones (or the item that enables hints) are locked by the item the hint is supposed to be for (or are completely unreachable)?

**Comment by r0bd0g** [comment]
What is the practical effect of this bug atm?

**Comment by ETR-BTF** [comment]
> What is the practical effect of this bug atm?

this plando won't generate:
![image](https://user-images.githubusercontent.com/63906538/98992919-0951a100-252e-11eb-9ab7-52ee1c6ba1e9.png)
Specifically it says `No valid hints for user-provided item`.
