### ISSUE TITLE
LACS reward not triggering?

### ISSUE THREAD

**Issue by rchrm5** [TestRunnerSRL/OoT-Randomizer#1157]
[OoT_43A0A_3O9Y1ZA6WA_Spoiler.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/5533075/OoT_43A0A_3O9Y1ZA6WA_Spoiler.zip)

I currently have 3 medallions, 70 skulltulas, and all 3 spiritual stones. Does anyone know why I don't receive the Zora Tunic when entering Temple of Time?

**Comment by aofengen** [comment]
Without being able to look at your spoiler log at the moment, do you have the shadow and spirit medallions? These two medallions are required to trigger the Light Arrow Cutscene reward - as soon as you enter the Temple of Time as adult with these medallions, you will get the item.

**Comment by rchrm5** [comment]
I don't have them - I thought the way the randomizer was worded, that any medallions/stones would suffice to unlock the reward. Didn't know you needed the vanilla requirements for LACS.

**Comment by rchrm5** [comment]
There are options under Shuffle Dungeon Items for Medallions, Stones, Skulltulas, and Dungeon Rewards to access LACS - wasn't aware these were needed in addition to the vanilla requirements.

**Comment by aofengen** [comment]
those options only place ganon's boss key at the LACS location with the given requirements. Otherwise, the vanilla requirements are needed for a randomized item.

**Comment by ETR-BTF** [comment]
In this case it's a TH seed, so ganon's boss key is not in the item pool.

For future cases please visit the support channels in our discord first. ;)
https://discord.gg/8nmX7fa
