### ISSUE TITLE
Slow text buying Fire Arrows

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#117]
Or am I just bad at mashing but I think that was a slow text. Adult kak potion, bring a wallet.

And also this seed, according to the spoiler, has the hint "They say that an unknown treasure&can be found at the market." and I'm not sure to which item it was referring. Should good item hints be excluding shop item types? [This part fixed.]

Settings: BEQJU9MMSCA6VBB
Seed: 776

**Comment by TestRunnerSRL** [comment]
They are supposed to, and I don't think they are

**Comment by TestRunnerSRL** [comment]
Ok, shouldn't get those kinds of hints anymore I hope. The slow textbox I'm not sure about, there's a couple texts like that and I'm not really sure what causes that atm. I know bombchus are also slow

**Comment by r0bd0g** [comment]
Since then I've gotten more slow texts... Hookshot, Bombchus...

**Comment by r0bd0g** [comment]
While most texts have been changed to appear instantly, some text scroll slowly unless you press a button first. And I think these are the ones that are made extra slow by the shop keepers.

**Comment by flagrama** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Slow Item Text](https://trello.com/c/CpYpKIIf/16-slow-item-text)
