### ISSUE TITLE
Inconsistency with the Skull Mask and MoT hints in Scrubs Dist

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1178]
The Skull Mask location is always hinted regardless of whether complete mask shop is on, but if the MoT check is not disabled, it won't be hinted if complete mask shop is on, despite the two checks being mostly equivalent. I think if you add MoT as an always hint to that hint dist, that doing so would override the conditional always, and always hint MoT when the check is enabled. I believe this dist should do its best to support all settings as it is commonly used in variety settings.

**Comment by ETR-BTF** [comment]
Supposedly fixed by #1222, so this can be closed.
