### ISSUE TITLE
Logic issue

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#119]
In my seed  OoT_CNGQY9MXUCAAAUA_m09d11y2018-28-comp using latest dev. In room with invisible spikes in shadow temple. My seed already found hookshot but did not have longshot. To get up to room with locked door you need longshot. I cheated to jump up to that door I went in and found long shot in the room. So that would be impossible for me to get up to with out cheating.

**Comment by flagrama** [comment]
You can backflip onto the small chest in that room to reach the hookshot target with a Hookshot. This is mentioned in the AmazingAmpharos README.

**Comment by TopHatMan** [comment]
Oh well okay lol was going insane.

**Comment by TopHatMan** [comment]
9

**Comment by OlafurKrH** [comment]
oh wait thats possible? I just hookshotted into the invisible platform on one corner, put on the Hover Boots and ran towards the door and also doing a jumpslash :P
