### ISSUE TITLE
Wasteland Skulltula hint accidentally changed to hint Colossus soil instead

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1192]
'Colossus GS Bean Patch':                                      ("a #spider buried in the wasteland# holds", None, ['overworld', 'sometimes']),

**Comment by r0bd0g** [comment]
A number of bugs like this were fixed previously but I guess this one was missed.

**Comment by LostThePirate** [comment]
The buried skull isn't in the Wasteland region, it's in Colossus.

**Comment by r0bd0g** [comment]
This hint is for wasteland skull. The "buried" is about the whole room being under the sands.

**Comment by r0bd0g** [comment]
History since 5.2:

Grammar fix:
https://github.com/TestRunnerSRL/OoT-Randomizer/commit/6e37ba9c4796f3d2a4cf5125a9f48b992e08db07

"Wasteland" made lowercase:
https://github.com/TestRunnerSRL/OoT-Randomizer/commit/be3944e2117189a3ae4879a4b7a49a5e81f857a9

Location renamed to "Haunted Wasteland GS":
https://github.com/TestRunnerSRL/OoT-Randomizer/commit/2480d9629b7748e0dd0cb53426af417e9a7cb432

Location renamed to "Wasteland GS":
https://github.com/TestRunnerSRL/OoT-Randomizer/commit/b5857fb66f9d90f933384e2d1244859bd5d4b454

Hint target mysteriously changed to Colossus Soil:
https://github.com/TestRunnerSRL/OoT-Randomizer/commit/dc174389c726fdcd12526397fee1bf9da8ba1960

The word "buried" is added:
https://github.com/TestRunnerSRL/OoT-Randomizer/commit/08e70033d11c8167f1b097a55fb748991163b0e7

**Comment by r0bd0g** [comment]
Yeah so the Wasteland GS was pointed at colossus soil, then mracsys updated the text to include the word buried, and added a new Wasteland GS hint that hint dists can enable if they want.

So we need to swap which hint or wasteland gs and colossus soil is a normal sometimes hint, and colossus soil needs a new text to not be so easily confused as the wasteland gs.
