### ISSUE TITLE
All Goals Reachable setting

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1196]
As has been discussed in relation to #1165, the All Locations Reachable toggle should be changed into a dropdown, with a new “All Goals Reachable” setting as a compromise between the 2 existing ones.

In this setting, it's guaranteed that all “goal” items (depending on bridge and Ganon bk conditions) are reachable, not just the number required. For example, All Goals Reachable with 1-medallion bridge and 1-skull bk would require all 6 medallions and all 100 skull tokens to be reachable.

This is how triforce pieces currently work in Beatable Only, which #1165 proposes to change. So this setting would allow for the current BO experience in TH.

**Comment by LostThePirate** [comment]
If you load up a Bingo board with Bingo Hints, will this guarantee that all Bingo goals are reachable, too?

**Comment by fenhl** [comment]
I'm not too familiar with how Bingo works, but if that's doable that seems like a reasonable addition as well.

**Comment by LostThePirate** [comment]
Sorry, I misread this at first as a PR, not an issue.
But since the Bingo Hints already can interface with Bingosync, it doesn't seem *too* far a stretch to expand this to accommodate Bingo Goals while not guaranteeing the entire world be reachable.

**Comment by r0bd0g** [comment]
One problem I could see is that ALR/BO is already kind of a confusing setting as to how it works, and this could compound the issue.

(There's also ambiguity over the meaning of the word "location". For example, windmill could be inaccessible as child if the bottom of the well entrance leads to an entrance with no item locations or events inside. But some might assume that every useless house or w/e would be considered a "location" that ought to be reachable.)

**Comment by fenhl** [comment]
I'm hoping that the tooltip can clear up some of this confusion. This is what I currently have:

> This determines which items and locations are guaranteed to be reachable.
>
> 'All': The randomizer will guarantee that every item is obtainable and every location is reachable.
>
> 'All Goals': The randomizer will guarantee that every goal item is obtainable, not just the amount required to beat the game, but otherwise behaves like 'Beatable Only'. Goal items are the items required for the rainbow bridge and/or Ganon's Boss Key, so for example if the bridge is set to 1 Medallion and Ganon's Boss Key to 1 Gold Skulltula Token, all 6 Medallions and all 100 Tokens will be obtainable. In Triforce Hunt, this will also guarantee that all Triforce Pieces can be obtained.
>
> 'Beatable Only': Only required items and locations to beat the game will be guaranteed reachable.

Any suggestions for how to further clarify are welcome.

I think the ambiguity of the word “location” is a separate issue, as any change to the terminology would also have to take into account the “Exclude Locations” list.

**Comment by LostThePirate** [comment]
"Beatable Only" is a bad phrase in a randomizer, since people think that, "Oh, this is the setting I need to use if I don't want an unbeatable seed." That would be why 3.0 moved off of Beatable Only to the phrase All Locations Reachable.

**Comment by fenhl** [comment]
Maybe “Required Only” then?

**Comment by puddydoo** [comment]
> "Beatable Only" is a bad phrase in a randomizer, since people think that, "Oh, this is the setting I need to use if I don't want an unbeatable seed." That would be why 3.0 moved off of Beatable Only to the phrase All Locations Reachable.

They would be right if we moved "No Logic" into this same dropdown (and moved it to main rules, and made Glitchless/Glitched a toggle) because it is the lowest extreme on this continuum and doesn't actually remove literally all forms of logic.
Then it could be 100% Beatable/All Goals Reachable/Beatable Only/Not Guaranteed Beatable.

**Comment by fenhl** [comment]
I like this idea, as well as the analogy to 100% as a speedrun category. In fact, you could explain this setting using that analogy (ALR ~ 100%, AGR ~ AD, BO ~ Any%). I'd still call it “All Locations Reachable” but then explain it that way in the tooltip.
