### ISSUE TITLE
[Suggestion] Flying silent pots shuffle

### ISSUE THREAD

**Issue by TimothieGeulin** [TestRunnerSRL/OoT-Randomizer#120]
Everything is in the title, i was wondering about the possibility to randomly replace some pots in the game with flying aggressive pots... but with a twist! Since they are easily avoidable with all the noise they make, it could also be nice to remove that sound totally.
We could choose the proportion of replacement, like 5%, 10%, 20%, 30%, 50%, 75% or 100% or something else.

**Comment by TestRunnerSRL** [comment]
This request seems to be part of a greater shop shuffle. Not a fan of an option for setting the distribution or their noise tho.

**Comment by TestRunnerSRL** [comment]
Sorry I meant Pot Shuffle. And I'm not really a fan of options that just add annoying mechanics

**Comment by TimothieGeulin** [comment]
So would it be considerable without the annoying mechanics? (So just the random flying pots)

**Comment by TestRunnerSRL** [comment]
This might be something that would be included with pot shuffle as mentioned, but at this point it's probably pretty unlikely that this is a feature to be implemented because of the logic code involved to make it possible. Maybe I'll change my mind about that later.
