### ISSUE TITLE
grottos not mixing with interior aka deku tree dungeon in grotto hole?

### ISSUE THREAD

**Issue by resinate** [TestRunnerSRL/OoT-Randomizer#1204]
in old version u guys had this option in v6 its not there. all dungeons mixed but in same spots. etc

**Comment by Star1468** [comment]
Version 6.0 is the main branch, which does not have mixed pools- that is a feature exclusive to Roman's branch. Please ask questions in our discord (https://discord.gg/7Qfk7DY) first _before_ reporting it here please.

**Comment by resinate** [comment]
says im banned and any chance how do i find romans branch?

**Comment by Star1468** [comment]
Well if you're banned that's not my problem, and https://github.com/Roman971/OoT-Randomizer

**Comment by resinate** [comment]
thank you
