### ISSUE TITLE
Can't exclude song locations with songsanity "off"

### ISSUE THREAD

**Issue by BeeLuigi** [TestRunnerSRL/OoT-Randomizer#1206]
You could do this in 5.2 and it would just force Serenade or Prelude on said location (so you could exclude up to two without further modifications). I believe 5.2.9 took this out again, which was a plando refactor so I think it was unintentional. If this gets fixed it's probably a good idea to implement it for songs on Dungeon Rewards too.

**Comment by r0bd0g** [comment]
Are you playing in settings where pre/ser could possibly be foolish? They can't be, under random spawns.

**Comment by BeeLuigi** [comment]
No, but that's irrelevant. It was possible to do this on 5.2 with full ER. Intended to be even iirc, because I think it even made sure that any song (Serenade or Prelude) on an excluded check wouldn't be used to reach new areas.

**Comment by ETR-BTF** [comment]
I think it's been fixed in dev. Not sure which PR did it though.

**Comment by BeeLuigi** [comment]
Yeah #1240 , thanks for notifying

**Comment by ETR-BTF** [comment]
I thought maybe it was that one but I didn't think plandomizer could be affecting this.
