### ISSUE TITLE
Free Zelda & Items on Song checks incompatible with Multiworld

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1210]
SereneDragon Today at 5:56 PM
Hi, I found a bug when playing a new 6.0 setting with multiworld. We picked the option to skip child zelda. Song from Impa on P2 was supposed to be an ocarina for P1, but P2 ended up getting it instead. It made the seed unbeatable because all the logic was based on P1 having that ocarina. We found out when we got completely stuck and checked the spoiler log.

**Comment by Vicas** [comment]
Hey there, for context, here's the seed itself: https://ootrandomizer.com/seed/get?id=645470

**Generation Date 12/11/2020, 2:50:36 AM UTC -- Seed F0ILZQ7C6A -- Settings String BJTWXCHYK249WH2DN7TAACTLLTDDJ8S8AALACAJAESBSAJAAAKAAA4JJFAB**

If you need any other info I can provide it

**Comment by LostThePirate** [comment]
It's not an items on songs checks issue, that works fine elsewhere; definitely SCZ specific.
