### ISSUE TITLE
Ice Traps ignore Slow Chest Cutscenes setting

### ISSUE THREAD

**Issue by ZNemesis** [TestRunnerSRL/OoT-Randomizer#1218]
When the following settings are used:
Ice Traps appear as Major Items
Chest Size Matches Contents enabled
Fast Chest Cutscenes disabled

Large chests have the long opening animation if the item inside is not an ice trap, but it will have the fast animation if it is an ice trap.

What I expected to happen:
All large chests have the long opening animation, regardless of contents.

**Comment by r0bd0g** [comment]
Issue #1073 seems to suggest that the reverse issue is the case, that big chest ice traps have the slow cutscene and small chests with ice traps also have the slow chest cutscene. Perhaps that was changed? I suspect the issue may be that the way the game s currently set up, you cannot have it both ways: It either needs to be slow or fast regardless of chest size, as chest speed depends on the item inside the chests, with ice traps as the only item that can appear in both sizes.

**Comment by ZNemesis** [comment]
With the same settings, in a multiworld game, Ice Traps that you find for another player correctly use the slow chest speed. Ice Traps for yourself are still fast.

(so both speeds can exist in the same game, but if it can't, I agree that it should be fast in all cases except if those particular settings are used)

**Comment by fenhl** [comment]
I suspect that major ice traps would have to be modified to give the “you are a fool” text to fix this properly. A possible fix would be to internally add a new separate item for major ice traps if chest cutscenes are slow.
