### ISSUE TITLE
Cannot assign item Compass (Shadow Temple) to location Song from Impa.

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1227]
I believe there is currently a problem with skip child zelda and map/compass anywhere? Not sure the full extent of this issue...

This seed failed to gen with that error: https://ootrandomizer.com/seed/get?id=678265

**Comment by ETR-BTF** [comment]
Aren't Maps and Compasses invalid starting items? Maybe it has something to do with that?
