### ISSUE TITLE
(Multiplayer) Shop softlock

### ISSUE THREAD

**Issue by TimothieGeulin** [TestRunnerSRL/OoT-Randomizer#123]
Was in multiplayer (2P)
Bought a deku shield and received a token at the same time resulting in the token being displayed first and getting stuck.
![sans_titre_3](https://user-images.githubusercontent.com/31931443/45499181-276bbd00-b77c-11e8-85de-80b27dd0c6de.png)

**Comment by TimothieGeulin** [comment]
[OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P1_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2380003/OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P1_Spoiler.txt)
[OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P2_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2380004/OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P2_Spoiler.txt)

**Comment by TestRunnerSRL** [comment]
This sounds like the same issue as #111, so it's probably some weird problem with skulltulas

**Comment by friedpen** [comment]
Just ran into this problem in a playthrough. Occurred when my teammate queued up Gerudo Membership Card right as I bought a Deku Shield as Adult in Goron shop. Curious if its possible that the game is trying to equip the received item after the dialogue completes or if something else with dialogue boxes is causing this?

**Comment by TestRunnerSRL** [comment]
Hmmmmm, no it sounds like there's a period between buying and receiving the item that the game is able to give the queued item, and since anything involving NPC and text is super unstable, so it just softlocks. Not totally sure the best way to handle this except maybe not queue items when you're in a shop?

**Comment by TimothieGeulin** [comment]
Well that seems a pretty good solution yeah

**Comment by TestRunnerSRL** [comment]
I'll assume this is fine for now. Let me know if something like this happens again
