### ISSUE TITLE
Spoiler log does not list model for ice trap in Bombchu Bowling

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1235]
If a freestanding piece of heart location has an ice trap, the spoiler log includes the `"model"` key listing its appearance. This information is missing if the ice trap is on a Bombchu Bowling prize.

Example plando:

```json
{
    "locations": {
        "Market Bombchu Bowling First Prize": "Ice Trap",
        "Market Bombchu Bowling Second Prize": "Ice Trap"
    }
}
```

**Comment by flagrama** [comment]
Could you see if #1247 fixes this? It also seems to have affected what was shown in-game, showing the default model instead of any cloak models.

**Comment by fenhl** [comment]
Looks like it!
