### ISSUE TITLE
Locked out of Mask Quest

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1239]
https://clips.twitch.tv/ImpartialDarkPresidentDxAbomb

You can't receive items while the title card is on screen, so I guess this is a rando specific bug caused by the text speedups? It's also kind of strange that it sets the flag for the mask quest before you actually receive the item...

**Comment by ETR-BTF** [comment]
I just reproduced this on v6.2.192. It's very reminiscent of the bug where you can "buy" A Hylian Shield from the Bazaar and leave before getting the shield. Of course that purchase doesn't set a flag so there's no softlock and you can just re-enter the Bazaar and try to buy it again. But it really feels like this is the same bug, which I think is Collection Delay?

The title card part enters into this bug in that if you confirm a shop item after the title card is gone, you can't take any steps before getting the item and therefore can't leave the shop in time. It seems that the faster you confirm/buy an item after entering a shop, the easier it is to exit the shop quickly before receiving the item.
