### ISSUE TITLE
(Multiplayer?) Mask shop softlock

### ISSUE THREAD

**Issue by TimothieGeulin** [TestRunnerSRL/OoT-Randomizer#124]
I heard that it was already repaired some time ago but here it is:
![sans_titre_2](https://user-images.githubusercontent.com/31931443/45499278-639f1d80-b77c-11e8-919e-7523fddffb29.png)
Don't know if it's linked to the multiplayer or not

**Comment by TimothieGeulin** [comment]
[OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P1_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2380014/OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P1_Spoiler.txt)
[OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P2_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2380015/OoT_DNGCSHMXUCSCAYB_STREAMINGA2_W2P2_Spoiler.txt)

**Comment by TestRunnerSRL** [comment]
Should be fixed in 68db1f17dd020393e6c5483bc337518c66a80469
