### ISSUE TITLE
Vanilla Bridge spawns when it shouldn't

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1255]
If you have all meds and all songs (time and storms not required) the bridge will spawn even if you don't have light arrows.

**Comment by Zannick** [comment]
Does anyone have a recent seed/repro for this? Is this vanilla behavior or just when we've set bridge=vanilla?

**Comment by r0bd0g** [comment]
If this were vanilla behaviour you'd think that somebody would have noticed that the bridge spawns without actually obtaining the light arrows. I think we have code for the bridge requirement that for some reason doesn't work correctly if every bit in the medallion and song bytes are set (the bytes set by saw and broken sword rba). At one point I remember seeing this code and somebody pointed to something that looked like the cause of the bug.

**Comment by Hamsda** [comment]
> Is this vanilla behavior or just when we've set bridge=vanilla?

Checked on gz real quick and, as expected, LA are required to spawn the bridge, no matter what I turned on in the quest status screen.

**Comment by Zannick** [comment]
Current asm code for vanilla bridge looks like this:

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/7b4f56ec1f2e971b8b0fa7abb3e8bdb49144051a/ASM/src/rainbow_bridge.asm#L151-L164

if I'm reading it right, it says `if item in light arrows slot == light arrows, branch to @@return`. I don't think that's inverted or the bridge would require not having lights ever. But maybe it's possible that the slot or item id is wrong (drift?)?

**Comment by r0bd0g** [comment]
Have we confirmed it's still broken? It's kind of an annoying thing to test.

**Comment by Roman971** [comment]
It's still broken afaik, but it doesn't happen very often so it easily goes under the radar. And yeah the problem is if you have every medallion and every song (aside from song of time and storms), the & 0xFFFF check will be true since that fills all the first 16 bits in the quest items variable. 0xFFFF was probably treated as a value that wouldn't happen normally, but that's not actually the case.

**Comment by r0bd0g** [comment]
If it's an equality test that happens at the bottom then a value that actually wouldn't be used is any that doesn't the shadow and/or spirit medallions since you have to have them to get to the lights check anyway.
