### ISSUE TITLE
Specifying --settings prevents generation

### ISSUE THREAD

**Issue by aplumafreak500** [TestRunnerSRL/OoT-Randomizer#1257]
```
OoT Randomizer Version 6.0.22 f.LUM  -  Seed: YRQNY18SKM
(Original) Settings string: AJLSXFCSKASBJAAZNAAAANCUSWJAAAAAAJCAASGJUCA

Generating World 1.
Creating Overworld
'dict' object has no attribute 'logic_rules'
Traceback (most recent call last):
  File "./OoTRandomizer.py", line 62, in start
    main(settings)
  File "/home/arcticluma113/OoT-Randomizer/Main.py", line 56, in main
    spoiler = generate(settings, window=window)
  File "/home/arcticluma113/OoT-Randomizer/Main.py", line 121, in generate
    worlds = build_world_graphs(settings, window=window)
  File "/home/arcticluma113/OoT-Randomizer/Main.py", line 146, in build_world_graphs
    create_dungeons(world)
  File "/home/arcticluma113/OoT-Randomizer/DungeonList.py", line 105, in create_dungeons
    if world.settings.logic_rules == 'glitched':
AttributeError: 'dict' object has no attribute 'logic_rules'
```

This happens if either settings.sav is present or if you specify --settings on the command line. Unsure if this happens in the GUI (I have no way to test this).

Edit: Attempted in Python 3.6 and 3.8.

**Comment by Zannick** [comment]
I'm unable to reproduce this except by intentionally mangling the line, but it gets me
```
AttributeError: 'Settings' object has no attribute 'logic1_rules'
```
which is notably different--`world.settings` should be a Settings object, not a dict.

Do you have any local changes? Does this reproduce with a clean checkout?

**Comment by aplumafreak500** [comment]
I did have a clean checkout.

**Comment by Zannick** [comment]
Then I will need more details. What's your full commandline? I used `python3 OoTRandomizer.py --settings_string AJLSXFCSKASBJAAZNAAAANCUSWJAAAAAAJCAASGJUCA --seed YRQNY18SKM` as well as `python3 OoTRandomizer.py --settings_string AJLSXFCSKASBJAAZNAAAANCUSWJAAAAAAJCAASGJUCA --convert_settings > settings.sav` followed by `python3 OoTRandomizer.py`. (python3 is Python 3.8.6 for me)

Are you using plando or any other non-shared settings? Can you provide your full settings file?

**Comment by aplumafreak500** [comment]
Whoops... I realized there was an error in my settings.sav (which I have to manually edit because I'm on a system that doesn't support the GUI). Namely, there shouldn't be an encapsulating "settings" tag before the settings data (as is the case in spoiler logs and plandos).

Closing. Apologies for unnessisarily taking up your time...
