### ISSUE TITLE
[Suggestion] (Multiplayer) Client/Server history for stability

### ISSUE THREAD

**Issue by TimothieGeulin** [TestRunnerSRL/OoT-Randomizer#126]
Having each clients and the server saving every items passing through them would be a solution to the desync caused by bugs or disconnections (in which one player would get an item for another, but that another wouldn't get it).
This way, the server could interrogate the clients to make sure that everyone is synchronized and if not, it could resend every missing items and retrieve the one that he himself is missing

**Comment by TimothieGeulin** [comment]
Example of how it could work:
[ - P1 is server, P2 and P3 are clients.
  - Item(Px) is Px's item.                    ]
>P1 get Bow(P2)
>P1's server write "Bow(P2)"
>P1's server check if P2 and P3 are missing something by asking them their saves
>P2 and P3 are both missing "Bow(P2)"
>P1 send "Bow(P2)" to both
>P3 write "Bow(P2)" but do nothing, because he's not concerned
>P2 write "Bow(P2)" and get his bow IG.

Now with a disconnection:

>P1 get Bow(P2)
>P1's server write "Bow(P2)"
>P1's server check if P2 and P3 are missing something by asking them their saves
>P3 is missing "Bow(P2)" and P2 is not responding
>P1 send "Bow(P2)" to P3
>P3 write "Bow(P2)" but do nothing, because he's not concerned
>P2 finally reconnect
>P1's server check if P2 is missing something by asking him his save
>P2 is missing "Bow(P2)"
>P1 see that he is missing P2's "Kokiri Sword(P1)"
>P1 send "Bow(P2)" to P2 and get "Kokiri Sword(P1)" from P2
>P2 write "Bow(P2)" and get his bow IG.
>P2 write "Kokiri Sword(P1)" and get his sword IG.
(Same sync is done with P3, just to make sure he's not behind)

**Comment by TimothieGeulin** [comment]
Sometimes, and i don't know why, someone disconnect but the server doesn't notice it and is still able to send it items (thus provoking the loss of said item).
Also when game get stuck (like in my previous issues) an item is got but since there's no way to save at this point, the item is lost.

I know that it's hard, that's exactly why I proposed an external save. This way the script would still only give item (and never have to verify if the item is there IG) it will just give the item if the save say "This item i just got must be given to the player". It's like externalizing the IG inventory to be able to check more easily. So the save will list items that have been taken, and flag the newly retrieved one, so that it will know if it have to give those items or not. Also even in case of a fail (like quiting without saving, leading to the loss of all items got after the last save) players would still be able to flag missing items in the save file, leading to the script giving them again.

Finally, it can also prevent duplicate (like if i get a token for P2, load without saving and take it again) by checking if the item is already there in the save.

**Comment by TestRunnerSRL** [comment]
Well, most of that mechanism already exists. If you get an item twice it will only send it once. If you restart the game, it'll regive any items that you just lost from the other player you are supposed to have. Making it know that an item wasn't transmitted between players is something that I don't believe your suggestion fully covers, and having it work in a reasonable way not really make too much sense. Like if you reload the script how does it know if it should reload the save or not, and if there is an discrepancy between the game's save and the script's save then there will be problems, which can happen quite easily

**Comment by TestRunnerSRL** [comment]
I pushed an update to the co-op repo that saves the cache I had mentioned earlier to disk. So it should persist even if you restart the script.

**Comment by TestRunnerSRL** [comment]
this is basically implemented as is
