### ISSUE TITLE
Locked in Kokiri Forest?

### ISSUE THREAD

**Issue by MystBunny** [TestRunnerSRL/OoT-Randomizer#1263]
https://ootrandomizer.com/seed/get?id=725906

I set it so I need the sword and shield to get past Mido, but need the bomb bag to get to the sword. I don't see the bomb bag in the spoiler. Also is the sword considered a progression item? Because I thought I had removed all grottos from the pool.

**Comment by Cuphat** [comment]
`"KF Shop Item 7":                                   "Bombchus",`

You have bombchus in logic and that is a "special deal" slot that you can buy with no requirements. And while you disabled a lot of grottos, you did not disable the one that the sword ended up in.

**Comment by MystBunny** [comment]
Oh... Bombchus are bombs... I'm a dumb bunny
