### ISSUE TITLE
[Feature] Add the ability to randomize inputs

### ISSUE THREAD

**Issue by woodne** [TestRunnerSRL/OoT-Randomizer#1264]
I think it would be fun to randomize the inputs for the game. Is this even possible?

**Comment by aofengen** [comment]
This sounds more like an emulator option, rather than something that would ever be implemented in rando. I do not believe it's possible to dynamically randomize the inputs within the game itself

**Comment by LostThePirate** [comment]
Yup, this sounds like something goofy to ask the ModLoader64 peeps or others about, not something native to Rando.
