### ISSUE TITLE
Starting with Nayru's Love in Minimal Item Pool and Quad/OHKO

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1283]
If you start with Nayru's, the item is not properly removed from the pool, and so the seed has a duplicate Nayru's.

**Comment by r0bd0g** [comment]
This is a weird little regression, so I'll call it out as something I'd like to see handled prior to another release.

**Comment by Zannick** [comment]
Do you have a seed where this occurs, or under a particular setting?

**Comment by r0bd0g** [comment]
We had one in RSL a while back but I don't have the seed anymore. The problem settings are minimal item pool and start with Nayru's Love -- there will still be a Nayru's Love in the pool despite starting with one.

**Comment by Zannick** [comment]
I see minimal item pool adds another Nayru's under ohko and quadruple damage, maybe this is it?

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/c95d62b125a4361351a5d19827ef48e98b56989f/ItemPool.py#L1340-L1341

**Comment by r0bd0g** [comment]
Ah. I think Nayru's was added back perhaps without realizing it was already added back under ohko/quad?

**Comment by r0bd0g** [comment]
Here's a seed to confirm: https://ootrandomizer.com/seed/get?id=890287

**Comment by Zannick** [comment]
I think it's more like this line is ensuring that a Nayru's exists in the world after we've already formed the pool based on starting items (which would make there be 0 Nayru's) and minimal (also 0 Nayru's). Maybe it should be checking starting items as well.

**Comment by r0bd0g** [comment]
I think it was added back for ohko/quad and then somebody who didn't know or forgot about this added it back for everything.

**Comment by r0bd0g** [comment]
I rolled a seed without starting with nayru's to see if there would still be 2, and there wasn't.

**Comment by r0bd0g** [comment]
It's strange, #1230 says it's only added Nayru's back in minimal ohko/quad.

**Comment by r0bd0g** [comment]
Okay I have no idea what's going on lol.
The intention is for nayru's to only be back in minimal pool if quad/ohko is on. But if you start with it you still get one in the pool anyway.

**Comment by Zannick** [comment]
Yes, it's probably like I said, it's being added to the pool regardless of starting items. Looking at the code, nothing else is being added in this way in this section. Probably the fix is to just additionally check whether Nayru's is a starting item.

**Comment by r0bd0g** [comment]
That would fix it but I'm not sure why Nayru's would need to be handled this way when other items properly remove themselves from the pool.

**Comment by Zannick** [comment]
I've got a better fix coming. The way minimal works is by capping the pool contents, which I think happens after removing things from the pool. So instead of adding Nayrus back to the pool (which is what the previous fix did), I've changed the cap on Nayrus to be dependent on quad/ohko.

**Comment by r0bd0g** [comment]
Do we really want it to only be in the pool in quad/ohko? I'm not really sure why it's being done like that...

**Comment by Zannick** [comment]
As in, why does minimal otherwise exclude Nayru's?

**Comment by r0bd0g** [comment]
It used to be a "difficulty" setting where if you put it on hardest you'd get ohko, no health upgrades, no nayru's... It was separated into item pool and damage multiplier, and removing nayru's was kept in with item pool aspect of that. Later, nayru's was added back but ONLY for quad/ohko which is pretty funny.

**Comment by Zannick** [comment]
It's a logical option for surviving damage. I don't mind adding it back to minimal in all cases... We're not very consistent about what's okay to drop out of minimal. We reduce all non-progressive copies of major items to 1, remove all the capacity upgrades, and drop Nayru's and Double Defense. I don't think we drop any conditionally-foolish items, and it looks like we leave in Ice Arrows.

I can see the point of minimal is more about omitting useful but not required upgrades--Nayru's occupies a weird state of potentially being both (it's usable logically outside of quad/ohko for accessing GC grotto, for example). Of course, if Nayru's isn't in the pool, the generator can still make a seed without it, but maybe we shouldn't exclude it just to make minimal harder.

**Comment by r0bd0g** [comment]
Could do a new option to remove nayru's from the pool, maybe consider it the final piece of breaking the old difficulty option apart. On the other hand you can do that with plando already, right?
