### ISSUE TITLE
Annoying Floor Switches in Master Quest

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1288]
The floor switches that were annoying to press (I guess because they were placed too high) in vanilla were long ago fixed to be easier to step on, but there are many such switches in MQ that have not been touched.

**Comment by r0bd0g** [comment]
I looked through my notes and found this list of 5 problematic switches. Let me know if you've run into any others...

1. Fire temple MQ flame wall maze
2. Fire temple MQ... uhhh whatever the hammer chest room from vanilla is called
3. Top of Deku main room (particularly when pressed as adult)
4. In MQ fire the blue switch where the map chest is in vanilla
5. I've bonked on the switch in the first room of MQ Forest a few times

**Comment by fenhl** [comment]
This was fixed in #1459.
