### ISSUE TITLE
Maps and Compasses don't give info if "Misc. Hints" is disabled

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1296]
If you enable m/c give info but disable misc. hints (in the "other" tab), then maps and compasses don't give info. I'm assuming this is just an oversight. the misc hints option also affects ganondorf's light arrows hints, so currently it is impossible to both get m/c info and not get LA info, which I don't think was the intention of that feature.

Edit: To clarify: the pedestal won't give info either if misc. hints is disabled, so you'd be playing a seed with no dungeon rewards info at all.

**Comment by ETR-BTF** [comment]
#1212

**Comment by fenhl** [comment]
This is definitely an oversight. The intent of the misc. hints toggle was to cover everything that's not covered by other settings already, which includes dungeon info from the pedestal when m/c info is *off*. When m/c info is *on* however, that setting covers those hints, so misc. hints off is not supposed to interfere.
