### ISSUE TITLE
Bugged playthrough/required item list generation in Keysy mode and non-keysanity mode

### ISSUE THREAD

**Issue by BeeLuigi** [TestRunnerSRL/OoT-Randomizer#131]
https://pastebin.com/GB4fHqSz

The playthrough/required item list generation is bugged in non-keysanity modes if a required item is in certain parts of Fire Temple. This is probably because of the changes to the locked door in Fire Temple in version 2.17.21. 

The same bugged behaviour appears in most (if not all) spoiler logs of Keysy mode seeds since it's implementation. 

The probable cause is that the collection of keys in Keysy mode and the one Fire Temple Small Key in non-keysanity in Itemlist.py somehow aren't used/known by the playthrough/required item list creation.

**Comment by Nicholas-Steel** [comment]
I believe Robdog has fixes for the playthrough stuff in the spoiler for all gameplay modes.

**Comment by TestRunnerSRL** [comment]
Should be fixed now
