### ISSUE TITLE
Applying .zpf files with periods in the name results in mis-named outputs

### ISSUE THREAD

**Issue by dewiniaid** [TestRunnerSRL/OoT-Randomizer#1314]
I have a plando I've released with a couple minor revisions so far.  The current latest version of it is distributed as: 

`Plando-YPSDKYH-by-Dewiniaid-FINAL-v1.2.zpf`

However, the randomizer is apparently cutting off the extension (to produce a .z64 file extension and spoiler logs) on the wrong period, and yields:

`Plando-YPSDKYH-by-Dewiniaid-FINAL-v1.z64` (or similar)

**Comment by flagrama** [comment]
It's stopping at the first `.` and assuming the rest is the extension.
