### ISSUE TITLE
Graveyard walls aren't ledge grabbable like they should be

### ISSUE THREAD

**Issue by dotzo** [TestRunnerSRL/OoT-Randomizer#1322]
This entire setup ([https://youtu.be/OOHLEP0Ew4c?t=4828](https://youtu.be/OOHLEP0Ew4c?t=4828)) works identically on vanilla 1.0. The changes to the graveyard graves must have bled over into the walls of the graveyard so that these ledge grabs no longer work.

**Comment by mzxrules** [comment]
this is on my list of "things to look into", but I don't have plans on getting to it within the next two weeks
