### ISSUE TITLE
1 TP Hunt with a TP on Impa in Skip Child Zelda

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1331]
I can only assume nobody thought about this and it's an impossible seed. I guess in theory the credits should immediately roll??

**Comment by Roman971** [comment]
This should already be handled afaik. There is a check in place to ensure you don't start with more triforce pieces than the number of triforce pieces in the goal.

I did a quick test starting with 1 piece and having a 1 piece goal, and it gives this error as expected:
`Too many Triforce Pieces in starting items. There should be at most 0 and there are 1.`

For reference, this is the plando file I used to test it:
```json
{
    "settings": {
      "triforce_hunt": true,
      "triforce_goal_per_world": 1
    },
    "starting_items": {
      "Triforce Piece": 1
    }
}
```

**Comment by r0bd0g** [comment]
What if the TP is from Zelda on Skip Child Zelda?

**Comment by fenhl** [comment]
Does not generate an error.

**Comment by r0bd0g** [comment]
To be clear, no error is a bad thing here.

(I would suggest also that the fix should be to ban a tp from impa song on scz if you start with 1 less tp than the goal.)

**Comment by fenhl** [comment]
I'm going to try to write a fix via ban. I have something that works when the location is plando'd, just need to test whether it works when generated naturally.
