### ISSUE TITLE
[Feature Request] any chance of porting OOT3DR's bombchu drop mechanic?

### ISSUE THREAD

**Issue by CocaineJohnsson** [TestRunnerSRL/OoT-Randomizer#1332]
Didn't see any feature requests for it, so I'm making it. It would save a lot of time in a lot of seeds, most of that time being mindless rupee farming (neither challenging nor interesting).

At any rate, time saving or no, I don't see how it's meaningfully different from a gameplay or logic perspective compared to sticks, nuts, arrows, seeds, bombs, or magic refills (among others) being drops (grass, pots, enemies, whatever) as well as buyable

**Comment by aofengen** [comment]
Bombchu drops exist on another version of the dev branch, but have not yet been completed to be added to the main randomizer. When that is done, they will be added

**Comment by ETR-BTF** [comment]
This is the aforementioned fork. You'll need to enable "chus in logic" tho. Enjoy. :)
https://github.com/Roman971/OoT-Randomizer/

**Comment by CocaineJohnsson** [comment]
Okay, thank you. I didn't think to check the forks, so then the answer is "yes, it will be added". Then I might as well close this FR since it's already being worked on, true?

**Comment by aofengen** [comment]
It will be PR'd when it's ready. Whether or not it will be added will be up to the main devs, so it's not guaranteed. Different dev teams have different priorities
