### ISSUE TITLE
[Feature Request] Multiworld ID Identification

### ISSUE THREAD

**Issue by Crain-32** [TestRunnerSRL/OoT-Randomizer#1334]
When generating a multiworld ROM, instead of "File 1", you instead have "File {ID}", so that you can be 110% confident that you're on the correct ROM.

**Comment by flagrama** [comment]
Might be something to mention over in [this PR](https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1182). IMO it's probably the best way to implement this. Your proposed way would require editing the texture for every generated ROM.
