### ISSUE TITLE
Foolish hints still say "Ganon's Castle" rather than "Inside Ganon's Castle"

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1337]
WotH was changed to always differentiate between inside and outside Ganon's, but this was not done for foolish.

**Comment by r0bd0g** [comment]
Any news on this issue? It's a weird consistency issue I think ought to be cleaned up soon. The problem is that foolish hints are not using the dungeon hint name, which is intended, but means the fix for "Inside Ganon's Castle" for WotH can't be applied.

**Comment by Zannick** [comment]
We can specify a hint name separate from the dungeon name, that should work.

**Comment by Zannick** [comment]
Wait, nevermind, the dungeons themselves have their own hints, that's how we have "Ganon's Castle" and not "Ganons Castle". That's easy to fix.
