### ISSUE TITLE
How do I run the offline build?

### ISSUE THREAD

**Issue by MystBunny** [TestRunnerSRL/OoT-Randomizer#1338]
It said I needed Python, so I downloaded the latest version of Python, but I'm getting the same message. Something about a command line switch. Don't know how to do any of that.

**Comment by ETR-BTF** [comment]
Please visit our setup support channel on Discord for help with setting up the randomizer. :)
https://discord.gg/nscuQk8E

**Comment by MystBunny** [comment]
I don't have Discord.

**Comment by Zannick** [comment]
Are you running the `Gui.py` or the `OoTRandomizer.py`? You should be able to run the Gui and have it take care of the setup for it.

**Comment by MystBunny** [comment]
Thanks. I'm downloading and running the Windows installer, then I try to run it and I get this, then it closes.
![image_2021-07-10_19-51-03](https://user-images.githubusercontent.com/79949095/125179851-5454ae80-e1b8-11eb-98d6-7e13bb2c8a3d.png)

**Comment by TreZc0** [comment]
Make sure to install Python with the pythonpath option, or follow this guide 
https://datatofish.com/add-python-to-windows-path/
