### ISSUE TITLE
Using Din's Fire on White Bubbles crashes the game

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1354]
Known and understood vanilla bug. This is merely for documentation purposes.

**Comment by ETR-BTF** [comment]
https://github.com/zeldaret/oot/blob/master/src/overlays/actors/ovl_En_Bb/z_en_bb.c#L1162

**Comment by ETR-BTF** [comment]
https://discord.com/channels/274180765816848384/438697911753113600/872842801040207944

**Comment by Pokechu22** [comment]
I ran into this in a multiworld randomizer by accident and it resulted in some chaos (due to my own not saving, and it also causing a hang resulting in a non-clean disconnect where I was still technically on the server but also wasn't). It'd be nice to include a fix for this.
