### ISSUE TITLE
Named item hints fail to generate

### ISSUE THREAD

**Issue by mracsys** [TestRunnerSRL/OoT-Randomizer#1363]
The below plando adds Light Arrows as a required named-item hint. Confirmed working on 6.0.61, now fails on 6.0.81 with the error "No valid hints for user-provided item".

Stack trace:
```
No valid hints for user-provided item
Traceback (most recent call last):
  File "C:\git\OoT-Randomizer-Fork\OoTRandomizer.py", line 62, in start
    main(settings)
  File "C:\git\OoT-Randomizer-Fork\Main.py", line 56, in main
    spoiler = generate(settings, window=window)
  File "C:\git\OoT-Randomizer-Fork\Main.py", line 123, in generate
    return make_spoiler(settings, worlds, window=window)
  File "C:\git\OoT-Randomizer-Fork\Main.py", line 192, in make_spoiler
    buildGossipHints(spoiler, worlds)
  File "C:\git\OoT-Randomizer-Fork\Hints.py", line 703, in buildGossipHints
    buildWorldGossipHints(spoiler, world, checkedLocations.pop(world.id, None))
  File "C:\git\OoT-Randomizer-Fork\Hints.py", line 888, in buildWorldGossipHints
    raise Exception('No valid hints for user-provided item')
```

Plando:
```
{
   "settings":{
      "bridge":"vanilla",
      "hint_dist_user":                          {
      "name":                  "Melrose",
      "add_locations":         [
          { "location": "Deku Theater Skull Mask",    "types": ["always"]}
          ],     
      "remove_locations":      [],    
      "add_items": [
            {"item":"Light Arrows", "types":["named-item"]}
],  
      "remove_items":          [],
      "dungeons_woth_limit":   1,
      "dungeons_barren_limit": 1,
      "named_items_required":  true,
      "vague_named_items":     false,
      "distribution":          {
          "trial":      {"order":  1, "weight": 0.0, "fixed":   0, "copies": 1},
          "always":     {"order":  2, "weight": 0.0, "fixed":   0, "copies": 2},
          "woth":       {"order":  3, "weight": 0.0, "fixed":   2, "copies": 2},
          "barren":     {"order":  4, "weight": 0.0, "fixed":   3, "copies": 2},
          "entrance":   {"order":  5, "weight": 0.0, "fixed":   0, "copies": 2},
          "sometimes":  {"order":  13,"weight": 0.0, "fixed":  99, "copies": 2},
          "random":     {"order":  7, "weight": 0.0, "fixed":   0, "copies": 2},
          "item":       {"order":  8, "weight": 0.0, "fixed":   1, "copies": 2},
          "song":       {"order":  9, "weight": 0.0, "fixed":   0, "copies": 2},
          "overworld":  {"order": 10, "weight": 0.0, "fixed":   0, "copies": 2},
          "dungeon":    {"order": 11, "weight": 0.0, "fixed":   0, "copies": 2},
          "junk":       {"order": 12, "weight": 0.0, "fixed":   0, "copies": 1},
          "named-item": {"order": 6,  "weight": 0.0,  "fixed":  0, "copies": 2}
            }
         }
      }
}
```

**Comment by DobbyDigital** [comment]
Huh, weird. It seems like the error still pops up if you set misc_hints to False. I figured it was the Ganondorf LA hint causing issues, but that should have fixed it

**Comment by DobbyDigital** [comment]
The following works as anticipated (and seems to be the equivalent to the output from the original plando, if I understand correctly):

`{
   "settings":{
      "bridge":"vanilla",
      "misc_hints":                              true,
      "hint_dist_user":                          {
      "name":                  "Melrose",
      "add_locations":         [
          { "location": "Deku Theater Skull Mask",    "types": ["always"]}
          ],     
      "remove_locations":      [],    
      "add_items": [
            {"item":"Light Arrows", "types":["named-item"]}
],  
      "remove_items":          [],
      "dungeons_woth_limit":   1,
      "dungeons_barren_limit": 1,
      "named_items_required":  false,
      "vague_named_items":     false,
      "distribution":          {
          "trial":      {"order":  1, "weight": 0.0, "fixed":   0, "copies": 1},
          "always":     {"order":  2, "weight": 0.0, "fixed":   0, "copies": 2},
          "woth":       {"order":  3, "weight": 0.0, "fixed":   2, "copies": 2},
          "barren":     {"order":  4, "weight": 0.0, "fixed":   3, "copies": 2},
          "entrance":   {"order":  5, "weight": 0.0, "fixed":   0, "copies": 2},
          "sometimes":  {"order":  13,"weight": 0.0, "fixed":  99, "copies": 2},
          "random":     {"order":  7, "weight": 0.0, "fixed":   0, "copies": 2},
          "item":       {"order":  8, "weight": 0.0, "fixed":   1, "copies": 2},
          "song":       {"order":  9, "weight": 0.0, "fixed":   0, "copies": 2},
          "overworld":  {"order": 10, "weight": 0.0, "fixed":   0, "copies": 2},
          "dungeon":    {"order": 11, "weight": 0.0, "fixed":   0, "copies": 2},
          "junk":       {"order": 12, "weight": 0.0, "fixed":   0, "copies": 1},
          "named-item": {"order": 6,  "weight": 0.0,  "fixed":  1, "copies": 2}
            }
         }
      }
}`

**Comment by Cuphat** [comment]
I generated on every version starting at 6.0.61 working up. It breaks on version 6.0.79 (commit 1599f62adc2d2b46171657ba4c74f41180129559) which is the massive "stop dumping the entire settings dictionary into world and use world.settings instead" PR. It's probably something relatively simple that was missed during that.
