### ISSUE TITLE
Dungeon Info display - Medallion/Stone info

### ISSUE THREAD

**Issue by friedpen** [TestRunnerSRL/OoT-Randomizer#138]
Medallion/Stone info seems bugged when it comes to compass collection. On a keysanity seed, (maps/compasses, smalls, and bigs anywhere), the compass does not present info for the dungeon's completion. On a non keysanity seed, (maps/compasses, smalls, and bigs in dungeons), all dungeon completion info is available from the start. 

![solokeys](https://user-images.githubusercontent.com/28878669/45600150-f7aff580-b9c5-11e8-8129-2c1362dc3e6e.png) ![test](https://user-images.githubusercontent.com/28878669/45600151-f979b900-b9c5-11e8-819d-4146d662c287.png)

Left Image
OoT Randomizer Version 2.18.2 f.LUM  -  Seed: solokeys
Settings (922RATMXEX55REEA):
Deku compass in top left Mido chest.

Right Image
OoT Randomizer Version 2.18.2 f.LUM  -  Seed: test
Settings (R23RAT5LAX55REEA):

edit : Medallions/Stones are currently attached to Maps instead of Compasses.
![solokeys2](https://user-images.githubusercontent.com/28878669/45601848-69496d00-b9e1-11e8-8f6d-3a0f8240f237.png)

**Comment by friedpen** [comment]
Small followup on this post. Medallions/Stones were switched to Compasses as of https://github.com/TestRunnerSRL/OoT-Randomizer/commit/e26028c427dd5a1c55f6f64dba87398328a864bc which agrees with the use in Readme. Full dungeon info seems to be connected to maps/compasses option. If set to Dungeons Only, the menu will show full info on game start. If set to Anywhere, it appears to work as intended.

**Comment by TestRunnerSRL** [comment]
I haven't closed this cause there's a pending fix to make it so that info is only revealed if you have found it. Namely that if map and compasses have the info then they reveal it, and otherwise the info is revealed by reading the altar in the temple of time.

**Comment by TestRunnerSRL** [comment]
The fix to the ganon's key is now also fixed
