### ISSUE TITLE
MQ Shadow 2nd Dead Hand spawns out of bounds

### ISSUE THREAD

**Issue by mracsys** [TestRunnerSRL/OoT-Randomizer#1384]
See the below video. On entering the room, if Dead Hand spawns near a wall he can fall through the floor, making him permanently unreachable until reloading the room. From testing it is unclear if this can happen mid-fight or if it only affects initial room load.

https://www.youtube.com/watch?v=ba9_7PAmNjM

**Comment by r0bd0g** [comment]
I wasn't able to get him to spawn oob mid-fight after 30 spawns, hard to say I wasn't just lucky.

**Comment by ETR-BTF** [comment]
I _think_ I remember hearing it can also occur in vanilla well but that it's just incredibly rare.

**Comment by Hamsda** [comment]
Yeah ZFG has mentioned it a few times, can apparently happen in vanilla.

Maybe decomp can shine some light on how rare it actually is nowadays?

**Comment by ETR-BTF** [comment]
Answer from decomp: https://discord.com/channels/274180765816848384/759842532963385354/893073109538721802

**Comment by fenhl** [comment]
The PR did not fully fix this. A new issue was opened for this: #1486
