### ISSUE TITLE
Randomized Settings are not different between worlds

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1387]
Apparently they are supposed to be. Who knew?

**Comment by Zannick** [comment]
They aren't supposed to be. That's a feature request/a feature someone is working on.

**Comment by r0bd0g** [comment]
They are supposed to be. They are different on stable. At some point in dev it was broken.

**Comment by cjohnson57** [comment]
To be clear, only settings with a "Random" option are meant to be.

**Comment by r0bd0g** [comment]
Ah yeah that was probably a source on confusion.
