### ISSUE TITLE
Impossible seed with Randomize Owl Drops enabled

### ISSUE THREAD

**Issue by IkaraV** [TestRunnerSRL/OoT-Randomizer#1398]
See https://ootrandomizer.com/seed/get?id=888783

Needed access to desert collossus grotto for a small key according to the spoiler playthrough. This is under a silver boulder, so gauntlets are required, but I could only access the area as child (owl dropped in wasteland) and the playthrough only had one strength upgrade at this point. Pretty sure the seed is totally impossible without glitches not covered by logic.

**Comment by cjohnson57** [comment]
While the item is located in the Colossus scrub grotto, you have grotto shuffle on so the Colossus scrub grotto is not located under the silver boulder.

**Comment by IkaraV** [comment]
Right, fair enough, too many randomizer settings make the playthrough hard to read! 🤦‍♂️ 

Very quick reply, thanks!
