### ISSUE TITLE
[Suggestion] Write Tunic and Navi Colors to Spoiler Log

### ISSUE THREAD

**Issue by Taylor-Bryan** [TestRunnerSRL/OoT-Randomizer#141]
With the recent addition of being able to specify a custom hex color for tunic colors, I believe a nice QOL improvement would be to write those values to the spoiler log. It might be fun to re-use tunic colors in the future or to checkout tunic colors that you may have missed because you ended up skipping them.

Just had a run that ended this evening without having picked up a Zora Tunic (or the Giant Wallet to buy it), and a bunch of my viewers on Twitch were curious to see what it was. I'll load up the save for them to give them some closure on the next stream, but that prompted this suggestion. Looks like it might be an easy addition, however my Python skills are lacking (though, this may be a good time to improve them...)

If somebody knocks this out real quick then that's great! If not, I might be able to take a swing at it in the next few weeks.

**Comment by TestRunnerSRL** [comment]
Hmm, it's not a bad suggestion, but I also kinda like having the spoiler logs not contain any of the cosmetic options so that you can compare two spoiler files to see if they are identical. Not sure

**Comment by Nicholas-Steel** [comment]
I was thinking of having a separate miscellaneous log file (version_settings_seed_misc.log or whatever) which would contain all of the cosmetic information plus anything else we can think of now & in the future that is irrelevant to a spoiler log file.

It can include things like what songs were assigned to each area and all of the other cosmetic settings for now.

I'd tie the generation of this file to the setting for generating a spoiler log.

**Comment by scattertv** [comment]
I think that's good. I understand the usefulness that can come out of a cosmetics log, but I also really like the idea of spoiler logs being 1:1 correlated with seed+settings. And I don't think anyone wants cosmetics to be seeded, either.

Only thing I'd say is that there's no reason to ever not generate the cosmetics log, so might as well just do it every time. Maybe a separate option on the cosmetics tab (that doesn't change the settings string, of course).

**Comment by TestRunnerSRL** [comment]
I kinda don't like the idea of cluttering up with even more files during generation if I can help it.
