### ISSUE TITLE
Not saving and not continuing gives Ganon BK

### ISSUE THREAD

**Issue by quietfanatic** [TestRunnerSRL/OoT-Randomizer#1414]
1. Set Ganon BK to be awarded on 6 medallions.
2. Create new file.
3. Die to the first enemy you find.  Wow, you suck at this game.
4. Select No for both "Do you want to save" and "Do you want to continue" (Gotta save those nuts).
5. Start the same file again.
6. Get the Ganon BK?

I've reproed this on both dev and devR; here's the dev seed.
https://ootrandomizer.com/seed/get?id=904544
Platform used: RetroArch ParaLLEl N64 on Windows

**Comment by cjohnson57** [comment]
dotzo figured out it's likely due to the title screen save file having all medallions
