### ISSUE TITLE
MQ Fire Like Like doesn't return your shield

### ISSUE THREAD

**Issue by SlyryD** [TestRunnerSRL/OoT-Randomizer#1437]
This Like Like in MQ Fire didn't return my shield. I'm not sure if this is vanilla behavior, but it might be programmed in MQ, because the chest you spawn contains a hylian shield in vanilla MQ. Please make the Like Like return the shield :D https://clips.twitch.tv/PeppyPleasantChamoisMoreCowbell-FZ1q1AWv8DlvTSq4

**Comment by SlyryD** [comment]
Discussion (not sure if useful): https://discord.com/channels/274180765816848384/704998354001723452/908613304103088138

**Comment by SlyryD** [comment]
Relevant discussion: https://discord.com/channels/274180765816848384/512048482677424138/905127647141568522

**Comment by r0bd0g** [comment]
This seems to be vanilla intended. They put a shield in a chest there b/c they knew this guy wasn't going to give it back.

**Comment by mzxrules** [comment]
The reason for this is that scene 4, room 17 is missing objects 0x00CB (Deku Shield) and 0x00DC (Hylian Shield). This can be fixed by updating the object list data in MQU.json, if we want to remove "vanilla" behavior here.

**Comment by SlyryD** [comment]
Thanks! Works as adult and child! So easy!

**Comment by Nicholas-Steel** [comment]
> This Like Like in MQ Fire didn't return my shield. I'm not sure if this is vanilla behavior, but it might be programmed in MQ, because the chest you spawn contains a hylian shield in vanilla MQ. Please make the Like Like return the shield :D https://clips.twitch.tv/PeppyPleasantChamoisMoreCowbell-FZ1q1AWv8DlvTSq4

I knew there was a Like Like jump scare somewhere in the game!
