### ISSUE TITLE
Glitchless Bug - I can't get into Spirit Temple as an Adult without performing a hover-boot glitch..  Deku Tree -> Spirit Temple

### ISSUE THREAD

**Issue by azrethVal** [TestRunnerSRL/OoT-Randomizer#1447]
With a Glitchless run and 0 tricks added, I would expect to do nothing janky.

**Comment by ETR-BTF** [comment]
Could you post your spoiler log in #gameplay-and-tricks in the discord? We'll take a look at it. ^^

**Comment by cjohnson57** [comment]
The entrance to Deku is open as adult in dungeon ER.

**Comment by ETR-BTF** [comment]
> The entrance to Deku is open as adult in dungeon ER.

You'll have to show Mido the Kokiri Sword as child to open Deku as adult if you didn't choose open forest.

**Comment by fenhl** [comment]
There was no follow-up on Discord and it's reasonable to assume they didn't know about the entrance being open as adult, so this can probably be closed.

**Comment by r0bd0g** [comment]
Close this maybe?
