### ISSUE TITLE
glitchless softlock - LLR Back Wall GS Has Boomerang

### ISSUE THREAD

**Issue by cybergrunge-ops** [TestRunnerSRL/OoT-Randomizer#1451]
rekt

**Comment by flagrama** [comment]
Please provide the spoiler log or link to the seed on the website.

**Comment by cybergrunge-ops** [comment]
i am sorry, i dont know what the seed was. i thought i had it loaded on SD but now when i check spoiler it doesnt say LLR Back Wall GS is boomerang, ive been going thru my browser history and looking at every seed ive ever made for the past 2 months and can't find it. but believe me it is real!!!!

**Comment by flagrama** [comment]
Unfortunately without a spoiler log there is no way to verify a bug vs user error. If you are able to find it, it'd be appreciated.

**Comment by Zannick** [comment]
The location is named "LLR GS Back Wall".

Even in glitchless, this can still happen when Reachable Locations is set to Required Only or Goals when the boomerang isn't needed to complete the seed. Closing until we can verify the seed settings.

**Comment by cjohnson57** [comment]
> but believe me it is real!!!!

no

**Comment by cybergrunge-ops** [comment]
its bene 3 hours do u believe me now??????????????????????

**Comment by ETR-BTF** [comment]
> The location is named "LLR GS Back Wall".
> 
> Even in glitchless, this can still happen when Reachable Locations is set to Required Only or Goals when the boomerang isn't needed to complete the seed. Closing until we can verify the seed settings.

Or if you have multiple Boomerangs in your item pool.
