### ISSUE TITLE
(Small optimization request) - Spinning pot in goron city

### ISSUE THREAD

**Issue by csharporblfat** [TestRunnerSRL/OoT-Randomizer#146]
can the spinning pot in goron city give a heart piece the first time?

**Comment by flagrama** [comment]
This would be taken into consideration if it was RNG. However it is not, it is based on where the pot is facing when the bomb explodes. It's unlikely any of the devs are going to attempt to change this.

**Comment by TestRunnerSRL** [comment]
As someone who is pretty terrible at getting the timing right, I have to agree that making this free is probably not something I would want to change since it is skill based.
