### ISSUE TITLE
Bean-related plando softlock

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1465]
Here's a plando that generates but shouldn't:

```json
{
    "settings": {
        "triforce_hunt": true,
        "triforce_goal_per_world": 1,
        "triforce_count_per_world": 1,
        "shuffle_beans": true,
        "reachable_locations": "beatable",
        "starting_items": {
            "Magic Bean": 1
        }
    },
    "item_pool": {
        "Magic Bean Pack": 0
    },
    "locations": {
        "Colossus Freestanding PoH": "Triforce Piece"
    }
}
```

In this plando, only one magic bean is ever available, so if you plant it anywhere other than colossus, you're softlocked. This generates successfully because the logic helper `can_plant_bean` only checks if you have 1 magic bean, not 10. This works fine without plandos since logical access to the single magic bean from the bean salesman implies access to all 10 thanks to the patch reducing the last one's price to 99. A fix could be to require 10 magic beans instead of only one to cover the starting items case, and adjust unshuffled bean salesman to sell a “Buy Magic Bean” item that logically acts as 10 beans but appears as a single bean in-game.

**Comment by cjohnson57** [comment]
Shouldn't shuffle beans require a magic bean pack in the item pool? I thought it worked that way for all items like that (kokiri sword etc.)
