### ISSUE TITLE
GTG Maze Softlock (v6.2.1 Dev Roman Branch)

### ISSUE THREAD

**Issue by anonylmous** [TestRunnerSRL/OoT-Randomizer#1466]
Unintentionally ran into a softlock in my recent seed (https://ootrandomizer.com/seed/get?id=970243)

First ocarina was locked inside one of the GTG Maze chests on the right side, but I mistakenly used all available GTG keys on the left side of the maze, and because I didn't have Ocarina to reach the right side chests, it left me unable to reach the Ocarina, which left me softlocked with no further available checks for progression. I had already saved sometime after clearing the available left-side checks, so it was too late to savescum and reach the chest containing Ocarina.

**Comment by DuskTheUmbreon** [comment]
Shuffle dungeon entrances is enabled. You're expected to go there as child and climb up the song of time blocks.

**Comment by anonylmous** [comment]
> Shuffle dungeon entrances is enabled. You're expected to go there as child and climb up the song of time blocks.

Ah I forgot that was possible, thank you.
