### ISSUE TITLE
Beating Forest Temple before playing Ocarina for Mido as Adult Link makes dismissing Mido unclear

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#1469]
### **Problem:**
If you beat Forest Temple before playing Saria's Song to Mido, Mido will change his dialogue to:

> If you see him somewhere, please let me know.
> And also...
> I'm sorry for being mean to him.

Which doesn't indicate how to make him move out of your way. 

### **Solution:**
Reprogram Mido to always include his initial dialogue:

> Oh...I see... Saria won't ever come back... But...I...I made a promise to Saria... If Link came back, I would be sure to tell him that Saria had been waiting for him... Because Saria...really... liked- hey you.

This will clue the player in that Saria is somehow related to dismissing him.

Discord discussion: https://discord.com/channels/274180765816848384/438698093354156032/923166497868763207

**Comment by r0bd0g** [comment]
There are just so many texts that don't make sense in the context of rando that I'm not convinced we should change anything along these lines without being prepared to update everything...

**Comment by Nicholas-Steel** [comment]
In this case you'd be restoring visibility of vanilla dialogue that hints at what to do to progress past a barrier, not editing a dialogue to have a more generic message or some such that better suits the environment of a randomizer.

**Comment by r0bd0g** [comment]
We have sometimes updated flags in the past, but there are still a lot of flags that haven't been altered. I guess you're suggesting instead to change the order that the flags are checked?

**Comment by Nicholas-Steel** [comment]
Have him check for the song being played before progressing his dialogue, instead of if the temple has been beaten.

I guess that is what you're saying and would render the currently spoken piece of dialogue inaccessible in-game while making the desirable dialogue accessible.
