### ISSUE TITLE
Golden Scale Obtained before Silver Scale.

### ISSUE THREAD

**Issue by teallen1996** [TestRunnerSRL/OoT-Randomizer#148]
Currently playing on the MQ branch, and I have just received the Golden Scale before the Silver Scale. Not yet been able to get to the other scale location, but once collected, will let you know what happens.

Collected second scale location, and still have golden scale, although one thing I did notice when scanning over it. The spoiler log says the first location was "Spirit Temple MQ Beamos Room Chest", however the place I found my scale was 1 of the scrubs in Ganon's Castle. Is this just a case of stuff not yet being updated due to it not being started for long?

OoT Randomizer Version 2.19.4 f.LUM  -  Seed: QTMZF9EYE3

Settings (R82QA9MX3LASH4LB):

**Comment by TestRunnerSRL** [comment]
Should be fixed in f1547bad620230d7af976fd4c9a44472b5dd9f4e
