### ISSUE TITLE
Progressive Hookshots locked behind Skulltulas needing Hook/Longshot

### ISSUE THREAD

**Issue by ErikElgerot** [TestRunnerSRL/OoT-Randomizer#149]
Got a seed today where I ended up getting stuck, and looking at the spoilers I noticed that both hookshots appear unobtainable in this seed - One is contained in the GS Spirit Temple Lobby (the GS in the statue room which you reach via longshot/scarecrow song), and the other is in the GS on top of Impa's House, which also needs a Hookshot to reach.

[OoT_V62MA9AXEFDAAEEA_GMK46JEQ6Q-0_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2394233/OoT_V62MA9AXEFDAAEEA_GMK46JEQ6Q-0_Spoiler.txt)

**Comment by TestRunnerSRL** [comment]
'GS Spirit Temple Lobby' location should be reachable with Hover Boots (according to the logic)

**Comment by ErikElgerot** [comment]
Logic was correct, my info was wrong. Thanks for the clarification.
