### ISSUE TITLE
Recieved Goron Mask as part of Randomizer

### ISSUE THREAD

**Issue by teallen1996** [TestRunnerSRL/OoT-Randomizer#151]
OoT Randomizer Version 2.19.4 f.LUM  -  Seed: D5BDRVRIRK

Settings (R82QA9MXKMASH4LB):

Went to the Great Fairy at the top of death mountain, and played Zelda's Lullaby as normal, however instead of the usual "Da Da Da Daaaa" stuff, the game gave me the item (1 deku stick) as if I had just picked it up off the ground. This led to a weird glitch where the game did that thing endlessly while I was in the fountain. Once I left the fountain, I was awarded an item in the usual way, except it was a goron mask. It appeared in my inventory and acted as usual from there. At the time I went there, I hadn't even got the Weird egg yet.

https://www.youtube.com/watch?v=iAgYZggnKkI&feature=youtu.be

**Comment by TestRunnerSRL** [comment]
Should be fixed now in c3cb5cc13e58aee9c9f9bde471083a2cf8887310
