### ISSUE TITLE
Cannot Plando Junk Items to Song on Impa if Skip Child Zelda

### ISSUE THREAD

**Issue by flagrama** [TestRunnerSRL/OoT-Randomizer#1510]
Junk items, dungeon items, and possibly more cannot be placed on "Song on Impa" location if "Skip Child Zelda" is on. 
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/2b5db1709ba9e8f284a80f4f717af8d2634a4012/Rules.py#L53

This seems to be the root cause. This only allows the keys from the following item dictionaries and lists to be set to this location: 
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/2b5db1709ba9e8f284a80f4f717af8d2634a4012/SaveContext.py#L770-L928

This is distinctly missing all of the junk items, which are defined in the following lists:
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/53e31ea89d7c9abc9ffc5e556e85b9960efec458/ItemPool.py#L646-L657
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/53e31ea89d7c9abc9ffc5e556e85b9960efec458/ItemPool.py#L663-L680

**Comment by cjohnson57** [comment]
It seems limit_to_itemset is only used in this one specific place. I'm not entirely clear why it is used. Why is this location treated differently from any other location when it comes to what items are allowed to be placed there? Shouldn't it just be songs if songs are shuffled to song locations or dungeons, and anything else if not?

**Comment by cjohnson57** [comment]
Was the idea purposely to make it so that free child zelda would always give you a major item?

**Comment by ETR-BTF** [comment]
There are 4 other "Skip Child Zelda" related issues. Could some of them be related to this issue? In particular I think #1227 and #1278 might be.

**Comment by fenhl** [comment]
There's an easy fix for this after #1352 gets merged.

**Comment by fenhl** [comment]
The PR standardizes how starting items are given, using the same code for plando starting items and free Song From Impa. That code can already handle most (all?) junk items.

**Comment by Cuphat** [comment]
> Was the idea purposely to make it so that free child zelda would always give you a major item?

No, it was to make sure SaveContext.py could handle making it into a pseudo-starting item.
