### ISSUE TITLE
[Suggestion] Shop shuffle prices

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#156]
I haven't done much shop shuffle, but during a recent seed, we were bottlenecked behind the first wallet upgrade.
This led to a second wallet upgrade in a shop and 3-4 songs + magic spread across a few different shops, each ranging somewhere between 150-250 rupees.
The result of this was multiple minutes spent farming rupees, just to get these next items.
I realize one could get an early wallet and sort of naturally fill it up and spend money on the way, but that isn't even really possible for the >200 rupee items if one has 0 or 1 wallet upgrade.
I like having the wallets be of more importance in terms of progression for shop shuffle runs, but maybe a reduction in overall prices would help make it feel less grindy if situations like these arise, without taking away the wallets significance?

**Comment by TestRunnerSRL** [comment]
I mean, I think part of the problem (depending on settings) is that most of the shop items can be available immediately. I think money grinding in such cases will just always happen no matter how cheap I make it if you have 4 items per shop. This is part of the reason I'm not a huge fan of putting more than 2 items per shop. I don't think it's realistically possible to drop the prices in shops without making wallets less useful. If two items require 2 wallet upgrades, it'll almost always involve grinding unless you pick up the items later, no matter how cheap it is. I should also note that it sounds like you got especially unlucky. The distribution is roughly:
```
40%: 0-99 rupees
40%: 100-200 rupees
20%: 201-300 rupees
```

**Comment by Hamsda** [comment]
Okay yeah, then we were just god damn unlucky. We had like 1 or 2 items for <100, the (second) wallet for 130 and I think almost all songs and magic for >200.
I'll close the issue then.
