### ISSUE TITLE
Reserve more space for text

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1572]
We are close to running out of room for messages.

Unlike the table of text box metadata, which in #1126 was extended to cover both the English and Japanese tables from the vanilla game, the space in memory containing the text itself is essentially the same size as in the vanilla game, with a small extension made in #744. That same PR reverted a broken attempt at using the Japanese text bank once the English one is full. I have made another attempt at <https://github.com/fenhl/OoT-Randomizer/tree/more-text-space>, but it causes the game to crash when the last text box in the English bank or a text box in the Japanese bank is displayed. I'm not sure why this crash happens, so I'm posting this issue in case anyone has any ideas for how to make something like this work. Pinging @mzxrules who wanted to be notified when we run out of room again.

This is blocking several features, including the text box aspect of #1563 and parts of silver rupee shuffle, namely silver rupee pouches and having different text boxes depending on the number collected.

**Comment by cjohnson57** [comment]
> having different text boxes depending on the number collected.

Is OoT's text system not sophisticated enough to have variables in text box's that aren't the player's name?

**Comment by fenhl** [comment]
I know the vanilla game has a couple other variables for the scoreboard in Link's house (which is how the gold skulltula text box works), but I don't know how to patch in new ones. Even then, having slightly different text depending on whether the silver rupee collected was the last one would already exceed the limit on some settings.

**Comment by fenhl** [comment]
@fig02 helped me with debugging this and it turns out the code wasn't actually changing the address where text is written when switching over to the Japanese bank. However, the crash still occurs after I implemented this, with both of the possible starting addresses @fig02 identified, `0x8eb000` and `0x923000`.

To reproduce the crash, set shops to 4 on <https://github.com/fenhl/OoT-Randomizer/tree/dev-fenhl-more-text-space>. The randomizer will print the first text box stored in the Japanese bank to stdout. The exact text box depends on the seed but it should be one for collecting a specific amount of a specific type of key.

**Comment by cjohnson57** [comment]
Should be fixed with the merging of 1837
