### ISSUE TITLE
Buy Blue Potion causes a Text ID Error and Softlocks the Game

### ISSUE THREAD

**Issue by Maplesstar** [TestRunnerSRL/OoT-Randomizer#1577]
Can be replicated easily using a plando:
```
{
  "locations":                 {
	"KF Shop Item 1":      {"item": "Buy Blue Potion", "price": 100}
  }
}
```

![image](https://user-images.githubusercontent.com/69886167/170405529-3aa78865-e1ae-439a-95f1-b87c37228021.png)

Also putting the discord link for what Shadow found about the text IDs: https://discord.com/channels/274180765816848384/802659695323250729/979214749902450749
The choice is currently referencing a non-choice text box. 500C is the text ID for buying blue potion in Granny's Shop. There is no normal shop description text ID.

**Comment by r0bd0g** [comment]
The randomizer should probably balk at you trying to put a blue potion in a shop, since there never was such a thing as buying blue potions from shops? Why do we have a buy blue potion item anyway, honestly I forgot for what reason it's there.
