### ISSUE TITLE
Ice traps deal 16 hearts of damage in OHKO

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1584]
It's possible to receive 16 hearts of damage from an ice trap, which seems to be contrary to the idea of one-hit KO. To reproduce, open an ice trap chest and start alternating A and B presses after the first frame Link is in the frozen pose.

**Comment by aofengen** [comment]
It's also possible to take no damage from ice traps from chests specifically if you mash fast enough. Has been a thing in some races.

**Comment by r0bd0g** [comment]
Yeah this has happened to me in a race before.

**Comment by fenhl** [comment]
> no damage from ice traps from chests specifically

In #1583 @r0bd0g is arguing that this is intended. That's the reason I was looking into this.

**Comment by ETR-BTF** [comment]
Isn't OHKO just a 256 damage multiplier? Iirc the smallest unit of health in the game is 1/16 so would 256*1/16 = 16 hearts explain the issue? Can OHKO be bumped up to a higher damage multiplier?

**Comment by mracsys** [comment]
For bonko I set health to 0 directly instead of dealing with multipliers. You can still survive if you get a healing item same-frame like with ohko flying pots, but I will eventually patch that for bonko. Maybe this approach could be applied to ohko as well?

**Comment by fenhl** [comment]
Looks like that's what's going on, yes. Changing this 8 to a 9 should fix it: <https://github.com/TestRunnerSRL/OoT-Randomizer/blob/e337d7f603b91a6bacb618fb32cc7fd70ed9ffca/ASM/src/damage.asm#L18>

**Comment by ETR-BTF** [comment]
> Looks like that's what's going on, yes. Changing this 8 to a 9 should fix it:
> 
> https://github.com/TestRunnerSRL/OoT-Randomizer/blob/e337d7f603b91a6bacb618fb32cc7fd70ed9ffca/ASM/src/damage.asm#L18

What if Double Defense is at play? Would it neutralize the doubling of the damage multiplier? I can't read asm but I assume you're doing 2^8 --> 2^9

**Comment by fenhl** [comment]
I'm not certain but it looks like double defence would divide the damage by 2 after the 2^9 is applied, so it should be 2^10 to account for that.
