### ISSUE TITLE
Incompatible starting item settings false positive

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1624]
The following plando no longer generates:

```json
{
    "settings": {
        "starting_songs": [
            "prelude"
        ]
    }
}
```

It gives this error message:

> Incompatible starting item settings. Either move starting_songs into starting_items or make starting_items a list

I suspect this has something to do with #1614.

**Comment by LostThePirate** [comment]
Shouldn't it be Prelude of Light?

**Comment by fenhl** [comment]
No, the old-style syntax uses the `settingname` values from StartingItems.py.
