### ISSUE TITLE
Bug causing softlock on the entire save file when getting an Ice Trap

### ISSUE THREAD

**Issue by GamingST** [TestRunnerSRL/OoT-Randomizer#1642]
I started a randomizer seed specifically seed ID: 1143385 on the Devrreal_6.2.138 excited to start a potsanity run. Everything started well. I spawned in as young Link leaving Talon's House in Lon Lon Ranch. I gathered all the stuff I could, checked out the grotto, went through the crawl space in the storage area then decided to make my way out of Lon Lon heading to Hyrule Castle. I stopped in the Gaurd's post to break all the pots eventually figuring out that if you stand directly facing a wall when you throw the pot you instantly collect the item inside. One of the pots ended up being an ice trap. I broke free then was hit by another. No text box, no other items, not even a second to move. This repeated until I died. I said "Okay, Weird" and saved and continued. As soon as I spawn in, I'm instantly frozen again and the cycle continues. I soft rebooted; the same thing. I restarted the emulator; the same thing. I erased my save file in game and started a new one; still got frozen. I had to completely erase the save data from my computer. I started a new file this time heading to Kokiri Forest after finishing in Lon Lon then after that heading back to the Guard's Post this time being careful not to use that wall trick again. A Triforce shard lands on the ground I pick it up aaaannnddd Ice Trap softlock again. I then decided to try to record it happening again (Immediately B-lining for the guard's post no previous pick-ups) and after two tries I failed to recreate it. I'm not sure what the problem is tied to.

**Comment by fenhl** [comment]
Are you by any chance playing on ModLoader64?

**Comment by Maplesstar** [comment]
Are you playing on Modloader64? That platform only supports the stable version of the randomizer. Issues like the infinite ice trap won't be addressed until such a time as potsanity becomes a stable feature.

**Comment by GamingST** [comment]
Yes
