### ISSUE TITLE
Settings String broken in GUI.

### ISSUE THREAD

**Issue by Cuphat** [TestRunnerSRL/OoT-Randomizer#1648]
I'm not sure what shenanigans have been added to the settings string with starting items, but whatever it is does not work - at least in the GUI.

All you have to do to reproduce is try to import literally any settings string.

![image](https://user-images.githubusercontent.com/15843710/180087404-d7d3fdb3-f30a-47d4-b50d-a42f1e045da5.png)

**Comment by cjohnson57** [comment]
@fenhl

(Maybe can use your site dev branch to test gui since you can update it at will now?)

**Comment by cjohnson57** [comment]
Cuphat also raised the point of potentially using NVM or a VM to be able to test the GUI.

**Comment by fenhl** [comment]
> Maybe can use your site dev branch to test gui since you can update it at will now?)

No, I can only update the website once per Dev version.

But I installed Node 14 via NVM and tested this, it does show the same error message. If I'm reading the GUI code correctly, the GUI is calling `python OoTRandomizer.py --convert_settings --settings_string BSWAMFQNALH2EAAGAACASMGAAAAA2EAUWCHGATL62AEAAAAAAEBAAA4AASQCFAACA` (using the default settings as an example). Running that command in a shell works as expected. It seems that there is [additional GUI code](https://github.com/TestRunnerSRL/OoT-Randomizer/blob/2fc0799b29cb3c53c1a993ba1ad6357ec07edc68/GUI/src/app/pages/generator/generator.component.ts#L464-L472) that uses the same error handler. It could be that this code doesn't work with dict-style starting items yet.
