### ISSUE TITLE
[Suggestion/Questions] Wallet and Arrows

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#166]
I was wondering if there could be a option to make base wallet 200 and each upgrade a bit heftier? As it stands right now. Wallets get in late game and id be nicer to carry more earlier. My other question some breakthroughs I got light arrow and or fire/ice. The game really does not utilize them well. I was wondering if it was possible to alter like example Regular poe gets hit by light arrow it should be a one shot. Don't ya think?

**Comment by TestRunnerSRL** [comment]
In shopsanity, there's 3 wallet upgrades, so they shouldn't be too late on average. 

I'm not sure I fully understand your second suggestion, but it's about changing the damage tables? I'm not really a fan of changing the behavior of the items from how they work in vanilla unnecessarily.

**Comment by TopHatMan** [comment]
Yeah what I was talking about would be optional and not forced.
