### ISSUE TITLE
Something is screwy with MQ Ganon scrubs

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1667]
r0bd0g — Today at 7:00 AM
Something is fucky with MQ Ganon scrubs. I was playing on [fenhl's] mixed pools branch [no idea if it might be specific to that branch]. I could have sworn the rightmost scrub didn't spawn, I don't actually know that it didn't, but it made me paranoid, so next time I was in Ganon's, I checked back. Two scrubs had respawned, neither of which was the rightmost scrub. They didn't respawn right away, I have to leave and go do other things first. (I'm sure I previously bought them but there's like a 1 in 10000000 chance I didn't notice I said no two times. I'm sure I had enough money at the least; I was loaded.) 

ETR_BTF — Today at 7:04 AM
was there ER involved?
specifically ganons castle ER

r0bd0g — Today at 7:04 AM
The ER was standard mixed pools level.
No Ganon ER, no boss ER, etc. 

PiMan — Today at 7:06 AM
I recall someone reporting that scrub problem maybe a month ago, too.

r0bd0g — Today at 7:06 AM
Actually if I didn't have enough money they would have respawned right away I think
not forcing me to leave to reset the temp flags
It was like, rightmost scrub is maybe overlapping with some other permanent flag, and then two of the other scrubs are on temp flags for some reason.

seed https://ootrandomizer.com/seed/get?id=1165222

**Comment by ETR-BTF** [comment]
Fixed by #1636
