### ISSUE TITLE
Bonk Damage Crash

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1670]
Tjongejonge — Today at 4:38 PM
So we are playing some bonk damage (bonk deals 1 damage)  but there are some weird things happening.

1) on vc if you bonk with half a heart it will vc crash (we replicated this multiple times)
2)on emu if you bonk with half a heart you get glitched health

If you guys want i have video's (made on phone so not best quality) and screenshot of these situations

This was rolled on realrobs branch (I do have the seed if that's important) 
Also on emu, if you get the glitched health and pick up health you die at that moment

**Comment by ETR-BTF** [comment]
For the record, what he described sounded exactly like what Poldon described in Discord the day before (including the part about the leftmost heart being missing). It's likely both issues are identical and due to negative health not being handled well or something.

**Comment by flagrama** [comment]
On hardware you don't even die.

**Comment by r0bd0g** [comment]
Somebody else chimed in saying also they had reported something like this before poldon iirc
