### ISSUE TITLE
One major item per dungeon allows extra items on boss hearts

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1671]
Going theory is that this setting was missing when supporting boss room shuffle.

**Comment by Cuphat** [comment]
I assume you mean that the theory is that the shuffled boss room is still considered the original dungeon and not the dungeon it is connected to?

**Comment by Cuphat** [comment]
Oh, okay, actually read the Discord. Apparently it doesn't need boss room shuffle to be on, so it just doesn't consider them part of the dungeon anymore.

One Major Item Per Dungeon has its own fill function so I could definitely see it just not getting updated for the changes to the logic files for boss room shuffle.

**Comment by fenhl** [comment]
The culprit is most likely #1590. I thought I had changed everything relevant to check for the hint area and not the `dungeon` field itself (which I removed from boss rooms), but I guess I must have missed this setting.
