### ISSUE TITLE
Deku Tree MQ Scrub Logic Mishap (thanks, collection delay)

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#169]
Nevermind, it doesn't work in real MQ either, lol.
(If you try to buy this guy's item from the water you just get collection delay until you go up there and say hi.)

**Comment by r0bd0g** [comment]
OK actually it doesn't work on real mq either, lol.
We gotta fix the logic I guess and move this guy to the basement path region and remove the rule for it.

**Comment by r0bd0g** [comment]
Alright, AA's has this fix.

**Comment by TestRunnerSRL** [comment]
Merged in AA's current dev that should have this fix now
