### ISSUE TITLE
Heart Piece bought from shop doesn't refill health

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#170]
It does add to the heart piece counter. If you get a new container, you it add the 1 new container in health, but still does not heal.

OoT Randomizer Version 2.19.20 f.LUM  -  Seed: 94

Settings (MJ23A9MMTLAS9PSA):

Goron shop. I wonder if potentially related to how the chu bowling heart piece always heals you, regardless of what it is.

**Comment by TestRunnerSRL** [comment]
This isn't really a bug per se. The hearts don't refill your health, but instead the actors the give the hearts heal. Same thing applies to deku scrubs. The fix would be to find every actor that does this and remove it, and then add the heal into the heart, but yeah for now it's just a weird quirk.

**Comment by r0bd0g** [comment]
I wonder though if this is part of why people kept reporting that bought heart pieces weren't working.

**Comment by TestRunnerSRL** [comment]
You mean as in they were healed and assumed they got a heart piece? I guess...

**Comment by r0bd0g** [comment]
I mean that they weren't healed and assumed they didn't get the heart piece.
