### ISSUE TITLE
Text too long, floats off the box

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#171]
OoT Randomizer Version 2.19.20 f.LUM  -  Seed: 94

Settings (MJ23A9MMTLAS9PSA):

Zora Shop

"Compass (Bottom of the Well) 90   Rupees" is too long for the text box.
This seems to occur for a lot of items that have long names when they appear in shops.
I couldn't even see the full price of a gerudo training grounds key.

**Comment by TestRunnerSRL** [comment]
Yeah I was aware of this... I kinda put off the fix since I was always able to read the text. Not sure the best way to handle this besides making a line break for the dungeon name?

**Comment by TestRunnerSRL** [comment]
I fixed it by outputting as one of 
```
Item Name   Rupees(cost)
Special deal! ONE LEFT!
Get it while it lasts!
```
```
Item Name   Rupees(cost)
(Dungeon Name)
Special deal! ONE LEFT!
Get it while it lasts!
```
```
Item Name   Rupees(cost)
Player X
Special deal! ONE LEFT!
```
```
Item Name   Rupees(cost)
(Dungeon Name)
Player X
Special deal! ONE LEFT!
```
