### ISSUE TITLE
Illegal licensing?

### ISSUE THREAD

**Issue by cariuyip** [TestRunnerSRL/OoT-Randomizer#1715]
The license file says MIT, but a file is seemingly licensed under GPL.

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/LICENSE
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/bin/Compress/src/crc.c#L9

MIT is widely considered to be incompatible with GPL v2.

**Comment by xrishox** [comment]
according to who?

https://en.wikipedia.org/wiki/MIT_License

one of the first things it says in there is that it is gpl compatible.

maybe you are confusing it with the 4 clause bsd license?

edit: after re-reading it i think that i understand what you are saying: they are taking gpl code and relicensing it as mit? if that's the case they definitely cannot do that.

**Comment by Zannick** [comment]
We should mark the subdirectory with the GPL license to distinguish them. Potentially we may have to mark the LICENSE file to indicate which directories it applies to.

**Comment by TreZc0** [comment]
Handled by including GPLv2 files for the compressor/decompressor and adding a note for that to the original license file. This is widely considered to be acceptable practice for MIT/GPL mixes.
