### ISSUE TITLE
Unable to learn song from Guru Guru after passing through Dampe's Grave

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1727]
Have to reload the map to learn the song. If this consistently happens it could dead end a seed if the windmill is not reenterable.

https://www.twitch.tv/videos/1605737971?t=186m00s

We've had a couple of sparse reports of this one over the years. Nobody seems to know exactly what is the cause.

**Comment by fenhl** [comment]
According to a conversation in #dev-bug-reports, this happens if you touch the hookshot chest but don't open it. Potential fix at <https://github.com/TestRunnerSRL/OoT-Randomizer/compare/Dev...fig02:OoT-Randomizer:windmill?expand=1>.

**Comment by fig02** [comment]
`Have to reload the map to learn the song`
ideally the fix above works and is merged asap, but also just want to note that getting the freestanding item, pulling out a bomb, or even standing next to bugs/fish will reset your get item id and allow you to talk to the windmill guy. at least as a short term fix if people find themselves in this situation before the patch is merged
