### ISSUE TITLE
Unbeatable Forest Temple

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#176]
Hello,

I think I found a bug with a Forest Temple seed....

```
Forest Temple First Chest: Boss Key (Forest Temple)
Forest Temple Chest Behind Lobby: Arrows (30)
Forest Temple Well Chest: Hover Boots
Forest Temple Map Chest: Small Key (Forest Temple)
Forest Temple Outside Hookshot Chest: Rupees (5)
Forest Temple Falling Room Chest: Compass (Forest Temple)
Forest Temple Block Push Chest: Piece of Heart
Forest Temple Boss Key Chest: Small Key (Forest Temple)
Forest Temple Floormaster Chest: Small Key (Forest Temple)
Forest Temple Bow Chest: Small Key (Forest Temple)
Forest Temple Red Poe Chest: Small Key (Forest Temple)
Forest Temple Blue Poe Chest: Deku Nut Capacity
Forest Temple Near Boss Chest: Rupees (50)
Phantom Ganon Heart: Map (Forest Temple)
```

A key is needed to get into the lobby side door, and a key is needed to get into the twisty room at the top of the block pushing puzzle rooms. The problem is, as you can see here, only one key is provided prior to the twisty room key.

Am I missing something here, or is this a bug?

**Comment by flagrama** [comment]
Floormaster chest is a small key. You can use hoverboots to reach it from the room with the block pushing puzzle.

**Comment by joeauty** [comment]
Wow, I didn't know that! Thanks for your quick response.. Just when I thought I knew a fair amount about this game :)
