### ISSUE TITLE
Remove the ability for hint dists to affect generation?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1763]
The tooltip says "Very Strong with Magic", with absolutely no clue what "with magic" even means. Apparently it adds a goal hint for magic, which is not obvious from the description, but also is apparently removes all other goals from the seed in an completely undocumented way.

**Comment by ETR-BTF** [comment]
The entire Hints wiki page needs an overhaul but I don't understand the hints system well enough to do so myself.

**Comment by fenhl** [comment]
This was fixed in #1764.

**Comment by r0bd0g** [comment]
Might be worth opening a new issue or repurposing this one, to talk about removing the ability for hint dists to affect generation like this.

**Comment by fenhl** [comment]
After discussing this internally, the dev team has decided to keep allowing hint distros to affect generation. The reasons given varied, but my own opinion is that while it might be unintuitive, it's also documented and potentially useful. Disallowing it would essentially just restrict the options given to plando authors, and would mean that we would have to figure out how exactly to restrict it.
