### ISSUE TITLE
Unable to distinguish between own and outgoing junk items from pots etc.

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1766]
I originally posted this as https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1558#issuecomment-1266523712 and am splitting it into a new issue since the PR has been merged.

If a junk item is picked up from one of the locations added in #1558, Link doesn't stop and hold up the item, and there's also no text box. It's therefore impossible to tell in multiworld whether the item you picked up was your own or someone else's. For a junk item, it's not that important to know who exactly received the item, but it would at least be nice to know whether or not it was your own. Maybe it would be possible to use a different sound effect and/or animation to distinguish between the two? For example, instead of drawing an outgoing item above Link's head, it could be animated to fly up quickly (to visualize that it's being “uploaded” to the network).

**Comment by ETR-BTF** [comment]
You could draw text on the screen whenever you send or receive an item. I think some other MWs also do that, like ML and alttpr?

**Comment by fenhl** [comment]
From @rrealmuto:

![upload](https://user-images.githubusercontent.com/641386/207590565-c7480086-7273-46a9-a44b-bcd5b2021d81.gif)

[With sound](https://cdn.discordapp.com/attachments/964923005186756659/1048784127085772892/THE_LEGEND_OF_ZELDA_-_Project64_3.0.1.5664-2df3434_2022-12-03_21-12-53.mp4)

**Comment by fenhl** [comment]
Implemented in #1964.
