### ISSUE TITLE
Dungeon Item Display incorrect textures on pj64

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#177]
This is what it looks like.

https://cdn.discordapp.com/attachments/274186223147417600/495108299591516160/snap0008.jpg

Textures from around the currently loaded area instead of any text or symbols.
I don't know what version the guy who reported this was on, but I tested it on pj64 1.6.

(I'm assuming that if it weren't PJ64-specific it would have been reported by now, but I haven't actually tested that it works correctly on other platforms.)

**Comment by TestRunnerSRL** [comment]
Seems like this can resolved by using different PJ64 settings. Wulfy is looking into possibility in making this work, but it's probably not likely to be fixed is my guess.

**Comment by r0bd0g** [comment]
Did Wulfy's latest pull affect this?

**Comment by r0bd0g** [comment]
Seems to be fixed.
