### ISSUE TITLE
[Bug] The search feature of the glitchless tricks list in the GUI skips tricks that apply to MQ when searching for "MQ"

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1770]
It seems that the search feature simply scans the name of the tricks for matches, but a handful of tricks apply to MQ without having "MQ" in their name (such as "Hammer Rusted Switches Through Walls"). Using the predetermined categories from the dropdown menu, the GUI instead uses tags declared internally to find relevant tricks. #1765 adds an "MQ" tag for all tricks that can apply to MQ dungeons, so until the bug with the search feature is fixed, users can still accurately find all tricks relevant for MQ after #1765 is merged if they use this method instead.

**Comment by cjohnson57** [comment]
Fixed by #1765

**Comment by ETR-BTF** [comment]
I think there's been a slight misunderstanding. #1765 doesn't fix this issue, but just creates a workaround. When inputting "MQ" in the search field you will still only find tricks with "MQ" in the name, but some tricks that are relevant in MQ don't have MQ in the name because those tricks are also relevant for vanilla. In other words, searching for "MQ" only shows tricks that are relevant ONLY in MQ, and not tricks that are relevant in both vanilla and MQ. But if you select "MQ" from the dropdown menu, you DO see all tricks relevant in MQ (including those that are also relevant for vanilla). This is because the dropdown menu uses the tags but the search field only scans the trick names. I can see the argument for "both systems are working as intended", but the consequence is that the search engine gives misleading results. See the images below for an example of the discrepancies between both methods of finding MQ tricks.

![image](https://user-images.githubusercontent.com/63906538/202421164-bca3ba3f-122d-4576-8dc4-ced3f6e6952b.png)

![image](https://user-images.githubusercontent.com/63906538/202421209-02ed561e-40f2-47f4-8106-f1896b950312.png)
