### ISSUE TITLE
Blue Fire Arrows still named Ice Arrows in hints

### ISSUE THREAD

**Issue by matthewkirby** [TestRunnerSRL/OoT-Randomizer#1773]
If your seed has Blue Fire Arrows enabled and they are hinted, they appear as "Ice Arrows" on a gossip stone. This could be a major issue since a player might ignore a hint about Ice Arrows when the Blue Fire Arrows are actually required.

**Comment by fenhl** [comment]
Fixing this would require splitting Ice Arrows and Blue Fire Arrows into separate items on the logic side, like what was done with Magic Bean and Buy Magic Bean in #1615. The item pool code would have to be adjusted to make that substitution when the setting is on.

**Comment by cjohnson57** [comment]
Yeah this isn't really a bug. The blue fire arrows are still the ice arrows. It was changed in the menu but that didn't necessarily carry the expectation that it would be changed everywhere. Outside of an RSL context I don't see the situation you presented taking place, and even then is it better for the player to have to chance the ice arrows not being sure if they're BFAs or not?

**Comment by cjohnson57** [comment]
Not to say that it shouldn't be changed necessarily (thus why I'm leaving this issue open), just that it's less a bug and more just something we didn't do that is pretty low impact

**Comment by matthewkirby** [comment]
It just felt like an untruthful hint was all. There aren't really any other instances of hints calling an item by a different name. But I guess this is one of the only places an item is actually changed. While I noticed this in RSL, I can also see a potential problem arising for a player who does not understand that the setting converts Ice Arrows to Blue Fire Arrows. 

It just seemed to me like it should be consistent. We went through the trouble of renaming the item in the menu, get item box, etc so I was expecting that it would be renamed everywhere. If you don't think its necessarily an issue, I will just file it in the quirks box in my brain and not super worry about it. I mainly wanted to make sure people knew it behaved this way.

**Comment by ETR-BTF** [comment]
I agree that hints should properly call out Blue Fire Arrows.

**Comment by LostThePirate** [comment]
Leaving this as-is will certainly lead to some percentage of players finding "unbeatable" seeds due to mislabeled Blue Fire Arrows in Hints and in Shops. It's just a matter of time. People will always disregard hints for Ice Arrows or for sale Ice Arrows, and some small percentage of those will actually be hard required BF Arrows. I'm 100% in favor of updating all in-game text to accurately describe what is in game.

**Comment by cjohnson57** [comment]
> People will always disregard hints for Ice Arrows

I really don't think is true when most people would know they have BFA's turned on, but I still agree with changing it

**Comment by LostThePirate** [comment]
I've had BF Arrows turned on and had to double back for "Ice Arrows" in a Shop because I forgot I had BFA on and Ice Arrows are junk, lol, and I'm surely not alone.

**Comment by fenhl** [comment]
This was fixed in #1797.
