### ISSUE TITLE
Glitchless seed with logic problems

### ISSUE THREAD

**Issue by JJJ101010** [TestRunnerSRL/OoT-Randomizer#1779]
https://ootrandomizer.com/seed/get?id=1256348
seed: NREQ3QI49B

Seed is set to glitchless, and all tricks are turned off, but Zora's sapphire was set to Phantom Ganon and Zelda's Lullaby was set to Sheik in the Death Mountain Crater. I am struggling to imagine any path where those would not be considered glitches or major tricks to become Adult Link without Zora's Sapphire, or get down to the crater as Child Link and trigger Sheik's cut scene.

**Comment by cjohnson57** [comment]
You don't need either of those things to go adult, you just need an ocarina and the song of time, both of which are available as child. Please confirm things like this in the discord server first

**Comment by JJJ101010** [comment]
Sorry, I wasn't sure where to go in the discord server. The bugs channel said to only post confirmed bugs there and to come here for reports.

**Comment by cjohnson57** [comment]
No worries, but yeah typically you go to #gameplay-and-tricks or #setup-support first
