### ISSUE TITLE
Adult Shooting Gallery won't give Kokiri Sword

### ISSUE THREAD

**Issue by Charles445** [TestRunnerSRL/OoT-Randomizer#178]
Version 2.20.2 f.LUM
Settings: 922GS9AAB4AA3EAUGA
Seed: SWORDFISHM-3
Emulator: m64py 0.2.4

Adult Shooting Gallery won't give out Kokiri Sword as its reward. Instead, it will give 50 rupees.
Interestingly, it doesn't set the flag for completion either (0x0EF0 0x40)

This could create an unwinnable seed if Child Fishing is an always required location.
With that said, it is incredibly rare.

I was able to generate one more unwinnable using the same settings: SWORDFISHO-76

**Comment by emerald000** [comment]
You need to have a bow to get the reward. It gives out a 50 rupees otherwise.

**Comment by Charles445** [comment]
> 
> 
> You need to have a bow to get the reward. It gives out a 50 rupees otherwise.

Verified on SWORDFISHO-76, having bow resulted in the sword being given. 
I guess this is vanilla behavior so it doesn't give you a quiver upgrade if you don't have the bow, much like Rolling Goron and bomb bag.
Thanks for the explanation.
