### ISSUE TITLE
Error - Unable to place songs / Unable to place unique dungeon items

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#179]
Version: 2.20.2
Settings: R2AKABALDLAKS6REFA
Unknown Seed

Suggestion: When a seed fails, output something so we can find out what seed it was even if they leave it blank.

Apparently somebody actually got this error, and not with a coop seed either.
Does the retry code actually work, and are we retrying enough times if so?

**Comment by TestRunnerSRL** [comment]
It usually needs to retry 1-3 times from my experience, but I've never seen it go above 5. I can raise the retry to like 50-100, and it should be fine, it's really just there in case something is broken and it can never generate

**Comment by TestRunnerSRL** [comment]
Also if you turn the info output on, it'll say every time it retries

**Comment by r0bd0g** [comment]
"trying to generate a multiworld seed on the 2.20.2 and it keeps saying unable to place songs"
I asked which seed, and blank apparently.

**Comment by TestRunnerSRL** [comment]
Yeah same issue

**Comment by r0bd0g** [comment]
Seems likely it is sometimes caused by not retrying enough times, it is apparently also being caused by impossible seeds, caused by our key4key logic being incorrect at times.

**Comment by TestRunnerSRL** [comment]
This should be fixed now
