### ISSUE TITLE
Shuffle Rupees & Hearts Does Not Function Correctly

### ISSUE THREAD

**Issue by Controser** [TestRunnerSRL/OoT-Randomizer#1793]
I have tried shuffling these on many occasions, even through the dev build. Initially it worked perfectly for me. However, in the latest of releases I attempt to shuffle them and run into this issue:

1. The rupees and hearts are not shuffled
2. The spoiler still considers them to be shuffled so those items become unobtainable

I don't know how I could go about fixing this error if it is on my end, but hopefully someone is able to get this fixed up. That setting made the runs super fun!

**Comment by matthewkirby** [comment]
Hey! Would you be able to do two things for me?

1. Share a link from ootrandomizer.com to a generated seed with a spoiler log enabled that has this problem
2. Let me know what platform you are playing on where you are experiencing this issue?

**Comment by Controser** [comment]
> Hey! Would you be able to do two things for me?
> 
> 1. Share a link from ootrandomizer.com to a generated seed with a spoiler log enabled that has this problem
> 2. Let me know what platform you are playing on where you are experiencing this issue?

Absolutely! I have also added a picture below so you can see what I mean. I have tried both using the Randomizer web version as well as the Randomizer GUI version. 

1. https://ootrandomizer.com/seed/get?id=1262721
2. I tend to play my randomizers using ModLoader64 (pictured below) so that I can play them with other people and use custom player models. 
![OOTR](https://user-images.githubusercontent.com/46281978/203620937-3c246f3a-5abe-4c02-8228-5c570dedc6d8.png)

**Comment by matthewkirby** [comment]
Thanks a lot for this! So it turns out that seeds rolled on version 7.0 are not currently working properly on modlodaer64. The ML64 devs know about this and I believe are working on a fix. I apologize for the difficulties in the meanwhile.

That said, the randomizer now supports custom player models on its own. So in the meanwhile, you could give that a try.
