### ISSUE TITLE
Got Gerudo Mask instead of intended item

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1809]
Duplicate of #257

**Comment by cjohnson57** [comment]
Why was this made?

**Comment by r0bd0g** [comment]
Because #257 was closed and still is closed despite it never having been fixed.

**Comment by cjohnson57** [comment]
When has this occurred on any recent build?

**Comment by fenhl** [comment]
Closing in favor of the original issue since that has more info.
