### ISSUE TITLE
Mixed Multi Issue?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#181]
Report from STORM

"Just started a new seed with my buddy
I have an MQ Dungeon for Deku, he has regular
if that pertains to anything im about to say
He pulled a heart piece in the lobby chest, and it was for me, but I got a red rupee instead
is something messed up?"

Version:  2.20.2
Seed: oppai
Settings: M62M39NUF5HYS6EEEA

Seems like it could be an issue with the script moreso than the worlds, but who knows.

**Comment by TestRunnerSRL** [comment]
Unsure, but it seems like there's a few issues with co-op, including some reports of receiving the wrong item at times, which is what this sounds like. I still haven't been able to reproduce these bugs, which is making it hard to fix

**Comment by TestRunnerSRL** [comment]
I want to believe this issue has been resolved, but i'm not completely certain what was causing this in the first place since it was not reproducible
