### ISSUE TITLE
Multi Softlock

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#182]
So this should maybe be on the coop repo, but nobody posts issues there...

From: Surdjak

"My friend was pushing a big cube on a ground interrupter and got a 2 blue rupees at the same time, he got stuck there"

Apparently a "ground interrupter" is a switch of some kind.

**Comment by TestRunnerSRL** [comment]
I have no idea to be honest.

**Comment by TestRunnerSRL** [comment]
There are a lot more checks that have been added to get items for when it's safe to get an item. I really doubt this is still an issue.
