### ISSUE TITLE
Possible Logic Error / Unbeatable Variant

### ISSUE THREAD

**Issue by Naestriel** [TestRunnerSRL/OoT-Randomizer#183]
I believe the variant I ran through is unbeatable because, reading through the spoiler log, it required the player to obtain the Song of Storms located at "GS Forest Temple Outdoor West." However, also per the playthrough in the spoiler log, Link does not have the Song of Time or the Fairy Bow and only 2 small keys for the Forest Temple and therefore can't reach that particular Gold Skulltula. Spoiler log attached with original naming for variant and seed specification.

[OoT_R22JK9PXEFAAE9HTB_66718129_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2432108/OoT_R22JK9PXEFAAE9HTB_66718129_Spoiler.txt)

**Comment by flagrama** [comment]
Are you able to reach the block pushing puzzle? Should be able to reach the Floormaster room with hover boots and access the outdoor area from there.

**Comment by Naestriel** [comment]
My mistake, yes, I could get to the push block room but hadn't considered utilizing the hover boots to get to the "exit" in that room. Thank you, closing issue.
