### ISSUE TITLE
[bug] weird rhythmic chirping noise

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1836]
Video: https://cdn.discordapp.com/attachments/476723801032491008/1057886619186757642/20221229_050202.mp4
If the above link doesn't work, try this: https://discord.com/channels/274180765816848384/438698093354156032/1058447438270173274

First(?) report on the dec 6th: https://discord.com/channels/274180765816848384/438698093354156032/1049774010864508978

It was supposedly fixed the same day, but we got 2 more reports of this audio bug today:
https://discord.com/channels/274180765816848384/476723801032491008/1058153358784987156
https://discord.com/channels/274180765816848384/476723801032491008/1058470119531098154
v7.1.11 R-1 (this should be from after the aforementioned "fix" was merged)

**Comment by TreZc0** [comment]
We have not observed this on the main fork yet, right?
Afaik, it only happened on devFenhl and devR, so it might be a change added there?

**Comment by ETR-BTF** [comment]
Roman just merged a fix. I don't know if that's the same fix that was pushed to Fenhl and that it just hadn't been pushed to Roman's fork yet, or if it's a different fix. Apparently it is known what causes this issue:

> it's sort of UB yeah, it has to do with where the audio thread ends up (address-wise) which depends on how much we have in the payload (ie. our ASM and C)
I already had to bump the address a few times in the past, tho I don't think Dev ever ended up with the issue (but it could happen at any time when we add/remove ASM or C)
for reference here is the original discussion where we figured out what was going on: https://discord.com/channels/274180765816848384/512048482677424138/709788258590130177

**Comment by fenhl** [comment]
It's a different fix. On my branch I fixed it by changing the structure of the code a bit, I guess that ended up compiling to less machine code.

**Comment by ETR-BTF** [comment]
> We have not observed this on the main fork yet, right? Afaik, it only happened on devFenhl and devR, so it might be a change added there?

I just realized what you meant and yeah you're right I may have jumped the gun a bit when I opened the issue on this fork, Since it hasn't been confirmed on this fork yet and since both Fenhl and Roman have pushed fixes to their forks, I'm gonna close this issue for now.
