### ISSUE TITLE
Masks remaining equipped thru loading zones leads to issues including softlocks

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1844]
This has already been discussed in Discord, but I'm still opening this issue so it doesn't get forgotten.

#1790 introduced a feature where masks don't get unequipped when going thru loading zones or save warping. This is quite convenient when using the Bunny Hood speed-up feature, and I think it's worth keeping. But it did introduce some bugs that need to be addressed.

The first one is that you can wear masks in places where you normally cannot equip a mask, such as boss rooms, the Fishing Pond and during the stealth section in Hyrule Castle. While allowing masks in these places is not necessarily a bad thing, the fact that you can't unequip them _is_, in my opinion. A player might have trouble moving with the Bunny Hood speed-up in these places and should have the option to unequip the mask if they want to. It should be noted that you can still play the fishing minigame with the Bunny Hood on. The NPC's text box won't be replaced with one mentioning your mask, as happens with most other NPCs.

![image](https://user-images.githubusercontent.com/63906538/211821542-fe5f9471-df44-4b4a-9651-3dcdaa85dec9.png)
![image](https://user-images.githubusercontent.com/63906538/211821576-b99fa2ae-cc0f-494b-be9e-c7d15a1b0dd8.png)
![image](https://user-images.githubusercontent.com/63906538/211821617-c63613f4-b85b-46bf-a1dd-16b53e07143f.png)

The second bug, and this one is much more serious, is that being unable to equip masks can lead to softlocks if the player equip-swapped a mask and then loses the ability to equip-swap again to unequip the mask. This can happen if the player equip-swaps from the left side with Deku Nuts and then locks themself out of left-side equip-swap by picking up Deku Sticks. Some locations, like diving in the lab, won't give you the shuffled item if you're wearing a mask. Equip-swap is not yet part of Glitch Logic, but it will be in the future, so this should be addressed at some point. And even if it never became a part of logic, I still believe it should get fixed.

The only known way to force-unequip a mask is by traveling thru time, but that's not always available. One possible fix would be to unequip masks when save warping. While this is inconvenient, it should at least fix the softlocks. Another possible solution is to apply the patch to Child Link only.

Tested on v7.1.23

**Comment by cjohnson57** [comment]
@louist103 Can you address this?

**Comment by ETR-BTF** [comment]
Another bug:

> Full context - so I tend to play with Mask Sequence Complete and Fast Bunny Hood. In my recent seed (randomized main rules), I had adult spawn be at Forest Warp Pad. So, as child with the bunny hood on, I pulled the Master Sword and did a save warp to go dip Forest Temple.
It took a couple of minutes, but I soon discovered that I had the hoods speed effect as Adult. If I had to make an educated guess, it's a side effect of the changes made to prevent the forced unequipping of the Bunny Hood during transitions. Did a bit of science afterwards, and the soft reset is apparently also necessary for it to occur.

> just to clarify: to reproduce you equip bunny hood as child, go adult, savewarp and now you have bunny hood as adult?

> yeah I took a moment of my seed playthrough to test it out because I wanted to see what caused it... and I was able to not only replicate it but I even deliberately used it.

**Comment by fenhl** [comment]
Are any of the issues mentioned here still present in latest Dev?

**Comment by cjohnson57** [comment]
This should be resolved now with #1992 and #2001
