### ISSUE TITLE
[Suggestion] Don't randomize Shop Texts, with text shuffle in shopsanity

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#189]
I see this one asked for a lot...

**Comment by TestRunnerSRL** [comment]
Jessie, this is boring!

**Comment by TestRunnerSRL** [comment]
While I think it's part of the "fun" not knowing, this would fix the tokensanity + shopsanity + text shuffle softlock

**Comment by r0bd0g** [comment]
There's an option in text shuffle not to shuffle hints and keys, and maybe shops should be added to that.
