### ISSUE TITLE
Warp songs break Closed Forest logic with shuffled Ocarinas+Songs

### ISSUE THREAD

**Issue by mg1189** [TestRunnerSRL/OoT-Randomizer#19]
OoT Randomizer Version 2.15.4 f.LUM - Commit: 1adf120
Settings String: BWB3GAFAAACB
Seed: CRN124G5GD-1

This issue can occur, when "Shuffle Ocarinas" and "Shuffle Songs with Items" are enabled in a Closed Forest seed. The logic incorrectly considers Warp Songs an option to get access to items outside of the forest before beating Deku Tree. If this happens, it essentially makes the seed an Open Forest seed.

If this is an intended behaviour, then it should be noted, that Prelude of Light and Serenade of Water are not shown in the spoiler log playthrough, even though they could be required to leave the forest.

Spoiler log: https://pastebin.com/raw/CJWDmHZB

**Comment by TestRunnerSRL** [comment]
Fixed in #24
