### ISSUE TITLE
Suggestion: Completely disable item shuffling

### ISSUE THREAD

**Issue by aplumafreak500** [TestRunnerSRL/OoT-Randomizer#190]
This would allow Text Shuffling and other minor patches to be applied while disabling other randomizer features, for example, to have a (mostly) vanilla playthrough.

**Comment by TestRunnerSRL** [comment]
I get this (and plando) requested a lot. Something that won't happen before 3.0, but is eventually planned I guess. I will mention there is a practice hack available that accomplishes much of what you're asking for already.

**Comment by r0bd0g** [comment]
Is there an MQ practice ROM?

**Comment by TestRunnerSRL** [comment]
I don't believe so.

**Comment by TestRunnerSRL** [comment]
This is also a duplicate of #89
