### ISSUE TITLE
Using Ocarina at Bombchu Bowling Crashes on VC

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1938]
This is actually a vanilla "bug" but I'm not sure how exactly you would go about using the Ocarina in here legit.

To reproduce, walk up to where the camera turns to play the game, walk back, the pull out the ocarina, and then cancel the ocarina to crash the game.

**Comment by flagrama** [comment]
Noting here that this likely also crashed on N64 for anybody looking to attempt this again in the future.

**Comment by r0bd0g** [comment]
At least one N64 Emulator was tested iirc.

**Comment by flagrama** [comment]
I'm talking console with a flash cart.
