### ISSUE TITLE
I believe I have a broken seed

### ISSUE THREAD

**Issue by zorginof** [TestRunnerSRL/OoT-Randomizer#194]
I have a seed with keysanity, shopsanity, tokensanity, etc....
Everything closed. Kokiri forest, door of time, etc ...
So I'm stuck as a kid until I get the kokiri emerald, goron ruby, and Zora saphire. 
The problem is the kokiri emerald is held by phantom Gannon, and the boomerang is in the gerudo valley. I believe it's the only way to beat the tentacles in jabu jabu

**Comment by flagrama** [comment]
You only need Song of Time to open the Door of Time.

**Comment by zorginof** [comment]
Ok then. I'll just go find it. Thanks.

**Comment by zorginof** [comment]
Thank you a lot. 
I spent a day running around beating everything, and nothing. I finally looked at the spoiler log. SThen thought I was just unlucky, and got the one broken seed. I bought the song, and everything is good. Thank you.
