### ISSUE TITLE
Adult start with certain starting items equips bombs on the wrong C button

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1951]
Bombs are equipped on the C-down button instead of on C-right, where they belong. Longshot is also equipped on C-right instead of C-left. This is likely a vanilla bug that bled into Randomizer.

Seed link: https://ootrandomizer.com/seed/get?id=1375967

![image](https://user-images.githubusercontent.com/63906538/229285524-e2d465dd-4934-4db6-857b-328a3b377ced.png)

**Comment by fenhl** [comment]
A fix for this was included in #1000. Unfortunately that PR seems to have been inadvertently closed instead of merged. Please direct discussion of this issue there so we can determine whether it should be reopened.
