### ISSUE TITLE
Text too long, floats off box

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#196]
Progressive Strength Upgrade   230 Rupees
is too long for the textbox.

At least you can read it.

**Comment by r0bd0g** [comment]
(Do we really need the word "progressive" here?)

**Comment by TestRunnerSRL** [comment]
I made it use the clearer hint names for the items instead, which works out pretty well.

**Comment by r0bd0g** [comment]
Do dungeon items still say what dungeon they're from like that?

**Comment by TestRunnerSRL** [comment]
yeah the dungeon items still behave like before, this only affects non-dungeon items
