### ISSUE TITLE
Randomized Random Starting Age sometimes doesn't appear in the Spoiler Log

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1962]
I noticed this in some mixed pools seeds and I also generated a relatively normal seed on Fenhl branch that had this issue.
I don't know if this is a symptom of something more serious.

**Comment by fenhl** [comment]
Can this bug be reproduced on main Dev?

**Comment by r0bd0g** [comment]
I didn't check. It only sometimes wasn't appearing so it's hard to say how many seeds you'd have to generate before you could be sure whether it does or doesn't occur. And if it only occurs under certain settings it'd be even harder to track down.

**Comment by fenhl** [comment]
Then this is the wrong place for this report. If someone sees this bug on main Dev, please post a comment and we'll reopen.

**Comment by r0bd0g** [comment]
"I don't know if this is a symptom of something more serious."
What I meant was, I didn't know if it might be more impactful than merely not showing the setting? but also if it might be more impactful that merely only occurring on the fenhl branch and/or whatever branch the mixed pools tourney was on.

**Comment by r0bd0g** [comment]
But seems crass to outright close this without at least reopening it on your branch.

**Comment by fenhl** [comment]
I'm going to reopen on my fork, give me a minute.

**Comment by fenhl** [comment]
https://github.com/fenhl/OoT-Randomizer/issues/23

**Comment by fenhl** [comment]
Reopening since according to #2256 the root cause is not specific to my branch. Thanks @mracsys for the analysis!
