### ISSUE TITLE
Spoiler log playthrough section lists the same hookshot twice (in different spheres) instead of two unique hookshots

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#1967]
> Found a bug in the playthrough listing in the spoiler log, 
Lists as getting Progressive Hookshot from Song from Impa (which we started with) on both Sphere 0 and Sphere 1 and doesn't list the KF Midos Bottom Left Chest progressive hookshot at all in the spheres. 

https://ootrandomizer.com/seed/get?id=1396062

**Comment by fenhl** [comment]
Natheirean tested this and was able to reproduce on stable but not on Dev:

![plando](https://media.discordapp.net/attachments/438698093354156032/1101977295050252288/image.png)

![spoiler](https://media.discordapp.net/attachments/438698093354156032/1101977295268368384/image.png)

I'm going to call this already fixed. If anyone finds evidence to the contrary, please post a comment and we'll reopen the issue.
