### ISSUE TITLE
MQ Spirit Temple chest unreachable

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#197]
I just found this out. Not sure if you know.

https://youtu.be/FqI17fUQq5E Video here. Young link shoots eye in the gap and the chest drops. I pushed the big block in so I can not get the chest.

**Comment by r0bd0g** [comment]
We fixed this a long time ago. Did you even try to get the chest?

**Comment by TopHatMan** [comment]
Sorry I just did , I was just coming to close it.

**Comment by r0bd0g** [comment]
Should be added to the readme tho…
