### ISSUE TITLE
37th Piece of Heart exists

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#1971]
This will potentially be accessible in glitchless play now with the addition of hideout shuffle. I'd say we have 4 options:
1. Do Nothing.
2. Consider it in logic.
3. Shuffle it. (Optionally could change the vanilla item to avoid having too many hearts in the pool.)
4. Remove it.

I think removing it when hideout entrance are shuffled is probably the best way to handle this. Just leaving it there and not even handling it in logic (for heart wincons) doesn't seem correct to me. But I don't like how leaving it there or in the pool could let you collect move than the usual maximum number of hearts.

But there's also the question of exactly which combination of settings should any changes be made under.

**Comment by fenhl** [comment]
I agree that removing it would be best. Presumably this heart piece does have a permanent collection flag (i.e. it's not infinitely repeatable), so we could simply set this flag at patch time to remove it.

**Comment by ETR-BTF** [comment]
Do bingo boards made for OoTR also have the "37th PoH" square?

**Comment by fenhl** [comment]
No. OoTR Bingo boards are designed to be completeable glitchlessly.

**Comment by fenhl** [comment]
Another solution would be to make it a setting, only shown when hideout entrances are shuffled. The options would be shuffle, vanilla, and remove. With remove (or when the hideout is unshuffled), the logic could be hacked so the region doesn't have to be reachable, and the vanilla option would include it in logic.
