### ISSUE TITLE
Can't Open Chests

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#199]
Raikaru Today at 5:45 PM:
so latest multiworld update, constantly getting the problem of not being able to open chests. can't get out of mido's house without it happening

**Comment by TestRunnerSRL** [comment]
Are you sure you updated the bizhawk script? There was a update and the update to the rando doesn't work with the previous versions of the script

**Comment by TestRunnerSRL** [comment]
I'm not convinced this wasn't an issue with not having been updated, seeing as this hasn't seemed to be an issue after using the following update.

**Comment by r0bd0g** [comment]
shdwlnk is experiencing this issue, having downloaded hours ago... The two rom files were different seeds.
