### ISSUE TITLE
Saving and resetting right before obtaining the item from "ToT Light Arrows Cutscene" will set the flag but not give the item, possibly leading to softlocks

### ISSUE THREAD

**Issue by ETR-BTF** [TestRunnerSRL/OoT-Randomizer#2002]
Saving and resetting after entering the Temple of Time as adult, but _before_ obtaining the item from "ToT Light Arrows Cutscene" will stop giving the item on that check, possibly leading to unbeatable seeds. I believe there's a 1 frame window for this.

(This is already known. This issue is just being opened for documentation purposes.)

**Comment by fenhl** [comment]
I was under the impression that this was fixed by #1695. Are you saying this issue still exists?

**Comment by ETR-BTF** [comment]
> I was under the impression that this was fixed by #1695. Are you saying this issue still exists?

Ah my bad. I had forgotten to update the wiki page. I tried looking for open or resolved issues/PRs but I didn't guess the right key words.
