### ISSUE TITLE
File Name displays incorrectly on Temple of Time Pedestal 

### ISSUE THREAD

**Issue by DarkHeroZark** [TestRunnerSRL/OoT-Randomizer#202]
OoT Randomizer Version 2.20.14 f.LUM  -  Seed: 4JWQWRND99
Settings (9JARSRJMEYTTN8RVHA)
clearer_hints: True
 
The hint for the medallion in "Link's pocket" displayed scrambled. Filename was set to "Dark" and was displaying "kark" in the hint. Unsure if other instances of the filename are affected.

Edit: Link the Goron also had the same name error

**Comment by TestRunnerSRL** [comment]
This has been fixed already
