### ISSUE TITLE
Recursion Error

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#2032]
Roman — Yesterday at 8:29 PM
Not sure if it's already known but current dev (7.1.143 f.LUM) encounters recursion errors when generating seeds with multiworld and a lot of shuffle settings (generation failing with "RecursionError: maximum recursion depth exceeded while calling a Python object"). For example I can reproduce it with a player count of 4 using the Hell Mode preset, tho it also happens with different combinations of settings, including no ER at all. It looks like the error is thrown before calculating the playthrough when copying worlds, and I'm guessing it's related to the recent changes made to the copy methods in https://github.com/OoTRandomizer/OoT-Randomizer/pull/1870. The common factor seems to be the amount of items and/or locations shuffled being over a certain amount, which probably brings the recursion depth over the Python limit 
Here is a setting string that seems to reproduce it consistently and is relatively quick to run since it has no ER: HSA4BGBSL62AEMTDDS6PFQNA4QMANASKAAUAASAAAUB89L9RAA29BAAAAAAZEBDBSBAJYDSW9 (it's still 4 player MW tho ofc)

**Comment by jdunn596** [comment]
Worth noting that this _is_ most likely related to the playthrough because it doesn't occur when generating seeds without a spoiler log from what we've seen

**Comment by cjohnson57** [comment]
I didn't know pinning was a feature but I'm using it as this should be fixed before the next release

**Comment by fenhl** [comment]
@cjohnson57 looks like closing an issue doesn't automatically unpin it.
