### ISSUE TITLE
Biggoron Item is repeatable (or not obtainable at all?)

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#2061]
flagrama — Yesterday at 6:40 PM
https://github.com/OoTRandomizer/OoT-Randomizer/blob/9bbf665578b257ac24f9406bd9a91f4771bba41e/ASM/c/trade_quests.c#L144-L155 if I'm reading this right, if adult trade is off a flag never gets set for claim check being turned in, so turning in the claim check is always valid since the slot doesn't change on trade? and it looks like vanilla depends on bgsFlag being set or not, which I believe only gets set in rando if you find the bgs, so there is no story flag triggered for it? 
(idk much about the new trade stuff, so that's just a guess from a quick repo search though)

**Comment by fenhl** [comment]
This should probably be pinned as release-blocking @cjohnson57

**Comment by r0bd0g** [comment]
Assuming it's real! I didn't actually confirm this myself; took people's word for it.

**Comment by cjohnson57** [comment]
I've seen a couple reports and one had a vid

**Comment by flagrama** [comment]
Twitch clip that was linked that made me take a look https://clips.twitch.tv/AgitatedCrackyLegBlargNaut-5ft52iNOJkaQYjTR and Discord link to discussion of said clip: https://discord.com/channels/274180765816848384/274186223147417600/1136871770041880696

**Comment by r0bd0g** [comment]
But wait there's more?

Lars P — Today at 11:39 AM
apparently getting the "DMT Biggoron" check requires eyedrops, altho logically i only need being adult and the claim check. biggoron has rang, so im very sure that i didnt get that check yet 

https://discord.com/channels/274180765816848384/274186223147417600/1139851862829449266

beginning of this topic is here ⁠gameplay-and-tricks⁠. ive also posted my spoiler log, emulator version, patch file and the used plando in that convo, if smth of those is needed

Lars P — Today at 12:59 PM
update: i continued playing that seed and i found broken sword and eyedrops. i went to biggoron, showed him eyedrops and sword (got the correct items for that), but then i tried the claim check again and still didnt get the claim check item 
i also tried showing him the stuff in other orders (i placed a savestate before showing him anything), but he still wont give me the claim check item. the other two checks work like intended, but the claim check one doesnt. apparently the game thinks, i already got the claim check check

**Comment by r0bd0g** [comment]
Sounds like it might be a flag overlap??

**Comment by DuskTheUmbreon** [comment]
https://discord.com/channels/274180765816848384/438698093354156032/1146631619352997898 Another instance of it occurring - on Retroarch

**Comment by cjohnson57** [comment]
@mracsys Would you mind looking into this if you have the time?

**Comment by mracsys** [comment]
I'll take a look when I can. It'll be a few days.

**Comment by r0bd0g** [comment]
This still pinned.
