### ISSUE TITLE
Sometimes Hints can hint locations inside pre-Completed Dungeons

### ISSUE THREAD

**Issue by TrenterTR** [TestRunnerSRL/OoT-Randomizer#2085]
https://ootrandomizer.com/seed/get?id=1478403

Spirit in that seed is pre-Completed. (empty)

The Gossip Stones on the other Hand gives us following info: "They say that upon the Colossus's right hand is a Small Key."

**Comment by damdayou** [comment]
It seems that line 152 in Fill.py is not doing the job anymore. (Or it never did what I thought it does and I just got extra-lucky on all my tests?)
https://github.com/OoTRandomizer/OoT-Randomizer/blob/35eb6fcdc5089e26e6db6320541ef8af15fdeb1b/Fill.py#L147-L153 
I'm afraid I'm not familiar with the hint system and I don't have much free time these days, so I'm just leaving this piece of code here as a starter in case someone wants to tackle the problem.
