### ISSUE TITLE
well won't drain

### ISSUE THREAD

**Issue by zorginof** [TestRunnerSRL/OoT-Randomizer#209]
I got the fairy ocarina, Visited Guru Guru, Back as a kid, Played song of storms, but the well won't drain

**Comment by zorginof** [comment]
I restarted everything.  Actaully reinstalled the emulator, and it worked finally.

**Comment by flagrama** [comment]
Was this with PJ64 or a different emulator?

**Comment by zorginof** [comment]
mupen 64
