### ISSUE TITLE
Removing Small Keys while key rings with boss keys are enabled removes boss keys from seed

### ISSUE THREAD

**Issue by Maplesstar** [TestRunnerSRL/OoT-Randomizer#2137]
Example: https://ootrandomizer.com/seed/get?id=1521310
Seed is glitchless logic, boss keys in own dungeon, 5 medallion Ganon's boss key, but the playthrough shows beating bosses without collecting boss keys.
![image](https://github.com/OoTRandomizer/OoT-Randomizer/assets/69886167/287ff050-1a3e-4c30-a501-fa842423a14c)
Need some kind of failsafe to somehow reject this combination of settings that leaves the seed without boss keys.

**Comment by cjohnson57** [comment]
This was mostly addressed in #2071 but it was pointed out that they should be starting items in the spoiler

**Comment by Maplesstar** [comment]
Loaded the example seed above. Link doesn't have the boss keys as starting items in it. Fire temple is easy to get to from the spawn point and the boss door is locked and not able to be opened.
