### ISSUE TITLE
Water Temple Bug

### ISSUE THREAD

**Issue by burstkk** [TestRunnerSRL/OoT-Randomizer#215]
I couldnt finish the Water Temple without using boss key skip. The last small key needed to open a door with a chest containing the boss key was dropped by the boss itself. 

No glitches were used at all (besides the boss key skip i mentioned)

OoT Randomizer Version 2.20.2 f.LUM  -  Seed: VOJCCEEQMW

**Comment by flagrama** [comment]
You need to share settings string as well for us to actually view your seed's spoiler log. Do you have a screenshot of the chests remaining in the Water Temple at this point?

**Comment by burstkk** [comment]
Settings String: B62QKQSLBY9ZSNAEGA
I don't have a screenshot anymore, but im trying to reproduce it tomorrow

**Comment by flagrama** [comment]
As far as I can tell this is an actual logic bug. I'm sure someone will fix it soon if it is.

**Comment by r0bd0g** [comment]
This was fixed 6 days ago.

**Comment by flagrama** [comment]
Was it fixed in Dev or just the rework branch?

**Comment by r0bd0g** [comment]
Fixed in 2.20.17

**Comment by r0bd0g** [comment]
It could also occur in mq fire and water if dungeon skulls were shuffled.

set_rule(world.get_location('Water Temple Boss Key Chest'), lambda state: (state.has('Small Key (Water Temple)', 6) and state.has('Iron Boots') and (state.can_play('Zeldas Lullaby') or world.keysanity) and ((state.has_explosives() and state.has('Progressive Strength Upgrade')) or state.has('Hover Boots')) and state.can_use('Longshot')) or (state.has('Small Key (Water Temple)', 5) and (item_name(state, 'Water Temple Boss Key Chest') == 'Small Key (Water Temple)' or not (world.keys_placed or item_name(state, 'Water Temple Boss Key Chest') == 'Boss Key (Water Temple)'))))

Note the check for the water bk that was added.

**Comment by r0bd0g** [comment]
The spoiler for that seed shouldn't be able to beat the game.
I think world.keys_placed isn't being copied???
If so, that would mean that items at those locations could end up collected too early in playthroughs.
I don't remember if hints uses the copied world or not, but if so, it could cause problems.
Gonna look into it.

**Comment by r0bd0g** [comment]
TR, can you add

        ret.keys_placed = self.keys_placed

to world.copy?
