### ISSUE TITLE
Dungeons have one major item - Spirit Temple with 3

### ISSUE THREAD

**Issue by friedpen** [TestRunnerSRL/OoT-Randomizer#222]
OoT Randomizer Version 2.21.12 f.LUM  -  Seed: spiritmajor
Settings (94BR37TXFK9QUK9JSA):
Silver Gauntlets Chest: Farores Wind
Mirror Shield Chest: Serenade of Water
Twinrova Heart: Small Key (Fire Temple)

OoT Randomizer Version 2.21.12 f.LUM  -  Seed: spiritnokeysanity
Settings (94BR37TFFK9QUK9JSA):
Spirit Temple Sun Block Room Chest: Lens of Truth
Silver Gauntlets Chest: Bolero of Fire
Mirror Shield Chest: Serenade of Water

Seems like the Colossus hands aren't working as intended as they appear to consistently contain the 2nd and possibly the 3rd item of the dungeon.

**Comment by r0bd0g** [comment]
For some reason I was under the impression that shuffled keys and boss keys would be excepted from the list of major items, but that does not seem to be the case.

Can_fill does not account for a dungeon maybe having 2 items, and it doesn't account for the spirit temple hands not being in the dungeon. So spirit temple configurations not involving at least one of the spirit temple hands are always rejected, and then nothing prevents a hand that has not been selected from being a major item.

**Comment by TestRunnerSRL** [comment]
Ok this should be fixed now
