### ISSUE TITLE
Blue warps sometimes don't activate

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#2230]
The new blue warps from #2034 sometimes don't activate. Only 3 reports since this was added to my fork in January 2023, most recently at <https://www.twitch.tv/videos/2157998297> played on 8.1.39. When this happens, reloading the scene fixes the bug, but also duplicates the item given by the blue warp.

A previous idea of what could be causing this was that the ranges for giving the item and for activating the blue warp might not exactly match and that this is what causes the bug (https://github.com/OoTRandomizer/OoT-Randomizer/pull/2034#issuecomment-1627584163), but I was unable to reproduce by drastically changing one radius or the other.

Given the camera angle in this most recent clip, maybe it has something to do with the center of the blue warp not being on screen at the time the item is picked up?

**Comment by tjongejonge** [comment]
https://clips.twitch.tv/ModernCreativeNikudonDansGame-0KNzspM5Ov0YVF41 here is another clip of the blue warp not activating

https://www.twitch.tv/videos/2158563186 the whole stream, around the 57minute mark

**Comment by fenhl** [comment]
Okay so WTHH is definitely looking at the blue warp, but they're both in the air above the blue warp and then land outside of it. So maybe it's caused by the item waiting in the queue until Link is in a state where he can receive it, by which point he's no longer in the blue warp?

**Comment by fenhl** [comment]
Here's a setup that seems to be consistent:

[OoT A7A63 M6RRQZ77MB.webm](https://github.com/OoTRandomizer/OoT-Randomizer/assets/641386/db142dca-0b79-40d3-9c38-aab757851812)
