### ISSUE TITLE
Custom Music Crash on VC

### ISSUE THREAD

**Issue by shirosoluna** [TestRunnerSRL/OoT-Randomizer#2257]
https://ootrandomizer.com/seed/get?id=1710952
https://clips.twitch.tv/EndearingWrongShrimpSoonerLater-tANKaYkGBRMUt-dc
[OoTR_1710952_G9D4LU1LV2_Cosmetics.json](https://github.com/user-attachments/files/16198108/OoTR_1710952_G9D4LU1LV2_Cosmetics.json)

Custom music on child diving minigame crashed consistently. This was rolled on main dev, seed link and cosmetic file attached.
Custom music was patched on web, played on Wii VC. 

Crashes have happened occasionally on realrob's branch however this was the first consistent crash that was able to be replicated repeatedly.

**Comment by shirosoluna** [comment]
https://github.com/user-attachments/assets/545e5d68-a362-4bfc-a8b8-03c192571d75

additional attempt, not mashing through the text. White text from the song appeared but still crashed

**Comment by flagrama** [comment]
If you're able to consistently get this to happen generating seeds offline, could you give #2258 a try and see if it prevents this crash from happening? The code should already be compiled on that PR.

**Comment by shirosoluna** [comment]
> If you're able to consistently get this to happen generating seeds offline, could you give #2258 a try and see if it prevents this crash from happening? The code should already be compiled on that PR.

just confirming on github as well, but this did resolve the crash in diving minigame when tested. Thank you again for providing the patch!
