### ISSUE TITLE
Still encountering Heart Piece glitch where it removes HPs

### ISSUE THREAD

**Issue by 03bgood** [TestRunnerSRL/OoT-Randomizer#2283]
Please fix this glitch. I was supposed to be fixed, but it's still occurring.

**Comment by aofengen** [comment]
This is not nearly enough information to figure out anything. Please give us some sort of information about the seed you were playing, when it happened, what you were doing, etc. Just saying it happened is a guaranteed way to have it never be fixed, because it can't be reproduced

**Comment by 03bgood** [comment]
> Please fix this glitch. I was supposed to be fixed, but it's still occurring. Not sure what's causing it but it probably happens when when you find a heart container and you have 2 or more HPs and then it resets them to 0.

**Comment by 03bgood** [comment]
> This is not nearly enough information to figure out anything. Please give us some sort of information about the seed you were playing, when it happened, what you were doing, etc. Just saying it happened is a guaranteed way to have it never be fixed, because it can't be reproduced

I have wonder items and freestanding recovery hearts and rupees are also randomized. Shops, Maps, Compasses, Keys, Scrubs, tokens, and Cows are also randomized.

**Comment by flagrama** [comment]
Either link the seed or provide a spoiler log. Also describe the situation where it happened, or post a video if available. Video is much preferable.

**Comment by 03bgood** [comment]
> Either link the seed or provide a spoiler log. Also describe the situation where it happened, or post a video if available. Video is much preferable.

Nevermind, I was able to get all 20 heart containers. So it wasn't a glitch.
