### ISSUE TITLE
Spiritual Stones and Medallions

### ISSUE THREAD

**Issue by Lord540** [TestRunnerSRL/OoT-Randomizer#229]
It would be cool to have a setting how to randomize  the stones and medalions

**Vanilla** = Medallions and Stones are in that dungeon where they should be 
**Randomized**= Medalions and Stones are randomized between the dungeons
**completely Randomized**= The Medalions and Stones are randomized in normal Spots and the 8 Spots where you get them you get normal items so that is another spot. (Example Dampes Race gives the Fire Medallion and in the chamber of sages you get the hookshot)

I think you should not get any hints in the Temple of Time when you play on the last setting.

**Comment by flagrama** [comment]
That last setting has generally been considered to just be "Triforce Hunt but with extra steps" with Triforce Hunt being a play option of the ALTTP randomizer and something that has been thrown around as a possible play option in the future.

>Triforce Pieces
The Triforce has been shattered and scattered into 30 pieces throughout Hyrule! Collect 20 pieces to win!

As for Vanilla locations, that might be possible but it might be something that gets held off on until this is done: https://github.com/TestRunnerSRL/OoT-Randomizer/issues/89
