### ISSUE TITLE
Invalid playthrough creation in spoiler logs in many cases

### ISSUE THREAD

**Issue by KevinPal** [TestRunnerSRL/OoT-Randomizer#23]
Note1: I'm working on the fix for this, but I want to open an issue in case others have something to say . I should have it done by this weekend if all goes well
Note2: The simplified playthroughs were created by setting the win condition to a different item, I think we should have an option for this, but that is a separate issue

[Example spoiler one](https://pastebin.com/jXGc33H8)
[Simplified spoiler one](https://pastebin.com/5cLezwGp)
Here, it states that we can get the `Lens of Truth` from `Bombchu Bowling Bomb Bag`, but having Bombchus is a requirement for this, since bombchus are in logic. There are no bombchus obtained in the previous spheres, however logic is still valid, as the Bomb Bag can be found in `Kakariko Back Grotto Chest`, which can be used to get `DM Crater Wall Freestanding PoH: Bombchus (10)`, but this is not in the play through

[Example spoiler two](https://pastebin.com/9bWMMMH1)
Here, both the `Bombchu Bowling Bomb Bag`, `Deku Salesman Hyrule Field Grotto`, and ` DM Crater Wall Freestanding PoH` are in sphere two, with no explosives in sphere one. Logic is not broken, has `Impa House Freestanding PoH` has `Bombchus (10)`

This issue seems to be that the play through generation allows for items from future spheres to be used to access items in the current sphere, creating circular dependencies. This can be seen here
[Example spoiler two with Master Sword as Win Condition](https://pastebin.com/WQj6H4QX)

By removing all items after the `Master Sword`, `Bombchus (10)` now come into the play through.
By tracing through the the original generation, the playthrough expected the player to use the `Song of Time` to become get the `Master Sword`, then use the `Hammer` to break into the `Deku Salesman Hyrule Field Grotto` to obtain the `Song of Time`

By tracing similarly for the case in example one, the play through expects the player to be able to buy Bombchus in the Haunted Wasteland, as the player can access them in the future

 Although I have not tested, the issue seems unrelated to Bombchus being in logic, or that the Door of time is closed. It however seems significantly more likely to happen under these less common conditions. Also, people playing under these uncommon conditions are more likely to be experienced, and probably do not notice this issue

**Comment by rchrm5** [comment]
[OoT_RH6ZM4CAECUB_3UXS5RELTO_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2299820/OoT_RH6ZM4CAECUB_3UXS5RELTO_Spoiler.txt)
See the attached spoiler log. Although Bombchus are not set to affect logic, they are required to get the GS tokens in branch 5 needed for the Megaton Hammer.

**Comment by EvilApple567** [comment]
[OoT_9Q5X7ZYBA9MAA_MZ0ENWQENA_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2325286/OoT_9Q5X7ZYBA9MAA_MZ0ENWQENA_Spoiler.txt)

Playthrough logic seems to be broken in consecutive steps. 3 requires explosives, scales, or Hover Boots for ZD entry, and 4 requires Hookshot for Scarecrow or explosives for magic beans for use of Step 3 item (LoT) to accomplish Step 5.

**Comment by Nicholas-Steel** [comment]
Robdog has been working on a fix for these issues I believe and he has submitted a Pull Request here: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/132

**Comment by TestRunnerSRL** [comment]
It's finally done. The spoilers should be good not 75b3bdf41efcbb9668261921bcf71e08d1865ccc
