### ISSUE TITLE
(Multiworld) Game Freezes on receiving Deku Shield

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#236]
From: mikusplaysgames

"i was holding a pot, and my multi partner picked up a deku shield. the game froze. i waited for it to register but it never happened so i reset. i was back at the kokiri house getting the items that he got me all in a row, then the deku shield popped up and it froze again. we both closed out of the room, closed the console, and closed bizhawk. it still froze when it tried to have me animate the "get item" on that deku shield."

---

It's unclear if it's multi-specific or whether it's potentially related to the recent change to the deku and hylian shield items (or the equipment screen I guess what do I know). Somebody tested the shields in single player and it seemed fine. It sort-of feels to me like something in the change is just not equipped for cross world? I dunno.

**Comment by TestRunnerSRL** [comment]
I really doubt this wasn't related to the issue with 3.0 build not having the proper deku shield code. I'm going to close this unless this is reproduced on the newer versions.

**Comment by r0bd0g** [comment]
This was reported prior to the release.
