### ISSUE TITLE
Scarecrow's Song Softlock

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#240]
Sometimes when you play scarecrow's song it softlocks.
It was thought to be from the song being too fast, but that doesn't totally seem to explain it?
It's a vanilla issue however people are reporting it happens more often in rando?

**Comment by TestRunnerSRL** [comment]
Hmnm, you might want to ask mzxrules about this one since they were the one that did the fix for this.

**Comment by krimtonz** [comment]
Fig did some testing with this and found that it was related to amount of lag.

**Comment by TestRunnerSRL** [comment]
We put a minimum note length of 4 frames, so this shouldn't happen anymore. Let me know if there's still a softlock, and we can raise the min more.
