### ISSUE TITLE
Linux release requires ubuntu 18.04 or higher

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#243]
TreZc0_'s server runs on 16.04.

Mac release has similar restrictions? Requires Mac OS X 10.13. Somebody with 10.10 could not run the release and had to use the source.

**Comment by phixtyseven** [comment]
Is there any associated error message?

**Comment by TestRunnerSRL** [comment]
I think this is probably because that is the version they were build on. I'm not sure how to handle this without haivng someone build for those versions

**Comment by phixtyseven** [comment]
This would classify as _wontfix_ at this point, correct?

**Comment by TestRunnerSRL** [comment]
I'll likely be dropping multiplatform support in favor of the webpatcher anyways
