### ISSUE TITLE
Error: Maximum recursion depth exceeded while calling a python object

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#249]
Raikaru Today at 7:27 PM
Well this is odd. got a "Error: Maximum recursion depth exceeded while calling a python object" error trying to make a multiworld seed. settings E9LAPSBAUCALSSNCAK8A seed UVTJP9PK3R
tried to create a save patch file but none generated but the first seed did

3.1.16

Raikaru Today at 7:36 PM
turned keysanity off and it stopped giving the error

**Comment by TestRunnerSRL** [comment]
The actual error is:
`maximum recursion depth exceeded while pickling an object`
I'll look into it, but yeah not sure why a specific generation would have a depth issue

**Comment by Cuphat** [comment]
This was related to the World File code, I believe. It should no longer be relevant now that world files are obsoleted.
