### ISSUE TITLE
Shop Softlocks

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#261]
From: Ponsari

OoT Randomizer Version 3.2.2 f.LUM  -  Seed: 5DF09ITH99  -  Settings: BB62R39KVGZ4ASN89DJA

https://cdn.discordapp.com/attachments/438698093354156032/509377230170882048/unknown.png

Apparently the shop slots were just empty when they walked in.

**Comment by TestRunnerSRL** [comment]
Should be fixed now
