### ISSUE TITLE
Can't check settings when creating from file

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#263]
So this is sort of related to #250 
It would be neat if it wasn't the tabs that get disabled, but rather the options on them. This would allow people to check settings when creating from a file. 
Not sure if tkinter allows to get all elements on each of the tabs to avoid having to hard code them all, but if not, maybe they could be stored when generating the tabs from settings.py?

**Comment by TestRunnerSRL** [comment]
Implemented as of 3.3.2
