### ISSUE TITLE
Need to buy blue fire to thaw King Zora but don't have big enough wallet

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#282]
According to my spoiler log:

`King Zora Thawed: Bottle with Letter`

So the only way to thaw King Zora is with buying the blue fire, but the blue fire costs 300 rupees (I'm playing with Shopsanity), and the spoiler log says I should only have one progressive wallet upgrade. So, is this seed unbeatable?

[OoT_BR92QABAAASV2MMAF2LG7DDGA_YB0JI8AH14_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2588034/OoT_BR92QABAAASV2MMAF2LG7DDGA_YB0JI8AH14_Spoiler.txt)

**Comment by flagrama** [comment]
Is the `Bombchu Shop Item 4: Buy Blue Fire` priced at 300 rupees? Or is it a lower amount than normal? I haven't played any shopsanity personally.

**Comment by joeauty** [comment]
Damn! Never thought of that.. Clever! Thanks again!

To answer your other question, yeah, the Bombchu shop price was 300 rupees.
