### ISSUE TITLE
Shop Softlocks (Like #261)

### ISSUE THREAD

**Issue by theroflcoptr** [TestRunnerSRL/OoT-Randomizer#288]
OoT Randomizer Version 3.4.26 f.LUM  -  Seed: 0W9WE8CV1Z Settings (BTST9UCAAAALSPBA4P7NLCA6JB):

Ran into the same softlock as shown in #261, except in the zora shop. Multiple blank items, any of them causes the game to softlock and appears to be the pocket egg.

**Comment by pkmnfrk** [comment]
Same version - Seed: ZPTN10MP71 - Settings: BVUL8ADAAAAQ3CEAA8HJCAGMBB

+1, three of the slots in Goron City were empty

**Comment by TestRunnerSRL** [comment]
Should be fixed now
