### ISSUE TITLE
Zeldas letter overwrites mask from salesman

### ISSUE THREAD

**Issue by creutzwald1105** [TestRunnerSRL/OoT-Randomizer#29]
In castle town we first went to the mask salesman to buy the Keaton mask before proceeding to the castle. In the court yard we got the letter from Zelda which has overwritten the mask.

The gate to death mountain is already open so the guard doesn't care about it (but talks about a mask). Therefore we can't get rid of the letter.

If we ask the mask salesman, he tells us that we should sell the current mask first. (The Keaton mask is still displayed behind him.)

1) Is this a bug or is there a way to proceed with or reset the mask sequence?

2) From the spoilers I got the two lines below. This should be everything that's not reachable if we continue this game or is there another reward involved somewhere? (I just skipped through the spoilers with Ctrl+F searching for 'mask' so we don't get spoiled.)
```
Deku Theater Skull Mask: Arrows (30)
Deku Theater Mask of Truth: Piece of Heart
```

Here's the full spoiler.txt:

[OoT_92B5KVCSAAUB_LEANICOLAS1337_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2281339/OoT_92B5KVCSAAUB_LEANICOLAS1337_Spoiler.txt)

Settings: 92B5KVCSAAUB
Seed: LEANICOLAS1337

**Comment by TestRunnerSRL** [comment]
Thanks for reporting this. Should be fixed in b4037670c21d7d6520203bd4409a9bcd29e736f4
