### ISSUE TITLE
Can't get Double Magic

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#307]
From: orly

dunno if its a known bug, i just got the second magic upgrade in version 3.5.4 f.LUM and it stayed at the small magic meter. 
Seed: N4MTR0K161 
Settings (B9UA8ADANCAT9EV89BMLA)

Edit: playing on Bizhawk

**Comment by TestRunnerSRL** [comment]
fixed
