### ISSUE TITLE
No such location for MQ locations

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#316]
Somebody was using settings string BRUS9A8MZ3AKJTJBASWRN2UC
and it was failing about as often as not due to there being "no such location" for a number of different MQ locations.

**Comment by TestRunnerSRL** [comment]
so the issue is that they are disabling locations that do not exist in the world (because MQ). I can ignore invalid locations, but it would be nice if there was a way to warn disabling dungeon locations in general

**Comment by phixtyseven** [comment]
Oh, this is the thing I fixed. I'm dumb :P
