### ISSUE TITLE
Apparently the code to rebalance multiworld is not actually doing anything?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#317]
(and maybe that's fine)

There was a report of somebody finding somebody else's lens at bongo (not beatable only, lens on all).

Tyrus Today at 3:34 PM
3.5.7

Tyrus Today at 3:34 PM
DZUA8A9JMDSXPYNLRC7JB settings
089FU4PRCV seed

(They never said how many players.)

**Comment by BeeLuigi** [comment]
Number of players is part of the settings string (it's 3)

**Comment by r0bd0g** [comment]
Is that new? I don't remember it doing that back in 3.0...

**Comment by BeeLuigi** [comment]
Apparently, yeah

**Comment by Hamsda** [comment]
We noticed something similar, I had a Ruto's Letter for someone else in my GC which was a medallion dungeon for the other person. From what I understood that should not happen?

**Comment by r0bd0g** [comment]
It's issues 326 now.
