### ISSUE TITLE
The multiworld balance fix breaks multiworld with mixed MQ dungeons

### ISSUE THREAD

**Issue by BeeLuigi** [TestRunnerSRL/OoT-Randomizer#326]
For example: 
Version 3.6.5 f.LUM
Settings: DDUTTUSHAMTAAASEAASTC
Seed: NF5VLA5IA
Error: No such location Gerudo Training Grounds Maze Path Third Chest

This is because different players have different MQ dungeons, so it can't check the same location in a different World.

**Comment by TestRunnerSRL** [comment]
lol that's pretty funny, I forgot that could be a thing. I'll have to think about that one

**Comment by r0bd0g** [comment]
Both versions of the world would have to exist, and the unused copy would have to contain no items, and naming conflicts would have to be resolved and...

**Comment by TestRunnerSRL** [comment]
Nah, I'd either do one of two things most likely. Check if you can reach the dungeon entrance if the location doesn't exist, or ignore those kinds of checks for those locations. I'm pretty busy so I don't have the the time to put much thought into this right now, so I'll have to mess with it later

**Comment by r0bd0g** [comment]
I think it should be "dungeon entrance" but for every area. Like, Kakariko in general, not just only adult shooting gallery, say.

**Comment by TestRunnerSRL** [comment]
Maybe, although I feel like this only applies in the cases where the location doesn't exist, which is just dungeons
