### ISSUE TITLE
Presets not being saved?

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#328]
* `python3 ./Gui.py`
* set a bunch of settings, click on `save preset`, give it a name. I see the preset in the dropdown
* quit the python app
* relaunch, the preset I had saved is gone

My apologies if this is a known issue, a WiP, or I'm doing something wrong, but I wanted to bring this up as an issue just in case this comes as a surprise given that I don't see a ticket for this.

**Comment by Cuphat** [comment]
It's working for me. Are any of your other settings changes saved? Is there a presets.sav in the same directory as Gui.py?

**Comment by TestRunnerSRL** [comment]
It's supposed to save the presets (along with your settings) when you close the gui window. So if it's not saving the preset, is it also not saving your settings?

**Comment by joeauty** [comment]
I see... 

I was expecting it to save when I was clicking "save preset" (on a preset that I already created). I was doing a save preset + quit. Is it possible for quit to also work the same as closing the GUI window?

Perhaps more of a UX issue than a bug.

**Comment by joeauty** [comment]
It's rather unclear that "save preset" can be used to update an existing saved preset as well?

**Comment by TestRunnerSRL** [comment]
tbh, I don't think this is something I'll be unlikely to change, since this is actually pretty normal behavior for most software. Saving over an existing file will overwrite it. I can make the file IO happen when you hit save instead of quit, but the fact that you're terminating the process in an unclean way is kind of already a problem, since then it's never able to save your settings.

**Comment by joeauty** [comment]
Speaking of the GUI changing a lot, I absolutely adore the new hover/iron boots equipping feature in the HUD. Brilliant and well done!

Why not just make the file I/O happen whenever an option is clicked? On the Mac (which is what I'm using) I'm used to quitting when I'm done and options being applied on click, which seems to be the most OS agnostic UI convention overall these days?

**Comment by TestRunnerSRL** [comment]
I could but i feel like that's half the issue here, cause the previous settings are also unsaved if you terminate python without letting the script finish. and saving the setting on every change feels like a lot of system io i'd like to avoid if possible

**Comment by TestRunnerSRL** [comment]
Ok I made it save the presets immediately when they are changed.. But I want to make it clear that it's still not saving your previous settings, which it would save if you closed the script cleanly instead of terminating python.
