### ISSUE TITLE
Song of Storms (Zora's River PoH) pickup freezes game

### ISSUE THREAD

**Issue by EvilApple567** [TestRunnerSRL/OoT-Randomizer#332]
[OoT_0406E_2YY6BHJK6R_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2651050/OoT_0406E_2YY6BHJK6R_Spoiler.txt)

Tested on Retroarch Mupen64Plus Core, ParaLLel N64 Core, Mupen64Plus-Gui, and Project64 2.3 with GLideN64. Single world generation.

**Comment by krimtonz** [comment]
Investigating.

**Comment by TestRunnerSRL** [comment]
We're pretty certain that the issue has to do with the text IDs used. I'll probably redo the text ID stuff whenever we get the ASM refactor done. In the meantime, I'll change it to use safer IDs to fix the bug for now

**Comment by TestRunnerSRL** [comment]
ok 3.7.2, I moved the IDs, so it should be ok now
