### ISSUE TITLE
Freeze on Generation

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#336]
From: HoagieWitaStogie
Version: 3.7.1 f.LUM
Settings String: BRED6FA8MP4BUDWDUECF2EAAEWK3A3EWZE
Seed: EXPLOSIVEDIARRHEA

**Comment by TestRunnerSRL** [comment]
I know you won't like this solution, but it does resolve the problem and doesn't really have any real effect on the item distributions.

**Comment by TestRunnerSRL** [comment]
Another possibility is maybe having the Gossip Stone logic to ignore whether locations are disabled. Dunno, I'd have to put more thought into it, but my hunch says it won't work.

**Comment by r0bd0g** [comment]
I think you could temporarily undisable locations when placing the gossip stone hints? But you might be expected to get an item at a disabled location in order to reach a required gossip stone hint. I'm not sure whether that's a problem. The guarantee that you can get reach your gossip stone hints is still kept, technically.

What I suggested before was to remove the logic for requiring the stone of agony to beat the game, but that doesn't allow stone of agony to appear in disabled locations. But I think at the least something needs to be done to prevent this change from mucking up the playthrough and woth.

**Comment by r0bd0g** [comment]
Thinking about it some more though, this is a significant change to item placement in some cases. Beatable only, with mask or truth hints, would mean that the stone dungeons would always have to be completable.

**Comment by TestRunnerSRL** [comment]
Ok this should be in a way you should approve of. Placement is not affected anymore. If hints are completely inaccessible, then it will place the hints with no logic.

**Comment by r0bd0g** [comment]
Thanks!

One thing though, I feel like you could save a small bit of time by saving whether the hints are reachable back when you do the initial collection for the spoiler log? But it's probably not worth the trouble setting that up.

**Comment by TestRunnerSRL** [comment]
sure, i can do that

**Comment by TestRunnerSRL** [comment]
actually, it's a bit awkward since the playthrough might not be created, and "get_required_items" doesn't build a max state.
