### ISSUE TITLE
Please add a line to the Quirks to Know section of the ReadMe for the spirit temple crystal switch.

### ISSUE THREAD

**Issue by distilled1** [TestRunnerSRL/OoT-Randomizer#339]
Please add the following line into the ReadMe files under "Quirks to Know" so that newbies won't be dumbfounded when they're supposed to hit a spirit temple switch and logic has not given them the boomerang:
"In the Spirit Temple, child Link can hit the crystal switch in the room with the Stalfos using the slingshot at the right angle instead of the boomerang."

The switch is very similar to a boomerang-required switch in Jabu-Jabu, and most newcomers will assume that they need the boomerang then turn back.

**Comment by flagrama** [comment]
It's already in the repo's wiki: https://github.com/TestRunnerSRL/OoT-Randomizer/wiki/faq-broken-seed-glitchless#lower-metal-bridge-on-child-side-without-boomerang

**Comment by TestRunnerSRL** [comment]
I think Trez is working on getting a more proper wiki up at some point, but these kinds of documentation takes a lot of time and people willing to help.

**Comment by TestRunnerSRL** [comment]
And yeah we're trying to cut all of that kind of info out of the readme and migrate into a more structured wiki. The readme is too long for anyone to actually read.
