### ISSUE TITLE
KEYSANITY_MESSAGES is not defined

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#340]
From Pikachuisloveandlife

Settings: BBED93F9MP4C2EJFLCWFAAEDL3AAJ2WK
https://cdn.discordapp.com/attachments/476723801032491008/521528036370153493/unknown.png

**Comment by krimtonz** [comment]
This is related to text shuffle, in is_not_exempt KEYSANITY_MESSAGES no longer exists.

**Comment by OlafurKrH** [comment]
i just got this too, hopefully it'll be fixed.
