### ISSUE TITLE
Impa gave no song

### ISSUE THREAD

**Issue by mattman2841** [TestRunnerSRL/OoT-Randomizer#35]
OoT Randomizer Version 2.15.20 f.LUM  -  Seed: DWOASVW869

Settings (RAH7ZVCA6VBB):

In a seed where got the oot before the weird egg when went to Zelda to get letter and song from impa only got letter after getting letter the courtyard only had Zelda and a few guards at the start of the courtyard. After getting kicked out was able to talk to malon in lon lon to get a song. After save quieting the letter reverted to chicken and was able to do stealth part again but still not able to get song

**Comment by TestRunnerSRL** [comment]
Did you watch the Ocarina of Time cutscene?

**Comment by mattman2841** [comment]
yes

**Comment by TestRunnerSRL** [comment]
Ok, Known issue with Getting Ocarina of Time despawns impa.

**Comment by TestRunnerSRL** [comment]
Fixed in a8d11707bf407dc4a7c365c4b64fc3f11007b10e
