### ISSUE TITLE
[MQ] No more spots to place Small Key (Forest Temple)

### ISSUE THREAD

**Issue by Cuphat** [TestRunnerSRL/OoT-Randomizer#354]
There seems to be something wrong in the MQ Forest Temple key logic. I've gotten this a lot of times in testing.

Example seeds (v3.8.9):
Settings: BRGBWBACAJFTDFAASBNKJDF, Seed: EOKQA5L6FR-3
Settings: CRGBWBACAJFTDFAASBNKJDF, Seed: IHQ0YTGAPW-7

**Comment by r0bd0g** [comment]
This is caused by the boss key being placed in the only chest prior to the first locked door. In 3.0 there was code to forbid the boss key from going into this chest if keys were placed in dungeons, but it appears to have been lost in the logic refractor.

**Comment by Cuphat** [comment]
Awesome. Thanks for figuring that out so quickly, r0bd0g. 👍

**Comment by r0bd0g** [comment]
Actually... There might be more code that was lost.
