### ISSUE TITLE
stick/nut upgrades broken

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#356]
So the sticks and nuts don't endlessly appear over ones head anymore, but the upgrades somehow broke. The first upgrade you get puts you immediately to max capacity.
[example](https://clips.twitch.tv/HyperStormyBobaKappaClaus)
We later got the intended max capacity and it just refilled to max capacity (as other items in e.g. plentiful would).
Other items like bow or bombs work as expected.

**Comment by TestRunnerSRL** [comment]
Hmm, it's possible that the upgrade condition is messed up, but then it should be broken for single world to.

**Comment by Hamsda** [comment]
Maybe it is, it's just the first seed I've played on Dev since the fix yesterday.
