### ISSUE TITLE
Duplicate items in multiworld

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#362]
SparkyToday at 8:30 PM
Getting an Item in Multi-world for a person While they hold a Cucco,Bomb,Etc. Makes them get a double of the Item (you get it twice)(edited)

we were using the Dev Build 3.8.10

with the updated Co-op Script

**Comment by Hamsda** [comment]
Yeah this even allowed to duplicate major items 😳 
[hookshot dupe](https://clips.twitch.tv/JoyousCleverTaroCoolStoryBro)

**Comment by TestRunnerSRL** [comment]
Should be fixed now
