### ISSUE TITLE
Unbeatable Seed?

### ISSUE THREAD

**Issue by tommaniacal** [TestRunnerSRL/OoT-Randomizer#363]
The Bottle with Letter is sold by one of the DMC Scrubs, which needs the hammer to unlock. The hammer is given by thawing King Zora, however. Isn't this unbeatable without glitches?

Settings String: BRJDVBAUFN4AAAAAKSDF
Seed: HVCFOWOLRP
[OoT_052C8_HVCFOWOLRP_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2678476/OoT_052C8_HVCFOWOLRP_Spoiler.txt)

**Comment by flagrama** [comment]
I'm not even going to look. Is it the Bomb DMC scrub? That one is child only.

**Comment by r0bd0g** [comment]
From that description it could also be buying blue fire, so I'll actually look.

**Comment by r0bd0g** [comment]
Yeah it was the bomb scrub.

**Comment by Cuphat** [comment]
DMC Deku Scrub Bombs doesn't need hammer. It's the child only scrub.

https://wiki.ootrandomizer.com/index.php?title=Scrubs#Death_Mountain_Crater:_4_scrubs

**Comment by LostThePirate** [comment]
Buy Blue Fire in Kakariko for 300r with a Goodness Wallet.

**Comment by r0bd0g** [comment]
One of his wallets is behind ruto's letter.
But yeah, it's the debu scrub bombs child-only scrub thing.

**Comment by tommaniacal** [comment]
Thanks guys. I didn't know there were two scrubs on DMC that sold bombs lol
