### ISSUE TITLE
Disabled location on WOTH

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#365]
https://cdn.discordapp.com/attachments/438698093354156032/522989278754766858/OoT_67972_IhrKnntNix_W5_Spoiler.txt

Deku Theater Skull Mask W4 has Iron Boots W4, WOTH, but the location is supposed to be disabled.

**Comment by Cuphat** [comment]
I generated the same seed and managed to get the same spoiler: except for one thing. Deku Theater Skull Mask does not appear as a disabled location. Changing the disabled locations to those that appear in this log generates a different seed with a different settings string.

[OoT_90F55_IhrKnntNix_W5_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2678974/OoT_90F55_IhrKnntNix_W5_Spoiler.txt)

**Comment by r0bd0g** [comment]
Anyway it seems most likely that the person who generated this seed lied about skull mask having been disabled and tried to pass it off as a bug.

Another slightly weird thing about this is that the seed was supposed to be "IhrKönntNix", but the ö character was ignored.

I'll close this later today, but there are 3 sort-of weird things I guess that got noticed while looking into this.
