### ISSUE TITLE
Map and Compass Shuffling

### ISSUE THREAD

**Issue by Sicilica** [TestRunnerSRL/OoT-Randomizer#37]
Keysanity shuffles dungeon items around, and we also have the ability to replace maps/compasses with rupees and shuffle them around. Why not have a middle ground of keysanity, like how tokensanity is handled?

Since maps/compasses are essentially junk anyway, changing them to rupees doesn't accomplish much, and we've already accomplished the technical hurdle (ie, updated text and so on) of moving them out of their dungeon - so why not have a setting that moves dungeon maps and compasses to the global pool while leaving keys alone? You still get +2 item pool draws per dungeon and add the same amount of junk to the pool, but the junk you find is a bit more interesting (while it technically doesn't make much of a difference, I'll feel emotionally better about fishing for a random map than fishing for $5).

I don't mind making a PR myself if anyone thinks it's a decent idea.

**Comment by TestRunnerSRL** [comment]
I don't see how this change makes any difference. The only change is whether you get one junk item or a different junk item. I don't really feel like it's in the spirit of dungeon items, and honestly will probably lead to more confusion.

**Comment by Sicilica** [comment]
I suppose another way to think of it is: I'm advocating condensing `nodungeonitems` and `keysanity` into a single setting, since they already achieve a very similar purpose. `keysanity` obviously also could make progression through a dungeon more difficult, but I would say that having just `nodungeonitems` vs also having `keysanity` as about the same difference as having `tokensanity` set to `dungeons` vs set to `all`.

I also think that leaving the maps and compasses intact is more intuitive, and the only reason they were ever changed to rupees is historic (that is, we weren't injecting a bunch of extra text). If you use `tokensanity`, it doesn't convert every token into a rupee in addition to shuffling them - although it would make very little difference.

Looking things over, it would be a pretty minimal change to the code as well. I could probably throw it together in a few minutes this evening.

**Comment by JojHeywood** [comment]
unprompted i know, but it would be nice to have dungeon/compasses shuffled separate to keys.
