### ISSUE TITLE
Show if all skulltullas collected on the dungeon info display

### ISSUE THREAD

**Issue by rlbond86** [TestRunnerSRL/OoT-Randomizer#396]
It would be nice if the Dungeon Info display showed a skulltulla marker if all of the skulltullas are collected inside that dungeon. I have started to work on it but I have no idea how to recompile the files in ASM/c into a patch. If someone can either point me toward documentation or help, I'd appreciate it. I can see it has something to do with bundle.o and some of the other files but I'm not sure exactly how to get it all hooked up.

**Comment by phixtyseven** [comment]
Unless you're writing code your code in c you should be fine to just install and run the armips build script. To create your base.z64 rom, be sure to use a copy of ZOOTDEC.z64, or you will get DMA conflicts.

**Comment by rlbond86** [comment]
I guess this is what I am confused about. It appears that the dungeon info logic is in ASM/c/dungeon_info.c. How does this interact with build.py?

**Comment by r0bd0g** [comment]
Why?
It'd make more sense to track if there were any randomized checks left in a dungeon, but that sounds like a pain to do, and I'm not even sure if I want that...

**Comment by rlbond86** [comment]
The game already tells you if you have all the skulltullas in a dungeon, but you have to actually go in to look at it without dingeon info display, just like for keys and the compass/map.

**Comment by TestRunnerSRL** [comment]
I'm kinda concern this will add more clutter to the display that honestly already has too much. I also don't think you really information gain anything since the info is there if you look at the map.

**Comment by phixtyseven** [comment]
It would be nice to hook the world map locations to indicate whether all checks have been completed in the area, rather than just the skulltula tokens. Otherwise, (as it is) the world map isn't much use in rando, and may as well be overwritten by the some custom menu.

**Comment by rlbond86** [comment]
I am pretty sure the map does not show skulltulla completion for dungeons.

**Comment by flagrama** [comment]
It does. Right next to the dungeon name, on the left side.
![image](https://user-images.githubusercontent.com/634079/50347853-12ce5c00-0505-11e9-9e55-67df09b8dfaa.png)

**Comment by rlbond86** [comment]
Yeah but you have to be in the dungeon to see it. It also shows the compass, map, and boss key but those were added to the dungeon info display.

**Comment by flagrama** [comment]
AFAIK Map and Compass were added because they now actually have functions that aren't useless to the majority of players after years of playing the game. Keys and Boss Keys were added because keysanity means you can get them anywhere instead of just in the dungeon, so the information isn't immediately available to you.

For Skulltulas, you can check if you got them all before you leave the dungeon as that information _is_ immediately available to you when it is relevant.

**Comment by rlbond86** [comment]
For tokensanity that's not really the case. Perhaps only show the skulltulla completion if tokensanity is enabled?

**Comment by TestRunnerSRL** [comment]
The information is on the world map. It shows the symbol next to the name of every area that is finished, including non-dungeon areas. I also believe these counts are not for the tokens for but the GS themselves, so it is still relevant even for tokensanity.

**Comment by rlbond86** [comment]
Dungeon skulltullas are not counted in those map symbols. For example, if you grab all the skulltullas outside of dungeons, the entire map will have the skulltulla marks, even if some dungeons still have skulltullas inside.
