### ISSUE TITLE
No ocarina_memory_game did not work (Ver. 2.9.5 f.LUM)

### ISSUE THREAD

**Issue by TPJEEMIAGE** [TestRunnerSRL/OoT-Randomizer#4]
Seed had Hover boots in ocarina memory game, despite the fact i chose to not include it in logic.

[OoT_QS98FA3MEA_DXUVS3QGDA_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2181305/OoT_QS98FA3MEA_DXUVS3QGDA_Spoiler.txt)

First keysanity run, maybe it's related ? Never had problem with this feature before.

Anyway, thanks for your work, i'm having a blast with this ;)

Edit : NVM, i've checked and you already corrected the problem, a not was missing in line 67 from rules.py

**Comment by TestRunnerSRL** [comment]
Yeah the option was reversed. Sorry about that
