### ISSUE TITLE
Infinite loop on Link the Goron

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#401]
Tried two different seeds, and when I bomb Link the Goron and get the prize I get an infinite loop of receiving the item over and over again, and I can't get out of it and therefore open the doors to the shop and crater.

**Comment by joeauty** [comment]
Unrelated question too... If this is confirmed a bug, can I plug in the seed ID and regenerate this ROM with the same placement and a fix for this issue?

**Comment by joeauty** [comment]
Disregard my last question, I downgraded (to 3bdb2f6086a1fb94cd76e35976e99b47b83ac78f) and regenerated the ROM with the same seed and this problem went away.

This does appear to be a bug with the latest Dev.

**Comment by Darkrai87** [comment]
This is due to the BGS collection delay fix from #400 , @fig02 says its due to all gorons using the same function to give link an item, which is was an oversight and is planning on applying the fix to trail only.

**Comment by fig02** [comment]
Should be good to go when TR has a chance to merge it. The scene check turned out to be unnecessary, krim and I figured out that some stuff was hardcoded that shouldnt have been. Tested to work fine with all gorons that give items

https://github.com/TestRunnerSRL/OoT-Randomizer/pull/403

**Comment by r0bd0g** [comment]
You remembered to test Giant's Knife?

**Comment by mzxrules** [comment]
the updated patch still looks sketchy because you're replacing instructions that are mutated by the overlay

**Comment by fig02** [comment]
fixed. thanks for the suggestion in discord

**Comment by TestRunnerSRL** [comment]
Merged in, should be good now
