### ISSUE TITLE
Make important small chests distinctive with "Chest size Matches Content"

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#406]
Create a Small Chest that uses the Boss Key Chest texture, for the purposes of clearly signalling when a Small Chest contains a Progression Item while using "Chest Size Matches Contents" (since some chests will always be small). I assume eventually all instances of forced Big Chests will get solved some day.

**Comment by TestRunnerSRL** [comment]
If you are on latest dev, all chests should be able to be made large/small now. Also Boss Keys will be put in gold chests
