### ISSUE TITLE
Biggoron yielded no reward

### ISSUE THREAD

**Issue by ProtoFG** [TestRunnerSRL/OoT-Randomizer#407]
I gave biggoron the "Worlds Finest Eyedrops" or whatever the name is, and once he gave me the claim check, I pretty quickly gave it to him and I got no rewards. I proceeded to talk to Biggoron and he said that the sword was his finest work, and when I tried to give him the claim check, he just let me keep it as a souvenir.

**Comment by flagrama** [comment]
Which version is this?

**Comment by r0bd0g** [comment]
Randomizer version?

**Comment by LostThePirate** [comment]
Sounds like Collection Delay, if this is an older version of OoTR. If it's Dev from the last day or so, that's a different story...
Exact version number, please?

**Comment by ProtoFG** [comment]
It is the version from the last day or so. Don't remember the exact version

**Comment by fig02** [comment]
Yeah just gonna second that its very important that you post your version number here. Want to be sure the seed was generated before the fix was added

**Comment by ProtoFG** [comment]
I got the wad from my brother. Might take a bit to get version number. Will get it as soon as possible

**Comment by ProtoFG** [comment]
Got it sooner than I thought. Brother says version is "3.10.7 f.LUM"

**Comment by flagrama** [comment]
Yeah, that should be fixed finally in the latest versions (3.11.x f.LUM)
