### ISSUE TITLE
Graveyard is both barren and WOTH

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#408]
https://pastebin.com/B7Sh1SPA

Check world 3. Hammer on the PoH.

Raikaru then said
posted the wrong log for my problem :P
fixed it

So I dunno what's going on there.

**Comment by LostThePirate** [comment]
The W3 player got a hint that Graveyard was Barren, but upon peeking the log when everyone in the 7-man multi was stuck, it was discovered that W3 Graveyard ledge HP held a WOTH Hammer.

**Comment by TestRunnerSRL** [comment]
As I figured this had nothing to do with graveyard. Multiworld wasn't being properly accounted for so it would not correctly check whether locations matched. Should be fixed now.
