### ISSUE TITLE
Bombing Goron as child bugged out

### ISSUE THREAD

**Issue by Urkelli** [TestRunnerSRL/OoT-Randomizer#41]
According to my cheat sheet, I was supposed to get a small key to forest temple from bombing the goron in goron city as child, but something bugged out and I didn't get anything at all. This softlocked forest temple, where light arrows were supposed to be so I couldn't kill ganon or finish at all.

SEED: T7WDAXTEDD
Settings: MZV3ZAFDSJCD

**Comment by TestRunnerSRL** [comment]
Did you have Bomb Bag? The rolling goron as child only gives an item if you bomb him in the tunnel and you have bomb bag.

**Comment by TestRunnerSRL** [comment]
Yeah getting the item from the goron as child is very picky
