### ISSUE TITLE
Generating the same seed twice results in different item placement

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#411]
https://cdn.discordapp.com/attachments/438698093354156032/526637351947075584/OoT_FD39E_QVV6C7G63H_W3_Spoiler.txt
https://cdn.discordapp.com/attachments/438698093354156032/526637667082043392/OoT_FD39E_QVV6C7G63H_W3_Spoiler.txt

Generating subsequent seeds all match the latter's item placement.
It apparently doesn't matter what seed you actually generate first. Any seed, then subsequent ones will all be different.
Notably, the medallions for player 1, and only player 1, are different. The other changes in the seed seem to branch out from there.

**Comment by r0bd0g** [comment]
TrenteR_TRToday at 6:35 AM
I tried 3 different 3.10.7 builds and all lead to total different Settings with the same settings string(edited)

https://cdn.discordapp.com/attachments/438698093354156032/526710605424361473/pure_horror.png

also, why does all say "No Logic" in the Logic Rules. 
I probably have to start digging more


TrenteR_TRToday at 7:11 AM
okay, i have all different builds of 3.10.7 before it got change to 3.10.8
And I can't reproduce the same settings with the Settingstring provided

also, 11 different versions of the same version generate with the same settingsstring mostly different settings... 



^ I have no idea what this person is going on about but it sounds weird.

**Comment by TestRunnerSRL** [comment]
This was really obscure but Plentiful Item + Non-shuffled Kokiri Sword would change the base item pool which would in turn affect later generations. We should never change these as they should really be constant. We should really consider making all of those lists to be tuples since they behave the same way but are immutable.
