### ISSUE TITLE
VC crash on talking with hot-rodder goron and link the goron.

### ISSUE THREAD

**Issue by KingBoolean** [TestRunnerSRL/OoT-Randomizer#419]
When playing on “no logic” seeds on VC wads, I’ve been experiencing consistent VC crashes whenever interacting with either goron before they give you their item.

**Comment by Cuphat** [comment]
What version? Because I am pretty sure this was fixed recently.

**Comment by KingBoolean** [comment]
It was a version from maybe 5 days ago. I’ll update and try again. Thanks for the quick response!

**Comment by Darkrai87** [comment]
For future reference a version number is much more helpful than relative terms like “latest” or “from 5 days ago”. Commits to this branch are made quite often so it can be hard for devs to track which build you’re referring to. The version is always listed at the top of the randomizer.

**Comment by TestRunnerSRL** [comment]
I don't think we're going to get a follow up here...
