### ISSUE TITLE
Game crashed with sound buffer problem?

### ISSUE THREAD

**Issue by Cyler1992** [TestRunnerSRL/OoT-Randomizer#42]
SlimDX.DirectSound.DirectSoundException: DSERR_BUFFERLOST: The buffer memory has been lost, and must be restored (-2005401450)
   bei SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   bei SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   bei SlimDX.DirectSound.SoundBuffer.get_CurrentPlayPosition()
   bei BizHawk.Client.EmuHawk.DirectSoundSoundOutput.CalculateSamplesNeeded()
   bei BizHawk.Client.EmuHawk.Sound.UpdateSound(Single atten)
   bei BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   bei BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by TestRunnerSRL** [comment]
I'm not sure this is an issue with the Randomizer, but a problem with BizHawk. You can try asking for help with setting up Bizhawk on the Discord server.
