### ISSUE TITLE
Ruto's Letter in "barren" region

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#425]
From: Nikolai
I've finished a multiworld seed and ran into an issue where I received a hint saying "Water Temple is barren of Treasure". After looking at the spoiler the bottle with letter is located in the water temple.

Seed: TWOvTOvTOO
Settings: C9GD6XCASUUDJGAHEHEJSJWJ2JNKAL6KJMEC6M7ENLEN6RASESJSNSSSNRTRXR3R7RBSFSKSPSTSXS3S7SBTFTKTBAEDEVTLJBA
Version: 3.11.12

**Comment by LostThePirate** [comment]
Fixed in v3.11.13 - update.

**Comment by r0bd0g** [comment]
It looks like this is likely the same issue that was fixed with 3.11.13.

**Comment by r0bd0g** [comment]
I just want to defend myself for missing that this was fixed already, is b/c there is special code involving ruto's letter and barren hints. So bit of a coincidence that it was that item that was showing up for this guy. :p
