### ISSUE TITLE
Profanity filter, not working?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#433]
Slengshit, apparently.
https://cdn.discordapp.com/attachments/512048482677424138/528754192450453524/unknown.png
3.11.24

**Comment by Nicholas-Steel** [comment]
Slengshit isn't profane, if it was sleng shit then... it's still not profane. Shit is shit is shit. I could maybe understand preventing swear words but removing vulgarity in a game with blood and a bloody torture dungeon?

**Comment by TestRunnerSRL** [comment]
It's not that it's not working it's just that `shit` is not on the list. This is something that I was pretty borderline about in general. `shit` is definitely profane but it's also on the mild end of things. I think in general I'm in favor of adding it to the filter, but again this is probably a little over the edge.

Also I don't really agree with our argument @Nicholas-Steel, there's a pretty major difference in how things are presented vs what they are. In any case, one kind of maturity should not imply another. Yes oot should would probably be rated T in today's standards under mild violence, but different times. Also even still there isn't a single Zelda game that has profanity, and I think we should try to at least stay in the style.
