### ISSUE TITLE
[Suggestion] "King Zora moved"/"Open Zoras Fountain" option

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#438]
KnightShift Today at 8:35 PM
Soooo i just realised; we have options to open forest, door of time, gannon's bridge, and even choose to unlock gannon's boss door. Buuuut no option to move King zora? :thinking:

I think this might actually be an interesting option. Would remove a required Rutos letter if ZF/Jabu/IC are needed. Sort of similar to the open kak option I guess.
Not sure what would happen with the letter, probably best to just not add it to the pool and instead use a 4th random bottle.

**Comment by krimtonz** [comment]
Probably remove the bug label and add enhancement. Though this seems like a pretty good option to me.

**Comment by krimtonz** [comment]
I’ll add tonight. Up to TR if he wants to merge though.

**Comment by Hamsda** [comment]
I can't, it is automatically added because of the template.
Might need another template for suggestions :P

**Comment by flagrama** [comment]
You can create an issue without the template
![image](https://user-images.githubusercontent.com/634079/50552357-5d677b00-0c5f-11e9-9ad9-98a4f2f4a67e.png)
"Open a regular Issue"

**Comment by Nicholas-Steel** [comment]
Could make it so you need to hand the letter to him & Thaw him as an adult in order to get the reward from him?

**Comment by r0bd0g** [comment]
You don't have to hand the letter to him to get the thaw reward even normally?

**Comment by Nicholas-Steel** [comment]
Correct, I was just thinking it'd be a way to keep the letter relevant if the player has King Zora moved by default.
