### ISSUE TITLE
Disable Quick Swap

### ISSUE THREAD

**Issue by Physonian** [TestRunnerSRL/OoT-Randomizer#440]
I play on PJ64 because I can´t get another program to work correctly ( I know it is not recommended).
When I play OoT, PJ64 seems to handle the D-Pad and the Analog Stick as the same action or key ( or however you´d call that). This means I put on Iron or Hover Boots on no matter what I use ( D-Pad or Analog Stick). So it would be nice to have an option to disable the quick swap so that I can actually play the game.

**Comment by TestRunnerSRL** [comment]
This sounds like a controller binding issue in your settings.

**Comment by TestRunnerSRL** [comment]
Also as we don't officially support PJ64, I'd highly suggest using Bizhawk or Retroarch instead.

**Comment by Physonian** [comment]
Yeah that makes sense. I still think that there are people who would appreciate such an option.

**Comment by Nicholas-Steel** [comment]
I believe PJ64 isn't a platform the developers target, so if a bug crops up that exclusively affects PJ64 you shouldn't expect a fix.

**Comment by phixtyseven** [comment]
Its compatibility is officially unsupported, so yeah. It's likely to continue working to an extent, since a few devs use pj64 debug for testing, but compatibility isn't a promise.
