### ISSUE TITLE
Ocarina Memory Game Skip.

### ISSUE THREAD

**Issue by rchrm5** [TestRunnerSRL/OoT-Randomizer#45]
Ocarina Memory Game is set to true, but spoiler log still lists the reward as a Piece of Heart. Is this intended?

**Comment by flagrama** [comment]
The logic only keeps progression items from ending up on those locations if you select it.

**Comment by TestRunnerSRL** [comment]
Just to clarify, "removing" those locations means that you do not need to get the item there to beat the game. It's possible the item can still be useful (like a bomb bag) but there will always be another way to beat the game without needing to check those locations.

**Comment by rchrm5** [comment]
Gotcha. thanks.
