### ISSUE TITLE
Potentially unbeatable seeds when using "Chest Size Matches Contents"

### ISSUE THREAD

**Issue by rlbond86** [TestRunnerSRL/OoT-Randomizer#457]
The rule for "Spirit Temple Compass Chest" is:

     Progressive_Hookshot and can_play(Zeldas_Lullaby)

However, when using the "Chest Size Matches Content" option, this chest can become small if it contains a junk item. This was not considered an issue since the item would not be required to finish a playthrough (discussion [here](https://github.com/AmazingAmpharos/OoT-Randomizer/issues/177)).

However, commit 21513857 changed the chest size for small keys from large chests to small decorative chests. This means that if the "Spirit Temple Compass Chest" contains a small key, and no other small keys are available in the Early Adult section of the Spirit Temple, and the Longshot is further inside the Spirit Temple, and either the Requiem of Spirit is inside the Spirit Temple or the Early Child section of the Spirit Temple contains no keys, the seed will not be beatable.

Even if there are keys as a child, it might still be possible to softlock if the doors are opened in the wrong order and the Longshot is behind a locked door.

Potential fixes:

1. Change the rules to require the longshot for that chest always
2. Change the rules to require the longshot for that chest if "Chest Size Matches Contents" is enabled
3. Enforce option number 2 if the chest ends up containing a key
4. If that chest contains a small key, override it to be large-sized
5. Somehow manipulate the chest position so it's possible to hookshot onto it
6. Somehow add a scarecrow to that location or some other way of getting there with just a hookshot
7. Move chest position so that it is never reachable by hookshot and update logic
8. Some other solution?

![temp](https://user-images.githubusercontent.com/3186821/50665663-c6f0cd80-0f6e-11e9-9194-374d3d30e512.png)

**Comment by rlbond86** [comment]
An unbeatable seed can be generated with the following:

Commit b235035
Settings BHBG8MF2FAXGAAAJGT7AMA
Seed I08O34619Q-159

The four accessible chests in the Spirit Temple will be the following:

    Spirit Temple Child Left Chest:                        Ice Trap
    Spirit Temple Child Right Chest:                       Deku Stick Capacity
    Spirit Temple Compass Chest:                           Small Key (Spirit Temple) # requires Longshot
    Spirit Temple Early Adult Right Chest:                 Piece of Heart

However, the third Progressive Hookshot upgrade is deeper in the temple:

    Spirit Temple Boss Key Chest:                          Progressive Hookshot

**Comment by AvosMeLardo** [comment]
I also experienced a similar glitch with the "Chest Size Matches Contents" setting. When playing the Sun Song inside of dungeon like areas that would stun Redeads / Gibdos or the Graveyard Sun Song Chest the game would freeze after the song having Link standing there with the Ocarina to his mouth, never loading the Freezing Gibdo's / Sun Song Chest.

**Comment by r0bd0g** [comment]
Are you sure that's related to chest sizes?

**Comment by TestRunnerSRL** [comment]
I would probably say we either move the chest or add a hookshot target

**Comment by phixtyseven** [comment]
Moving the chest is more vanilla, I like this fix

**Comment by DatXFire** [comment]
Fixed as part of #471 rebase.
