### ISSUE TITLE
Dampe Dig PoH Permanently Missable

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#466]
If you dig up the heart piece and don't collect it, it's gone forever.
This is a vanilla OoT bug.
It was "fixed" OoT3D by allowing you to collect the PoH as many times as you want.
Funny, this glitch in OoT3D was discovered, before it was discovered in vanilla.

**Comment by DatXFire** [comment]
Fixed in #464.
