### ISSUE TITLE
Double Defense chest size

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#468]
MikusPlaysGames Today at 2:20 AM
Request for Double Defense be moved to big chest in chest size matches contents. 
When it is placed in a dungeon combining chest size matches contents and 1 major item, it appears in a small chest and leaves the player confused as to what the major item should have been

**Comment by rlbond86** [comment]
Seems like double defense shouldn't count as a major item in the first place...

**Comment by flagrama** [comment]
I can't think of any reason Double Defense should be a major item either.

**Comment by r0bd0g** [comment]
It's not used atm but it actually could be logically important in quad damage. For the "useless" items like DD, Ice Arrows... there's some inconsistency about how those are handled across the various... things.

**Comment by TestRunnerSRL** [comment]
DD was supposed to be a in a big chest. This is a bug that happened in the refactor.
