### ISSUE TITLE
Multiworld Crashes upon Entering Mido's House/Kokiri Sword

### ISSUE THREAD

**Issue by CascadeHope** [TestRunnerSRL/OoT-Randomizer#473]
Tried doing a multiworld with some friends, and it crashes once we go into the Kokiri Sword check or Mido's House near the chests. Not certain if other checks crash as well, since these were our initial checks.

**Comment by DatXFire** [comment]
Gonna need some more info here, version, settings string, seed, spoiler log, any clips of the crash if you have them, etc. all listed in the original template that you seem to have ignored.

**Comment by CascadeHope** [comment]
Sorry about that. It was late and I just quickly posted that, not thinking about the template.

**To Reproduce**
1. Create a multiworld seed with the following values;
Settings String: DHSG8MX6AFXCAAA2NAR2LA
Seed: 80EB35014J
Player Count: 3/Player ID: 1-3
2. Open a room in lua console, in bizhawk 2.3
3. Have other players join the room
4. Create your save file
5. Enter Mido's House and walk close to a chest
6. The game will crash.

**Expected behavior**
Expected outcome would be to be able to grab the chest contents

**Screenshots**
N/A at this time. I will try to reproduce this later today.

**Randomizer Version Number**
3.12.3 f.LUM

**Platform**
 - Bizhawk -- Windows -- 3 Windows Laptops

**Comment by flagrama** [comment]
And all of you are using the latest version of the multiworld script? Not the one meant for 3.0 Release, right?

**Comment by flagrama** [comment]
It isn't altered. It is the latest version of the co-op script in the repo. The latest one doesn't work with 3.0 release, and the older one meant for the 3.0 release does not work with Dev.

**Comment by CascadeHope** [comment]
If it helps... I have attached the version of the script that my friends and I use. I'm uncertain as to if it is the updated for 3.0 version or not..
[bizhawk co-op.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2753869/bizhawk.co-op.txt)

**Comment by rlbond86** [comment]
FWIW I was trying to get multiworld to work 2 weeks ago and also had this issue. Not sure of the setup anymore though. We set it up with the powershell script

**Comment by CascadeHope** [comment]
[Ocarina of Time.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2762600/Ocarina.of.Time.txt)
I have now uploaded the Ocarina of Time.lua file (converted to Text to allow attaching). Based on the fact that each of my ramcontroller files (LTTP, MZM, and OOT) are the same date/time, I'm assuming this is the default one.

**Comment by flagrama** [comment]
https://www.diffchecker.com/A5WHyxj2 You are using the 3.0 version of the script I believe. Left is your script, right is latest script from https://github.com/TestRunnerSRL/bizhawk-co-op

**Comment by CascadeHope** [comment]
Hello @flagrama, Thanks for checking on this. I will try giving this a run on the weekend, to see if this fixes the problem.

I'm not certain who this part should be directed to, but is it possible to suggest a version number be added as a comment at the top of the files in future iterations? Not necessary, but it would help for clarity.

**Comment by DatXFire** [comment]
Going forward you will now receive a warning about an incompatible multiworld script as of this commit: 
https://github.com/TestRunnerSRL/bizhawk-co-op/commit/6f7bd06dc28d32e8d191d3f4c11585644814c6ba
