### ISSUE TITLE
Free scarecrow on, even when disabled

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#475]
Fig Today at 2:26 PM
there are reports of the scarecrow instantly popping up when youre in range even with fast scarecrow off
going to test myself in a bit

Fig Today at 2:39 PM
yeah, confirmed that free scarecrow is on even when disabled

FigToday at 2:41 PM
rather, you still need to learn the song when its off but he will pop up automatically

**Comment by TestRunnerSRL** [comment]
Fixed in 3.13.9
