### ISSUE TITLE
Chest Game Crash

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#484]
Ouichemaster Today at 1:32 PM
3.13.18 crashes when I try to open the 1st locked door in the treasure chest minigame
(on retroarch, I haven't tested on other emulators)
tried twice on the same seed, crashed twice

**Comment by r0bd0g** [comment]
Also applies to playing Bombchu Bowling for anything other than the two prizes (?).

**Comment by shoover56** [comment]
Following up on what @r0bd0g said.

RandoVersion: Oot Randomizer 3.13.18 f.LUM
Bizhawk Version: Version 2.2.2 (x64) (GIT release #218d75c)
Settings String: BRWY2DA29XMBAWAASASFBXCMA
Seed: 011920191
OS: Windows 10 x64

Filename: OoT_EF034_011920191

OoT Randomizer Version 3.13.18 f.LUM - Cosmetics Log

Default Targeting Option: switch
Background Music: off
Display D-Pad HUD: True

Colors:

Kokiri Tunic: Completely Random (#E8C954)
Goron Tunic: Completely Random (#C071AA)
Zora Tunic: Completely Random (#46FD66)
Navi Idle: Completely Random (#E53465)
Navi Targeting Enemy: Completely Random (#CB8B27)
Navi Targeting NPC: Completely Random (#CF962A)
Navi Targeting Prop: Completely Random (#36D7FD)
Inner Initial Sword Trail: Rainbow (#36D7FD)
Outer Initial Sword Trail: Rainbow (#36D7FD)
Sword Trail Duration: 15

SFX:

Navi - Overworld: cluck
Navi - Enemy: bark
Low Health: silver-rupee
Menu Cursor: gunshot
Menu Select: goron-wake
Nightfall: talon-hmm
Horse Neigh: child-owo
Hover Boots: ruto-lift
Ocarina: whistle

On the 3rd straight reward of bombchu bowling, on Bizhawk, this is the screen that shows

image

Crashes and the usual deletes the save file on reopen.

**Comment by TestRunnerSRL** [comment]
I believe this should be fixed now in 3.13.21, but should verify

**Comment by shoover56** [comment]
I did a new seed with similar settings on what I commented on except on 3.13.21 and both the bombchu 3rd reward reveal and 1st chest in mini-game did NOT crash.
