### ISSUE TITLE
N64 Crash after king dodongo

### ISSUE THREAD

**Issue by sorokya** [TestRunnerSRL/OoT-Randomizer#488]
**Describe the bug**
Game crashes after defeating king dodongo

**To Reproduce**
Defeat king dodongo. A few seconds into the cutscene the game crashes.

**Screenshots**
https://imgur.com/a/mHNbKDN

**Randomizer Version Numer**
3.13.18 f.LUM
Dev branch
Commit 546e23966fa88d883971e13f881d181b135ac73d

**Platform**
 - Game N64 Everdrive
 - Randomizer Linux

**Additional context**
I was adult link
It was the first dungeon cleared on on the seed

**Comment by fig02** [comment]
This version has an issue with item models. Wouldn't be suprised if its related to the heart container model. A fix is waiting to be merged in.

3.13.17 is the latest stable release

**Comment by sorokya** [comment]
Seed HUCYGO2U5C
Settings BMPU2DA2PYMBJSAA2ATBL5FGAEBYJLC

@fig02 Thanks, I made a new rom with version 3.13.17 to see how that works out :)

**Comment by TestRunnerSRL** [comment]
I think this is fixed in 3.13.21 if someone can verify
