### ISSUE TITLE
Unplayable seed without use of Bombchus (unset in logic)

### ISSUE THREAD

**Issue by rchrm5** [TestRunnerSRL/OoT-Randomizer#49]
[OoT_RH6ZM4CAECUB_3UXS5RELTO_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2299821/OoT_RH6ZM4CAECUB_3UXS5RELTO_Spoiler.txt)
See the attached spoiler log. Although Bombchus are not set to affect logic, they are required to get the GS tokens in branch 5 needed for the Megaton Hammer.

**Comment by TestRunnerSRL** [comment]
Closing because the spoiler log issue is a duplicate of #23
