### ISSUE TITLE
Game crash when attempting to pick up a non-disappearing recovery heart

### ISSUE THREAD

**Issue by SpekkioKilwala** [TestRunnerSRL/OoT-Randomizer#490]
When I attempt to grab a non-disappearing recovery heart (e.g. the ones of the roofs of kokiri village or left behind by the first Scrub in Deku Tree) the game crashes - time halts, no inputs seem to work, but background noises continue.

Expected behaviour is for Link to recover one heart of health without exceeding his maximum and for the "bloop" noise to play.

Randomiser version number 3.13.20 f.LUM on Windows. I am using Retroarch.
Settings: BREGKRA2ZCYCDAS2ATKV5FAETNULC
Seed: 334523487

Additional context: I turned up the randomisation quite high on this one. Random colours, random noises, random text.

**Comment by TestRunnerSRL** [comment]
Should be fixed now 3.13.21
