### ISSUE TITLE
Ocarina + Ladder softlock

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#491]
Hamsda:
@krimtonz so I found a way to softlock with the dpad ocarina, basically the usual ladder + cutscene softlock
https://clips.twitch.tv/PrettiestEphemeralBaconTwitchRaid

--

It seems the ocarina does not grey out like the other items do while climbing a ladder, regardless of whether or not Link is swordless.

**Comment by shoover56** [comment]
This has also been present since at least 3.13.16, probably as early as when d-pad ocarina existed, so this bug wasn't introduced after allowing d-pad ocarina.

**Comment by flagrama** [comment]
Yeah, it's just an oversight of where D-pad ocarina is allowed. Boots had a lot of them when they first were put in too.

**Comment by KyuuGryphon** [comment]
I don't think this is completely fixed, though it might be a different, related bug. I know I'm slightly out-of-date here, as this is on 3.14.23, but I managed to softlock by using the Ocarina at the edge of the Death Mountain cliff:
![image](https://user-images.githubusercontent.com/2258511/51886167-7b4dfb80-2343-11e9-9b61-c68a74d82474.png)
Figured it was at least worth mentioning, just in case.

**Comment by r0bd0g** [comment]
Confirmed.

**Comment by krimtonz** [comment]
I can't seem to recreate this :/

**Comment by r0bd0g** [comment]
I thought it happened the first time I tried it but I couldn't get it again so now I'm not sure if I wasn't just dumb and pressing the wrong button to try and cancel ocarina. (That's not what's happening here; the hud is showing your item buttons and such...)

**Comment by KyuuGryphon** [comment]
Yeah, I've tried recreating it myself, but I couldn't seem to get it to happen... Might be worth noting that immediately before this, I went into the fairy fountain to play ZL, then paused to check my tracker on getting outside, before running to the edge of the cliff and pulling out the ocarina. I'll do some more testing with this a bit earlier, to see if I can reproduce it reliably (if at all).
