### ISSUE TITLE
Shop text shuffles

### ISSUE THREAD

**Issue by phixtyseven** [TestRunnerSRL/OoT-Randomizer#492]
**Description**
Shop text is shuffled with "Text Shuffle: All Text Shuffled".

As consequence of this:
* The appropriate price of items isn't always displayed
* It's impossible to detect whether an item is an ice trap (I think so, anyway)
* Shop items can end up having more than one text item when you move the cursor over a shop item.

**Randomizer Version**
3.13.20 f.LUM

**Opinion**
Shop text should never change, it's too janky for any setting to allow. Never offer the user bad options.

**Comment by r0bd0g** [comment]
There's an option to shuffle most text, between shuffling no text and shuffling all text. It mostly solves issues 1 and 2.

**Comment by TestRunnerSRL** [comment]
People like playing all text shuffled because they want to have a bad time. This working as intended.

**Comment by XVII** [comment]
It'd be cool if this could be revisited at some stage! 
I like randomised text for the fun, not for the bad QoL. 

Of particular annoyance:

1. Shop prices
2. The multi-text per shop item is just pure jank

**Comment by flagrama** [comment]
IMO If you use All Shuffle for text, then there isn't anything to do. That's what _all_ shuffle means. If you play with "Shuffle Text: Except Hints" and have these issues, or have an idea for another option for the list, that's different.

**Comment by XVII** [comment]
@flagrama , I use "Shuffled except Important Text" for this reason. 

I would consider shop prices and info "important text" (especially if prices are random as well), otherwise you're just guessing blind. That's where it starts to become less fun and more of a frustration.

But otherwise, this level would be somewhere between "No Text Shuffled" and "Shuffled except Important Text" if it demanded it's own level (vs just making the shop text considered "important").

The shop menu text (navigation) is tolerable, if you've memorised what the options are from vanilla, and understand the quirks of multiline textboxes.

**Comment by flagrama** [comment]
Okay. This issue is about "All Text Shuffled" though. If you have issues with "Shuffled except Important Text" you should create a new issue explaining what important text is missing.

**Comment by XVII** [comment]
> Okay. This issue is about "All Text Shuffled" though. If you have issues with "Shuffled except Important Text" you should create a new issue explaining what important text is missing.

I assume that's because it was a few years old and the name probably changed. I can create a new one, just didn't want to create dupes. The feature name has changed since v3.0 so can create a new one 👍 

Added #2425

**Comment by flagrama** [comment]
>  it was a few years old and the name probably changed. 

> The feature name has changed since v3.0 so can create a new one

"All Text Shuffled" and "Shuffled except Important Text" are two separate features. This report was about "All Text Shuffled" which is very much still named that.

**Comment by XVII** [comment]
> > it was a few years old and the name probably changed.
> 
> > The feature name has changed since v3.0 so can create a new one
> 
> "All Text Shuffled" and "Shuffled except Important Text" are two separate features. This report was about "All Text Shuffled" which is very much still named that.

Oh right, I see what you're talking about now. Well #2425 is there, so hopefully that covers that off. Thanks!
