### ISSUE TITLE
Using Ocarina on D-Pad while on ladder hardlocks the game.

### ISSUE THREAD

**Issue by shoover56** [TestRunnerSRL/OoT-Randomizer#494]
Version: 3.13.21
Emulator: Bizhawk 2.2.2

I think this is exactly like how climbing a ladder during a cutscene locks the game, but you can attempt to play an ocarina with d-pad down while on a ladder. While it doesn't work right away, finishing the ladder or jumping down will cause link to hard lock in place.

This was also present in version 3.13.16, probably since d-pad items existed for ocarina.

![image](https://user-images.githubusercontent.com/4006604/51443838-83a79600-1cb4-11e9-96f4-65b2921ec38d.png)

**Comment by Cuphat** [comment]
Duplicate of #491.

**Comment by shoover56** [comment]
Oh wow this is what I get for not refreshing github after having it opened yesterday. Sorry. Closing.
