### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by williamXgray** [TestRunnerSRL/OoT-Randomizer#50]
I am a Mac user and when I try to make generate a patched rom it says "Error: can only concatenate str (not SSLCertVerificationError") to str

**Comment by GB-CG** [comment]
In the Python folder under `Applications` you'll see a `Install Certificates.command` double click that.

**Comment by SmashManiac** [comment]
Why would an offline randomizer attempt to validate an SSL certificate in the first place?

**Comment by TestRunnerSRL** [comment]
There is a version check added to let you know if an update is available. I wasn't aware Mac needs to take extra steps to use SSL. It at least should not crash anymore, and just give you a warning. 97b82fd9f438cbc1a56e2738775f2b70fbe5cd63

**Comment by TestRunnerSRL** [comment]
We're planning on not having multiplatform support for 4.0 in favor of the webpatcher, so this issue is no longer applicable
