### ISSUE TITLE
UX: Creating files can overwrite previous files without any confirmation

### ISSUE THREAD

**Issue by phixtyseven** [TestRunnerSRL/OoT-Randomizer#502]
**To Reproduce**
Generate a ROM with a custom seed. After it generates, create another one with the same seed/string. The previous ROM will be overwritten.

**Expected behavior**
A little dialog box should appear upon clicking "Generate", with the option to overwrite the old file or create a new one.

**Randomizer Version**
3.14.2

**Additional context**
I'm not as worried about the CLI having the same behavior, as it's more for scripting. Though if someone happens to change it, please also provide an -f/--force option to clobber files.

**Comment by mzxrules** [comment]
I don't think it's a huge problem since the default installation sets the output directory in an empty folder. It'd also bug me because then I'd have to learn how to use the cli to avoid the overwrite prompt

**Comment by TestRunnerSRL** [comment]
Wouldn't this generally just replace the rom with the same rom? Even if you use the same seed/settings on a different version, it will hash differently and be a different rom, right?

**Comment by KevinPal** [comment]
You can use the same settings/seed but different cosmetics and it would override it.

**Comment by TestRunnerSRL** [comment]
I suppose? Still not sure this is something I would want. I frequently want to generate the same seed with asm changes and getting a prompt every time would be really annoying. Also since we're pushing for having users use the webpatcher in the future anyways, it's a pretty non-issue there.
