### ISSUE TITLE
Exclusion for Stone of Agony from major items for barren areas coded backwards?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#512]
It seems to only get excluded if hints are set to stone, but it should be the opposite.

**Comment by flagrama** [comment]
Actually I think it should just be more accurate to always have it excluded. It makes no sense on any other hint setting to be a major item in a hint, **and** it makes no sense on agony hints because you need it before actually reading the hints.

**Comment by Cuphat** [comment]
If you excluded it always, you'd also need to exclude it from Way of the Hero or else you open the possibility of an area being both at once.

**Comment by TestRunnerSRL** [comment]
hints can't be self locking
