### ISSUE TITLE
Sequence Breaks with Chest Size Matches Contents

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#520]
Apparently if you get a large chest for the goron city left boulder maze chest, you can jump off it to reach the leftmost maze chest without hammer, strength 2, or hover boots. There may be other cases where sequence breaks like these shouldn't be possible, but are.

**Comment by r0bd0g** [comment]
I'm gonna have to think about this and try to figure out what all chests I need to do tests with...

**Comment by mzxrules** [comment]
at this point i feel like we should get rid of the option in favor of using a different texture for "large" chests

**Comment by r0bd0g** [comment]
One idea I guess is to repurpose the gold chests from having only keys, to all major items?

**Comment by shoover56** [comment]
Kinda sorta the reverse of this, but another example of big vs small chest that need clarification on in logic.

In Spirit Temple Adult Side, the chest that requires you to play Zelda's Lullaby on the 1st flow with the Wolfos can be hookshotable (no long shot required) from the sinking sand, bypassing the hoverboots/longshot requirement.

However if "Chest Size Matches Contents" is on and that chest turns into a small one, it's not possible to hookshot it from the sand.

**Comment by r0bd0g** [comment]
@shoover56 What version of the randomizer was this?

**Comment by shoover56** [comment]
@r0bd0g Oh this happened many months ago. It was a 3.1x dev version. Apologies I couldn't be any more specific.

**Comment by TestRunnerSRL** [comment]
That was fixed

**Comment by rlbond86** [comment]
Seems like a similar fix could be applied to the Goron city chest, just move it into the corner or something. Personally I like Chest Size Matches Contents, it makes the game feel closer to the original somehow?

**Comment by TestRunnerSRL** [comment]
Another solution is make it so that you can't get on top of the chest, like an invisible wall or something. Moving the chest might need to be moved by too much, also hover boots.

**Comment by r0bd0g** [comment]
Invisible wall might interfere with the actual trick to get back there, using hover boots.

**Comment by TestRunnerSRL** [comment]
Well i'm unsure how much the chest needs to be moved to resolve the problem. like does it need to be moved a little, or like swap it's position with the gossip stone?

**Comment by r0bd0g** [comment]
I doubt anybody knows the answer to that. If you can do a hover boots backflip from the chest and you'd rather that not be possible even though from the crate works, the chest probably has to go all the way to the wall.

**Comment by mzxrules** [comment]
not very. in vanilla, it was configured on a per-item basis, stored in the sign bit of the get item model id

**Comment by rlbond86** [comment]
How would the animation work with child link? He literally hops up and leans over the edge of the chest...

**Comment by TestRunnerSRL** [comment]
wait if you don't want to be able to hover from on top of the chest, what's the problem with preventing link from getting on top of the chest again?

**Comment by r0bd0g** [comment]
I worry that if you add some invisible wall, it could get in the way of the normal sequence break that you'd do.

**Comment by mzxrules** [comment]
with dotzo's help i implemented my suggested fix of changing the texture of the chest over having the sizes changed (#542), which also fixes the issue of chests obstructing the player's view on certain pre-rendered maps. the problem now is that Testrunner refuses to pull it

**Comment by rlbond86** [comment]
That PR seems like way overkill. You want to remove an entire feature because of a sequence break? When the Spirit Temple chest issue was found, the solution was to move the chest slightly, not to take out a very popular feature.

**Comment by r0bd0g** [comment]
It's the same feature?
The difference I guess is if you put on slow animations, you don't get the full sfx if you go small chest with major item. Are there other differences?

**Comment by mzxrules** [comment]
isn't the whole point of the feature being able to read into the contents of the chest? this accomplishes that without changing vanilla gameplay

**Comment by TestRunnerSRL** [comment]
Why is this exact conversation happening again with the same people.

**Comment by rlbond86** [comment]
The point of the feature is that in Zelda big chests have good stuff

**Comment by mzxrules** [comment]
well then the point of this feature is to remove jank from the rando code and make it easier to do cool shit in the future

**Comment by Squidkingdom** [comment]
Honestly I think that if people don't want it to be used in their playthrough's then they don't have to use it. Tournaments can ban the practice, and personaly playthroughs can just agree not to. By adding a invisible wall we start to interfere with no im/ww tournament/playthroughs. Good ol make a bug a feature.

**Comment by r0bd0g** [comment]
Apparently you can skip the hookshot when getting through Shadow if the invisible spikes room has a big chest.
