### ISSUE TITLE
Why does Ganondorf tell you about the item in his tower?

### ISSUE THREAD

**Issue by pkmnfrk** [TestRunnerSRL/OoT-Randomizer#534]
I might be remembering wrong, but didn't he tell you where the Light Arrows were at one point? I feel like this would be much more useful than the contents of the boss chest, which the player either opened ~60 seconds ago, or skipped because they know they don't care about it.

Or, does it have something to do with my settings? Sample: BVTC4HCJKFFDJRSRSS2SATJTSTAAAJGBFKLA

**Comment by LostThePirate** [comment]
If you have Trials set to >0, he will tell you what is in the Boss Key chest. If you have Trails set to 0, he will tell you where LAs are.

**Comment by pkmnfrk** [comment]
Oh, I guess it makes sense that he doesn't tell you about the light arrows if you must have them by definition. Didn't think about that.

I wonder, though, if there's anything else he could say other than the boss chest, though. Maybe the 100 Skultula reward, once they implement #422 

What? That's never, ever going to happen for any reason? Pah, fine.
