### ISSUE TITLE
Can buy Bombchu's with only Bomb Bag (no Bombchu's previously acquired)

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#540]
Version: 4.0 (download)
Seed: CVVIXJB7R2
Settings: BZPG2VT2RJFHAAAKTBCMV5EAETNSLA
File Select Hash: Mask of Truth | Deku Nut | SOLD OUT | Mask of Truth | Stone of Agony

Shopsanity disabled.
Bombchus are considered in Logic.

Find a Bomb Bag and you can now buy Bombchu's from any shop such as Kokiri shops top-left corner item for example. No need to find Bombchu's prior to purchase.

There's been 3 separate reports on Discord of this happening (including my report). TippyCow#2376 reported it first, I confirmed it and then Ketris#9035 discerned it may have also happened to him.

**Comment by r0bd0g** [comment]
This was working before... Must have broken somehow?

**Comment by r0bd0g** [comment]
Can you still buy chus if you don't have a bomb bag, only chus in the inventory? If not then all chus in logic seeds are potentially busted. What about bombchu bowling, what lets you play that?

**Comment by r0bd0g** [comment]
Alright, after some testing it sounded like the only problem was that, with chus in logic, it let you buy chus if you have a bomb bag. It lets you buy if you have chus as well. The only problem is that one case of letting you buy when it shouldn't... Maybe?

**Comment by Nicholas-Steel** [comment]
Your last message sounds about right.

**Comment by r0bd0g** [comment]
It works correctly in 3.0 apparently.

**Comment by Cuphat** [comment]
In 3.0 this was handled by Patches.py. In 4.0, it's handled by chus_in_logic.asm. The refactor to put it into the ASM just overlooked a small thing, so if the check for bombchus fails, it is currently falling back to the bomb bag check before failing.
