### ISSUE TITLE
Make DM Trail Freestanding PoH Without Bean Optional

### ISSUE THREAD

**Issue by ruqrourou** [TestRunnerSRL/OoT-Randomizer#543]
The way(s) to get the item above Dodongo's Cavern (called "DM Trail Freestanding PoH" in the spoiler log) without using the bean are not trivial/obvious for beginners. There should be a way to guarantee that a seed will not require these tricks for this item location.

**Comment by goldencow2** [comment]
This is hardly obscure compared to other things the rando expects you to do and any piece of heart walkthrough on the internet will tell you how to get it this way. The trick itself is also not difficult at all. If a new player -really- can't figure it out, then they can learn how to do it easily after checking the spoiler log and seeing that the rando wants them to.

**Comment by darkangel93x** [comment]
dont get this wrong, i see what you mean but i figured this out myself with 8 fucking years. its not that hard to try :)

**Comment by r0bd0g** [comment]
I definitely did not use a bean to get this as a kid. I doubt many did??

**Comment by dstruct2k** [comment]
Even as a child I knew to jump over the tiny-ass fence up top. Never have I used a bean...

**Comment by TestRunnerSRL** [comment]
This could potentially be an added trick, but this is something that is fairly easy to see as possible without guidance and not too hard to execute. My general rule of thumb is that if you can figure out how to do something without being told how to do it, then it's probably fine.
