### ISSUE TITLE
"Stonesanity"/"Medallionsanity"

### ISSUE THREAD

**Issue by reddipper** [TestRunnerSRL/OoT-Randomizer#544]
An option to randomize the location of Spiritual Stones/Sage Medallions along with everything else. The main implication of this that separates it from Vanilla Requirements/All Spiritual Stones/All Medallions/All Dungeons is that you would not necessarily be required to explore temples/beat the bosses in the temples.

One of the major complaints about randomizing items seems to be that it would require "looking for a certain amount of random locations". At first glance, this makes sense, except that "looking for a certain amount of random locations" already exists with Keysanity, since you'd need to find the random locations of the 6 boss keys, or alternatively know how to skip all of them). In fact, randomizing these 9 items would probably result in _less_ time spent looking for random items in Keysanity, as the items in temples tend to require many more items (mainly, keys) than items outside the dungeons.

**Comment by krimtonz** [comment]
This is being planned/worked on as a "triforce hunt"  The stones/medallions themselves won't be randomized rather a new item called triforce pieces will be added to the item pool and when you collect all of them the game is beaten.

**Comment by flagrama** [comment]
https://github.com/TestRunnerSRL/OoT-Randomizer/issues/229

**Comment by reddipper** [comment]
@krimtonz That seems a little excessive. I would think it would be much simpler (AFAICT), and more faithful to the original game just to randomize the stones/medallions. In addition, you would still be required to beat the game, unlike this "triforce hunt" you've mentioned.

**Comment by flagrama** [comment]
![image](https://user-images.githubusercontent.com/634079/52729563-67cba300-2f87-11e9-98ea-9a3a3b44ce1b.png)

**Comment by reddipper** [comment]
is there something about the medallions/stones that make them hard to randomize?

**Comment by flagrama** [comment]
Compared to "Create simple model with dlists, add variable counting how many you have found, end game when `n` have been found," yes.

Some current examples:
![image](https://user-images.githubusercontent.com/634079/52730037-76668a00-2f88-11e9-939d-495a69fd0c54.png)
and the medallion thing: https://github.com/TestRunnerSRL/OoT-Randomizer/issues/265

**Comment by krimtonz** [comment]
Giving the medallions themselves would probably not be difficult. Preventing them from the original locations would be the difficult part.

**Comment by Nicholas-Steel** [comment]
I like the idea of a Triforce Hunt where you still have to defeat Ganon after getting the pieces... aka: Instead of Link starting with the Triforce of courage he now has to find it before facing the big baddie.

**Comment by TestRunnerSRL** [comment]
As mentioned would rather have a triforce hunt. Does the same thing and it much easier to implement. I'd rather warp to credits tbh, since then you don't need a bunch of items to clear GT, but that's a separate discussion.
