### ISSUE TITLE
Rainbow Bridge Requirement: X Gold Skulltulas

### ISSUE THREAD

**Issue by reddipper** [TestRunnerSRL/OoT-Randomizer#545]
Instead of the Rainbow Bridge Requirement in the randomizer for Skulltulas being 100, make a slider or input box to choose how many Skulltula tokens should be required. An option for a random number of Skulltula tokens between a minimum and a maximum could additionally be added.

**Comment by flagrama** [comment]
100 Gold Skulls is basically a meme option that was added partly because people were always asking for 100 Skulltula item to be changed to an item location instead of a flat 200 rupees every time you talk to the guy. It wasn't even properly or fully tested to work with other options to be honest. Don't even know how many people actually use it.

**Comment by reddipper** [comment]
100 Skulltulas right now is essentially a randomized 100%, as you're extremely unlikely to find every token until you have only a handful of items left. With 80 required, for example, you just have to find most of them, which is far more flexible, and forgiving for the player.

**Comment by BladefangFT** [comment]
Yes, the "essentially a randomized 100%" was kind of the point.

**Comment by Cuphat** [comment]
Honestly, changing this wouldn't be that hard, but I'm not sure it's worth adding? It'd be weird to have one bridge option have an extra option just for it.

On the other hand, it's not exactly the worst idea, and could be somewhat interesting the play with.

On the other other hand, it's basically a poor man's Triforce Hunt at that point, except with the added flexibility of not using tokensanity.

**Comment by TestRunnerSRL** [comment]
This sounds like it would be a highly unused feature that would add a bunch of options. At best, an option to specific custom bridge requirements might be ok, but I think various GS counts is not really worth cluttering the UI with.
