### ISSUE TITLE
Epona becomes locked after... something happens

### ISSUE THREAD

**Issue by pkmnfrk** [TestRunnerSRL/OoT-Randomizer#55]
Sorry that this is very vague, but I'm not 100% sure on the circumstances that led to it.

Basically, I had a seed where Skip Epona Race was set. Early on, I summoned Epona and used her to cross the canyon, and then left her there. Sometime later, I tried to summon Epona, but it didn't work. I then had to go to Lon Lon Ranch and race Ingo to unlock Epona permanently.

I was not paying a lot of attention in the middle, and I did a lot of stuff in the middle, so I have no idea what might have changed in the middle.

Here's the spoiler log: [OoT_ZJ6994C2DA4B_V8N1F1F15M_Spoiler.txt](https://gist.github.com/pkmnfrk/db8bd8cf24814a7139fe0a950a77cd3b)

**Comment by flagrama** [comment]
Did you happen to get Weird Egg after getting Ocarina and Epona's Song, then proceed to go check the Epona's Song check at Malon?

**Comment by pkmnfrk** [comment]
No, I didn't get the Weird Egg until very very late, well after the above events transpired.

I'm going to try another seed, and see if I can reproduce it with a bit more precision.

**Comment by flagrama** [comment]
Someone else has literally hit the same bug as you so I'm just trying to narrow down where the issue might be.

Did you receive Fairy Ocarina > Epona's Song > Ocarina of Time?

**Comment by pkmnfrk** [comment]
That order seems likely, I got the Ocarina and Epona's Song very early.

**Comment by TestRunnerSRL** [comment]
Should be fixed in 835aa1108d964ce2dc346421e430566c1a738d7d
