### ISSUE TITLE
Should "all locations reachable" respect excluded locations? 

### ISSUE THREAD

**Issue by rlbond86** [TestRunnerSRL/OoT-Randomizer#551]
I had a surprising run where the lens of truth was in an excluded location. Of course, I didn't need to do the Shadow Temple to complete the game, but this wasn't the behavior I expected,since all locations were reachable only via excluded locations. Is this the intended behavior?

**Comment by BladefangFT** [comment]
excluded locations only concerns itself with items you need by logic to beat the seed
"All Locations Reachable" has nothing to do with this.
You can still reach and complete the excluded locations, you just don't want to.

**Comment by TestRunnerSRL** [comment]
Yeah as blade said, You still have the ability to reach all locations in the game. Excluding locations just means you will never need to check those locations to beat the game.
