### ISSUE TITLE
Automatically Replace Fire Temple song in the pool

### ISSUE THREAD

**Issue by nitronova** [TestRunnerSRL/OoT-Randomizer#557]
This is a feature request/enhancement.

The backing track to the Fire Temple in the 1.0 version of Ocarina of Time makes the use of Islamic prayers as part of the song's ambience. People who practice Islam seem to have a (common?) rule within their religion that says prayers must never be set to music. The inclusion was Nintendo's cultural oversight back in the day, and it was one of the things that they patched out in a later version.

I recommend that the mod also addresses this so that Islamic players and Islamic gamers watching streams can enjoy the game without this issue. Here are two recommendations I can think of:

1. Replace the original song with the new one that removes the prayers. (default behavior)
2. Re-target the original song to another song at random for added randomness.

Before it is suggested (and I'm not saying anyone here is about to), I don't recommend an additional option for keeping the original track as is, as the point of this enhancement is to help offer a more inclusive experience. There isn't any real benefit to keeping it, is all I'm saying.

Edit: I believe Nintendo also removed some of the crescent moon symbolism in a later patch, too, but I think more people should make their input on that matter, too, as I am not of an Islamic faith.

**Comment by Nicholas-Steel** [comment]
Everybody (except islamists I suppose) like the ominous chanting more than the replacement music and the symbols are just fancy pics, don't take them away like Red Cross took the Red Cross away from medical kits in video games...

**Comment by darkangel93x** [comment]
Not only that this would be problematic due to Copyright issues, it is also kinda unnecessary. It does no harm to anyone.

**Comment by Darkchas** [comment]
> This is a feature request/enhancement.
> 
> The backing track to the Fire Temple in the 1.0 version of Ocarina of Time makes the use of Islamic prayers as part of the song's ambience. People who practice Islam seem to have a (common?) rule within their religion that says prayers must never be set to music. The inclusion was Nintendo's cultural oversight back in the day, and it was one of the things that they patched out in a later version.
> 
> I recommend that the mod also addresses this so that Islamic players and Islamic gamers watching streams can enjoy the game without this issue. Here are two recommendations I can think of:
> 
> 1. Replace the original song with the new one that removes the prayers. (default behavior)
> 2. Re-target the original song to another song at random for added randomness.
> 
> Before it is suggested (and I'm not saying anyone here is about to), I don't recommend an additional option for keeping the original track as is, as the point of this enhancement is to help offer a more inclusive experience. There isn't any real benefit to keeping it, is all I'm saying.
> 
> Edit: I believe Nintendo also removed some of the crescent moon symbolism in a later patch, too, but I think more people should make their input on that matter, too, as I am not of an Islamic faith.

Sorry but this is a randomizer for the Game Zelda OOT, Rather keep outside views like Religion OUTSIDE of the game. It has nothing to do with zelda so changes shouldn't be made to please a few players.

**Comment by LostThePirate** [comment]
I don't think this should be universally removed from the Random BGM pool, but it would be nice as a toggle to take it out of the pool if you wish to. Lots of folks enjoy the original Fire Temple music; many folks find it uncomfortable. No need to force either its presence or its absence on all players, but being able to optionally remove it from the pool would be nice.

**Comment by archmage** [comment]
Solid suggestion; making software more inclusive is objectively positive.

To the haters in this thread, please take your gatekeeping elsewhere.

**Comment by nitronova** [comment]
The main thing I want to avoid is the discussion becoming too hostile to be productive, but archmage's point in her response is something that I too believe in. We certainly can come up with a creative solution that works for just about everyone.

1. Firstly, if some players do not like the music when it doesn't have chanting, we can easily create a version of the music that includes unique, original chanting effects that everyone can enjoy.
2. If symbols were just pictures that nobody has passion for, I wouldn't be opening this issue in the first place.
3. People will have to explain to me why merging in Master Quest levels into the original game's ROM is not infringing copyright but replacing music is.
4. As I explained in the original issue, it isn't me that is bringing religion into the game, it was Nintendo. And they themselves made the choice to remove the offending content in a subsequent version. Was that not noble of them? Isn't it the right thing to do to respect cultures even when we aren't familiar with them and don't know as much about them?
5. As the original post stated, a toggle option would mean that Islamic viewers would have no idea whether the stream they would be watching would contain the offending content or not, and would defeat the purpose of this modification (to create a more inclusive experience).

The majority of these points were answered in the original post, but I have either repeated or further detailed my reasoning, here. I'm standing by my issue and consider it an improvement to the software.

**Comment by earfolds** [comment]
Just for the record, most muslims couldn't care less about the music in the game. The calls in the Fire Temple theme aren't actually from a prayer at all, and the crescent moon symbol is actually a symbol of the Ottoman Empire, not of Islam.

I commend your efforts to be more inclusive, but this seems to stem from popular misconceptions about Islam.

**Comment by LostThePirate** [comment]
Again, this supports the option of including a toggle. If you dig around way back when I'm the Discord, you can find me making this suggestion as far back as ~July~. I don't think it needs to be completely removed - many folks enjoy the original Fire Temple accompanyment - however, including it as an optional toggle for those who desire it would be a nice addition. I am not Muslim, and will not pretend to speak for "most Muslims" (I'm pretty sure there are over a billion, I doubt there's much that ~all~ of them have in common), but being able to make my Twitch channel a cozier space for folks of all faiths is something I would appreciate. However, many folks like to play solo, and if they aren't offended and there isn't anyone else around to be offended, I don't see cause to remove something that those players enjoy. Thus, toggle.

**Comment by nitronova** [comment]
@earfolds It is in fact from an Islamic prayer. This has been fact for years.
[Source 1](https://zelda.gamepedia.com/Controversy_in_The_Legend_of_Zelda_Series#Religious_content_and_censorship)
[Source 2](https://www.zeldadungeon.net/nintendo-officially-talks-about-the-infamous-ocarina-of-time-fire-temple-ch/) - Here it shows that Nintendo accidentally included it because they used an open sound library.

The Ottoman Empire part is true, but then again [that makes it, by popular extension, an emblem of the Islamic world](https://en.wikipedia.org/wiki/Star_and_crescent), as it says here in the very first sentence. I was not originally advocating its removal without insight, but I'm also for replacing that imagery for two reasons:

1. Nintendo's policy is against real-life religious inclusions, so it is a matter of respect towards Nintendo to play a version that approaches their intended experience.
2. Utilizing the religious symbol would be an example of [cultural appropriation](https://en.wikipedia.org/wiki/Cultural_appropriation). The case being that the Gerudos pretty squarely and neatly fit the tropes of exoticism ("they're very different, very isolated, very resistant to outsiders, etc"). So it is perhaps inappropriate to use that imagery and to opt for an original design, instead.

@darkangel93x I have music production skills and could provide something.

**Comment by earfolds** [comment]
> @earfolds It is in fact from an Islamic prayer. This has been fact for years.
> [Source 1](https://zelda.gamepedia.com/Controversy_in_The_Legend_of_Zelda_Series#Religious_content_and_censorship)
> [Source 2](https://www.zeldadungeon.net/nintendo-officially-talks-about-the-infamous-ocarina-of-time-fire-temple-ch/) - Here it shows that Nintendo accidentally included it because they used an open sound library.
> 

It's not from an islamic prayer. I've attended many islamic prayers in my life, and it isn't an islamic prayer. The first source you gave has no sources, and the second refers to an open sound library that features a devotional song where they sing "There is no god but Allah, Allah is great." These words have been in many songs over the years, in a genre known as qawwali, which is enjoyed by muslims and others the world over. Qawwali is a form of devotional singing that has been around for over 700 years. I can say with good authority that the inclusion in the Fire Temple theme is fine. You don't need to worry.

I understand you are trying to be helpful to muslims, but your facts are wrong, so you are being unhelpful.

**Comment by nitronova** [comment]
I see. Thank you for this information and your input.
