### ISSUE TITLE
Impossible run (circular dependencies)

### ISSUE THREAD

**Issue by archmage** [TestRunnerSRL/OoT-Randomizer#56]
Hi all,

I got a seed that I believe has a circular dependency - I'll attach the spoiler and post the relevant parts. It was generated with version 2.15.34 f.LUM.

[OoT_9A9B7RWBHASNA_7WGGWY2X8R_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2305600/OoT_9A9B7RWBHASNA_7WGGWY2X8R_Spoiler.txt)

```
Gerudo Training Grounds Stalfos Chest: Iron Boots
Shadow Temple Hidden Floormaster Chest: Gerudo Membership Card
Mountain Storms Grotto Chest: Nocturne of Shadow
Lake Hylia Sun: Song of Storms
```

1) Iron Boots require Gerudo Card.
2) Gerudo Card requires Nocturne of Shadow.
3) Nocturne of Shadow requires Song of Storms.
4) Song of Storms requires Iron Boots.

I did check to make sure that I couldn't get to Lake Hylia Sun; I used the Longshot and Scarecrow Song to get to the platform, but there was no chest and I couldn't shoot the sun to make the chest appear as normal.

If this is due to a misplay or lack of knowledge on my behalf, I would very much like to know what I could do to break this dependency loop.

**Comment by emerald000** [comment]
You have to shoot the sun early in the day. You do not have to beat Water Temple. Easiest way is to use Sun's Song to put you at the correct time, but you might have to wait if you do not have it.

**Comment by fraggerman91** [comment]
Lake Hylia Sun does not require Iron Boots as far as I know. You just shoot the morning sun to make the chest appear and hookshot over to the scarecrow like you did already. It HAS to be very early morning to trigger the chest appearance. Just chill a night there and shoot the sun just as it comes up.

**Comment by archmage** [comment]
Huh, I guess I didn't shoot early enough. Sorry!

In hindsight it would've likely been better to check this on the Discord or something, heh heh.
