### ISSUE TITLE
Error: 'WorldDistribution' object has no attribute 'get_starting_item'

### ISSUE THREAD

**Issue by Zombrya** [TestRunnerSRL/OoT-Randomizer#573]
When trying to make a multiworld seed using setting string 74ESZLSAXW4AFCGCRCSCNWAADAEVURSFA

Error: 'WorldDistribution' object has no attribute 'get_starting_item'

![error1](https://user-images.githubusercontent.com/48075784/53536251-9d1dd800-3ad3-11e9-8e3e-e7483ad7466b.JPG)
![error2](https://user-images.githubusercontent.com/48075784/53536250-9d1dd800-3ad3-11e9-8829-f0dde82460ae.JPG)

**Comment by Ketris** [comment]
That means you have it trying to load a distribution list (for plando) but not providing a list. Reset your preset to Default and then re-customize.

**Comment by TestRunnerSRL** [comment]
This was fixed
