### ISSUE TITLE
Compress32.exe does not function on 32-bit systems

### ISSUE THREAD

**Issue by dotzo** [TestRunnerSRL/OoT-Randomizer#58]
Raizuto_Gaming in the discord had someone test the compressor on a 32 bit system. Circumvented checking by deleting the default and renaming the 32 bit to no avail.

**Comment by TestRunnerSRL** [comment]
So the check is OS version correctly working, but the 32 bit compressor doesn't work? Do you happen to know the trace/error message?

**Comment by dotzo** [comment]
I don't. I asked if they'd taken the preliminary steps to isolate the problem to make sure it was an actual bug with the compressor, but didn't think to ask about if they'd tried to get a traceback.  I'd test myself, but I don't have access to a 32-bit machine.

**Comment by TestRunnerSRL** [comment]
Well GrantMan is the one who wrote the compressor and I wrote the version check, but I don't really have a 32-bit system to test with. If they can do some further testing that would be very useful. Maybe putting in some print statements in the version check in main.py to see if it's following the correct branch.

**Comment by TestRunnerSRL** [comment]
Hopefully this fixed the issue. Would they be able to verify this fixes their issue?
