### ISSUE TITLE
"No nighttime Skulltulas without Sun Song" tooltip typo

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#59]
"No nighttime Skulltulas without Sun Song" options tooltip contains an erroneous "because needed" in it.

**Comment by StenAtBigSkyResort** [comment]
![image](https://user-images.githubusercontent.com/31937063/44671266-4d563b00-a9e2-11e8-99a8-b257151772d2.png)

**Comment by TestRunnerSRL** [comment]
Fixed in 38bd4a6f4009cc36c7f31079335638197d245d77
