### ISSUE TITLE
Unfinishable Seed (MZ0ENWQENA) with Settings: 9Q5X7ZYBA9MAA

### ISSUE THREAD

**Issue by EvilApple567** [TestRunnerSRL/OoT-Randomizer#60]
[OoT_9Q5X7ZYBA9MAA_MZ0ENWQENA_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2325286/OoT_9Q5X7ZYBA9MAA_MZ0ENWQENA_Spoiler.txt)

I've checked what I believe to be every advancement item/condition and found nothing workable under normal play circumstances, unless there's some way to reach the top of DM Crater as child without explosives. Perhaps the logic confused Iron Boots with Hover Boots? I really don't know, just spitballing like a dunce here, but I'm pretty sure this seed in broken.

The playthrough logic seems to be broken in consecutive steps. 3 requires explosives, scales, or Hover Boots for ZD entry, and 4 requires Hookshot for Scarecrow or explosives for magic beans for use of Step 3 item (LoT) to accomplish Step 5.

**Comment by flagrama** [comment]
Playthrough is known to skip required items. It is an issue that will probably be addressed at a later date. So aside from that, are there explosives or other items available to you that the playthough skipped over?

**Comment by fraggerman91** [comment]
Well you could do the chest game to get an ocarina and use that for the memory game to get bombchus. You only require lens for wasteland in your settings so you dug your own grave here.

**Comment by fraggerman91** [comment]
Remote Southern Grotto Chest: Bomb Bag

Not sure if that is the open grotto besides the gate to Hylia Lake but there would be bombs.

**Comment by flagrama** [comment]
I believe Remote Southern Grotto is the one with a rock above it.
`Field Near Lake Outside Fence Grotto Chest: Gold Skulltulla Token`
`Deku Salesman Hyrule Field Grotto: Map (Shadow Temple)`
Are the Hylia ones.

**Comment by EvilApple567** [comment]
I looked for Bombchus, Bomb bags, Fire Arrow, Hammer, Ocarinas, Hookshots, Boomerang, Hover Boots, Scales, Strength Upgrades, Bottles, Din's Fire, and everything else I could think of that could be used to get any new GS (even Nightime ones not set in logic w/out Sun Song + Ocarina) or pickups and found nothing I could reach. Pretty sure I combed this one as thoroughly as possible.

fraggerman91 is correct in that I technically could have done the 1 in 32 chest game to get the Ocarina, but that obviously would be a flaw in the logic and would still warrant an issue thread. Also just to answer his comment there's really no point in doing that or continuing at all at this point since I've had to spoil the pickups and all to find out what went wrong.

This was also the first time I've ever looked at the Playthrough log just to see what it had wanted me to do, and I replied to an 18 day old open thread regarding the subject by KevinPal. Thanks for the feedback.

**Comment by flagrama** [comment]
Looks like its a logic error. It expects you to be able to get to the skulltula in crater but you can only reach that area as an adult, not as child. It'll be fixed soon. Sorry about your bad luck.

**Comment by r0bd0g** [comment]
The crater crate for silver scale is the "intended" solution. The GS needs to be checking the child access requirements (which is blast_or_smash) but it's not, so if you can get there as adult it thinks you can get the GS.

**Comment by EvilApple567** [comment]
Good to know, thanks for the answer. I'm just glad I was able to contribute in some way, even as a bug tester, to perfecting this amazing mod. The strangest thing to me was how comparably early I got locked out compared to most other incompletetable seeds I've seen.

Also r0bd0g I don't think it should be checking for "smash" if you're referring to the hammer, as child Link can't wield it.

**Comment by flagrama** [comment]
If you hammer the rocks on Death Mountain Trail as adult, they stay smashed when you go back to child.

**Comment by StenAtBigSkyResort** [comment]
Won't `blast_or_smash` catch that either way?

**Comment by flagrama** [comment]
No. There is no way to explicitly check that you are a child, which is the assumption that caused the GS logic bug in the first place. We need to only use `blast_or_smash` in areas where blasting or smashing cause the same result. In this case it is fine since smashing those rocks and then going back in time works.

**Comment by EvilApple567** [comment]
Ah, correct. I should've known as I just found in the same seed that blowing open the Lost Woods shortcut from Goron City with the Bow keeps it open as Child. This game sure is difficult to wrap your head around sometimes.
