### ISSUE TITLE
Deku Scrub Salesmen spawning issues.

### ISSUE THREAD

**Issue by shoover56** [TestRunnerSRL/OoT-Randomizer#604]
Version: 4.6.2 Dev Build
Settings String: FW3ARAA9Y4LAAAAJGBRJLAA
Seed: 031620192
Platform: Wii VC

Can be more of a question if deku scrubs spawning weirdly is some sort of intended behavior I'm not aware of.

In the seed that I generated, Deku Scrub Salesmen seem to have issues where they sometimes do not spawn. I figured this was just a randomizer intended thing to reduce memory or just another setting configured that I forgot about, but it turns out it held me hostage after looking for the Mirror Shield for 3 hours.

The Mirror Shield, as in the spoiler log, shows that it was supposed to be from the Lon Lon Ranch Grotto Deku Scrub that sells Deku Nuts. I assume that's the left one because way back in the early part of the game when I checked, that specific Scrub was NOT there. Checking much later and then after I read the spoiler log, it still wasn't there.

There was also some weird issues with the Scrub Salesmen in Goron City. When I first went there, none spawned. Then when I checked back many hours later, of course looking for the Mirror Shield, all 3 were spawned. I was also able to go in and out and get the same rewards from them seemingly infinite times. This didn't break anything, like with Deku Nut count upgrades as it still capped to 40. But I could have theoretically gotten infinite skulltulas as each one kept counting.

**Comment by Cuphat** [comment]
Known issue with 4.5.3+ but nobody report it here so thanks. Use 4.5.2 or below for scrubsanity.

**Comment by shoover56** [comment]
@Cuphat Okay thanks I appreciate it. If you know (or anyone else that reads this issue), did something actually change to the scrubs that had the side effects that I reported, or will scrubs remain the same way they always have?

**Comment by Cuphat** [comment]
It was just a change to the flags they use, not an intentional gameplay change.

**Comment by TestRunnerSRL** [comment]
This was fixed as of 4.7.2
