### ISSUE TITLE
Goran shop as kid

### ISSUE THREAD

**Issue by resinate** [TestRunnerSRL/OoT-Randomizer#61]
i tried to remove all tunics in game but this shop was not in shop list, still sells red tunic

**Comment by flagrama** [comment]
You can't buy the goron tunic as a child anyway so will at least effectively do what you want.

**Comment by resinate** [comment]
atm editing shops isnt possible i found out

**Comment by TestRunnerSRL** [comment]
It should be possible, but the shop data is only updated if you turn shopsanity on
