### ISSUE TITLE
Entrance Rando Logic issue.

### ISSUE THREAD

**Issue by teallen1996** [TestRunnerSRL/OoT-Randomizer#616]
":version":         "4.7.5 f.LUM",
  "file_hash":        ["SOLD OUT", "Hover Boots", "Bottled Milk", "Slingshot", "Boss Key"],
  ":seed":            "B2MUIVJYVE",
  ":settings_string": "7B22RAA9PXMDAASSBENAKVUAS3LDVBA",

Bombchu Shop entrance leads to Talon's house. The Chicken Mini Game is only playable in daytime, however the Bombchu shop is only open at night therefore making this check impossible to do. In the seed posted, this contained a Goron Tunic which according to the playthrough log at the bottom, is a step on there.

**Comment by Roman971** [comment]
In this seed, you are expected to play Sun's Song inside Talon's House in order to play the game. You get Sun's Song in sphere 2 from the Ocarina memory game which unlocks Talon's Chickens in sphere 3.

**Comment by teallen1996** [comment]
Ahhhh, OK. Didn't realise you could play sun song inside, probably due to never needing to before entrance rando. Thanks for clearing that up for me!
