### ISSUE TITLE
MW Playthroughs Borked Up

### ISSUE THREAD

**Issue by LostThePirate** [TestRunnerSRL/OoT-Randomizer#638]
":version":         "4.9.3 f.LUM",
  "file_hash":        ["Mirror Shield", "Master Sword", "Frog", "Stone of Agony", "Longshot"],
  ":seed":            "MTMQYQ8LCE",
  ":settings_string": "7WSA8LB8TLMPSGBHBAABAUK3H2EA",

17-player MW seed; Spoiler Log was missing a lot of essential information.
- Playthrough is all messed up. Stops at Sphere 20 at random, nowhere near everyone's Triforces.
- Missing WOTH items from the WOTH list (Most pressing example: P4 held P3's Hammer for P3's 
Shadow Medallion Fire Temple on Vanilla Bridge settings, but the Hammer was not on P4's WOTH list).

[OoT_FE9BA_MTMQYQ8LCE_W17_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3042482/OoT_FE9BA_MTMQYQ8LCE_W17_Spoiler.txt)

**Comment by r0bd0g** [comment]
There's been a pull request sitting there a few days now that might fix this I dunno.

**Comment by Cuphat** [comment]
Known bug, fixed in #635.

Here's the fixed spoiler log:
https://cuphat.com/downloads/OoT_FE9BA_MTMQYQ8LCE_W17_Spoiler.json

**Comment by TestRunnerSRL** [comment]
Fixed in 4.9.4
