### ISSUE TITLE
Make Kokiri Sword and Slingshot available elsewhere with Open Forest off

### ISSUE THREAD

**Issue by Toxijuice** [TestRunnerSRL/OoT-Randomizer#647]
If I'm not mistaken, currently with the "Open Forest" option turned off, you will always find the Kokiri Sword and Slingshot in the forest. Having the option to keep a closed forest, yet shuffle those items elsewhere, might be interesting. I imagine it would mean that one of Bombs/Scale/Warp Song would always be in forest instead, for an alternate route out. This likely wouldn't be _too_ different from having Open Forest on; however, it opens up the potential to have Deku Tree inaccessible until later. Currently, with Open Forest on or off, the Deku Tree is always accessible fairly quickly (though, admittedly, not always beatable.)

**Comment by DatXFire** [comment]
See comments from #465 and #596

**Comment by dombarrieau** [comment]
This is more of a suggestion than an issue and should have been brought up in the discord channel instead of here

**Comment by Toxijuice** [comment]
Ah I see, my apologies. And thank you for pointing me in the right direction!

**Comment by TestRunnerSRL** [comment]
With the added Closed Deku, this shouldn't be needed
