### ISSUE TITLE
Trying to generate a seed produces error.

### ISSUE THREAD

**Issue by teallen1996** [TestRunnerSRL/OoT-Randomizer#650]
Using a setting string of AJRANNHAS9Y4XBEUCAJ2ACGSWKKA2NXT3AA produces the error

"Error: Byte must be in range (0,256)"

Not sure if I am just being stupid with one of the options or if something is broke?

Edit: Changed setting of damage from Half to Normal and a seed was produced correctly this time with no error. New setting string that worked: AJRANNHAS9Y4XBEUCAJ2ACGSWKKA2NXT3BA

**Comment by teallen1996** [comment]
Version 4.9.13

**Comment by darkangel93x** [comment]
getting that same error with your string

http://prntscr.com/nbkybr

**Comment by MrCheeze** [comment]
Root cause seems to be the use of write_byte(-1) instead of write_byte(255) https://github.com/TestRunnerSRL/OoT-Randomizer/commit/1109df4fc4083f50a2e20218afb92d0c5055f488#diff-a2bded7e17a2176a6d881d6a6854e68fR1128

**Comment by aofengen** [comment]
Any update on this? Getting at least one error on this a day in support
