### ISSUE TITLE
Feature request: start with Ocarina if starting as adult.

### ISSUE THREAD

**Issue by MrCheeze** [TestRunnerSRL/OoT-Randomizer#655]
As a design choice, by default the fairy ocarina isn't randomized by its usual spot, to prevent the game from being overly centralized around finding it.

With the new "start as adult" feature, you get the above centralization, since neither ocarina is available from its default location as adult. A simple fix for this would be to just add an option to start with it, although an alternative would be making it so that you start with it automatically if ocarina locations are unrandomized and you start as adult.

**Comment by darkangel93x** [comment]
dont randomize it go to forest and get your mido checks + ocarina <_< u get the ocarina as adult when you leave too

**Comment by MrCheeze** [comment]
O
