### ISSUE TITLE
Bombchu Bowling Prizes Out Of Order

### ISSUE THREAD

**Issue by EvilApple567** [TestRunnerSRL/OoT-Randomizer#656]
Seed: GBGUY251O9

Settings: AJ9ANSZLS9Y4XBAA6U593EAAJKL

4.9.13

I've been using this for a while and I'm pretty sure, along with other things, that Bombchu Bowling is supposed to give the two pool (unique) items first and second for convenience. This seed instead gave me the first item, then a purple rupee (which I initially left upon seeing), then the Shadow Temple key I needed, which I didn't realize until much later at wits end in the spoiler log. Also when I returned for the key the first prize offered was again the purple rupee. Not sure if BB now gives 3 prizes for some reason or if the item order/logic for convenience malfunctioned.

**Comment by flagrama** [comment]
When you get the item it is forever replaced with a purple rupee in the loop. The loop always starts at item 1, then item 2, then bombchus, bombs, purple rupee. Are you sure you didn't leave between the first prize and what you thought was the second prize?

**Comment by EvilApple567** [comment]
Ah, okay. Rewatched the footage and I was short on rupees for the second game, didn't know it worked like that. Thanks.
