### ISSUE TITLE
Milking the Stable Cows is Janky

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#665]
Standing in front of the left cow, you'll often milk the right cow. You have to stand way over to the left to milk the left cow.

**Comment by Nicholas-Steel** [comment]
Tasty Salamanders#4135 also mentioned this phenomena a fair while ago but it didn't seem to draw very much attention: https://discordapp.com/channels/274180765816848384/274186223147417600/562607462927171603
