### ISSUE TITLE
Burning Kak as child

### ISSUE THREAD

**Issue by dragonmost** [TestRunnerSRL/OoT-Randomizer#666]
If you have burning kak cs requirement as child, anytime you load into kak you get sent to the front entrance even if loading from a building.

**Comment by aofengen** [comment]
known issue - fix already submitted.
https://github.com/TestRunnerSRL/OoT-Randomizer/pull/664

**Comment by flagrama** [comment]
Why would you waste issue #666 like this. Now we need a new repo so we can have a shot at a proper meme 666.

**Comment by Nicholas-Steel** [comment]
Kak burns in ER because of the devil!
