### ISSUE TITLE
All Indoor and Overworld shuffle unbeatable seed with random starting time of day

### ISSUE THREAD

**Issue by IntrinsicNerd** [TestRunnerSRL/OoT-Randomizer#672]
Links house as a child took me to castle town entrance at night, so I can't leave through the gate, and the other entrance leads me to death mountains top most entrance, where I can't leave because I have no items

**Comment by Cuphat** [comment]
You need to actually give information here, such as version/settings string/seed.

**Comment by Zannick** [comment]
I assume you mean Crater, because Trail has other exit options. But there are a few checks you can make in that area even with no items. If you have a spoiler available, we'd be able to see what the seed expects you to do.

**Comment by LostThePirate** [comment]
If it took you to Trail, you could let Time of Day pass there and then go back.
