### ISSUE TITLE
Reverse wasteland required with glitchless logic

### ISSUE THREAD

**Issue by SMWDreams** [TestRunnerSRL/OoT-Randomizer#676]
Started up a new seed with full entrance randomizer using glitchless logic (as it does not currently support other things) and in order to complete the seed it requires either a child bombchu megaflip to get to fire temple for zelda's lullaby to get in through Darunia's room, or to do reverse wasteland as child. I feel that reverse wasteland should not be considered in glitchless logic or at the very least with lens required set to everywhere. The seed number is 96112_1TC9HNQBAK and my settings string is AJ9UNSZAS2NXKFAASACJCBJGT9JLAA. This is the current release.

Thank you.

**Comment by flagrama** [comment]
1) Post the spoiler log ESPECIALLY since you didn't include version
2) Generally the Discord is better for this stuff before you report an issue

**Comment by SMWDreams** [comment]
Since github doesn't accept JSON files here it is in wonderful plaintext:

[Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3133662/Spoiler.txt)

Ver 4.10.5

**Comment by flagrama** [comment]
And have you followed the full Entrance Playthough at the end of the spoiler log? Which specific step there do you have issue?

**Comment by SMWDreams** [comment]
In order to get to kokiri forest in order to obtain the master sword you must either:
1. Enter gerudo fortress from wasteland
2. Enter Death mountain crater from Darunia's Room

The second one is not possible as child link. Even if it were, it requires Zelda's Lullaby which requires bolero, which is in fire temple, or a chu megaflip. The first one requires you doing reverse wasteland even though glitcless logic is set and lens is set to required everywhere. Reverse wasteland is not difficult, but with glitchless logic **and** lens required everywhere having reverse wasteland as child being in logic seems like it isn't right.

**Comment by itsmedoggo** [comment]
I believe you're expected to use Prelude of Light to get to the Temple.

**Comment by flagrama** [comment]
```json
"5":  {
  "GS Zora's Fountain Above the Log":               "Prelude of Light"
}
"6":  {
  "Master Sword Pedestal":                          "Time Travel",
}
```
Yeah, looks like it.

**Comment by flagrama** [comment]
Again, it is best if you ask in the #gameplay-support channel on the Discord next time before creating a issue. 99% of the time it isn't a bug.

**Comment by Zannick** [comment]
Also, neither glitched nor glitchless have reverse Wasteland in logic. I definitely did it once myself thinking it was the only option, but I must have also been overlooking something.
