### ISSUE TITLE
[ER] Spirit Temple temp flags affecting whatever area is the Spirit Temple entrance

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#686]
If you leave through the hands, it doesn't reset the spirit temple temp flags. That's normal. But then you can enter the spirit temple entrance and apply those flags to whatever dungeon happens to be there.

What probably has to happen is, if the entrance to Spirit Temple leads to an area other than Spirit Temple, the temp flags are cleared as you enter.

(There are other entrances where the temp flags are not reset, but none of those are randomized in the current ER implementation.)

**Comment by TestRunnerSRL** [comment]
Merged a PR that deals with this issue. It always resets the temp flags when entering from the main entrance for the same of consistency in ER
