### ISSUE TITLE
Shopsanity textbox lock

### ISSUE THREAD

**Issue by Tyrusss** [TestRunnerSRL/OoT-Randomizer#69]
![bug](https://user-images.githubusercontent.com/42982810/45058562-f3fca480-b090-11e8-99ff-a98338e1224f.JPG)
Bought Biggoron Sword from Zora shop as kid, stuck on Pocket Cucco text box. I don't have text shuffle on.

Seed: 479IJOAX95
Settings: RJNBR2JKSSDJGA

**Comment by TestRunnerSRL** [comment]
Should be fixed now
