### ISSUE TITLE
Manually entering Player Count displays errors in console (Dev build)

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#694]
1) Open up the Developer Build
2) Edit the number of players by clicking in the box and typing a number instead of clicking the increment/decrement buttons.

Console displays a bunch of errors.
![image](https://user-images.githubusercontent.com/11567846/57769990-96a61080-7752-11e9-8e7a-e7287feb15e0.png)

https://github.com/TestRunnerSRL/OoT-Randomizer/issues/618 may be related.

**Comment by flagrama** [comment]
A copy and paste/screenshot of the error would be helpful.

**Comment by darkangel93x** [comment]
#618 is the same thing

**Comment by Nicholas-Steel** [comment]
![image](https://user-images.githubusercontent.com/11567846/57769944-770ee800-7752-11e9-8fc4-69eaae64cdc7.png)

**Comment by Nicholas-Steel** [comment]
Added an image Flagrama, that particular error was when I manually inputted a value of 8.
