### ISSUE TITLE
[ER] Triggering OoT Cutscene Warped out of HF

### ISSUE THREAD

**Issue by LostThePirate** [TestRunnerSRL/OoT-Randomizer#699]
4.11.7
String: AJEPWSZMA9VXESBJELE8EAFLJHKBAEAJGV92LAA
Had gotten my 3 Stones and was headed to the Bridge via HF to get my OoT item (songs and Ocarinas shuffled, had hint it was Mirror Shield). Upon triggering the cutscene, was warped to Castle Grounds Entrance (which, in this seed, is only accessible via Kokiri Forest).
[OoT_1706C_ECN40WRNSN_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3185088/OoT_1706C_ECN40WRNSN_Spoiler.txt)
https://clips.twitch.tv/PiercingSmellySmoothiePastaThat

**Comment by flagrama** [comment]
https://github.com/TestRunnerSRL/OoT-Randomizer/pull/689

**Comment by LostThePirate** [comment]
Sorry, didn't realize this was the same issue.

**Comment by TestRunnerSRL** [comment]
Ok should be fixed now
