### ISSUE TITLE
D-Pad Not working on VC

### ISSUE THREAD

**Issue by shawlucas** [TestRunnerSRL/OoT-Randomizer#701]
Using the latest source, the D-Pad isn't working for quick boots or ocarina or anything. All it does it toggle the map.

**Comment by TeknoAnonymous** [comment]
Very lacking in detail, and better suited in a support channel. If I had to assume, the issue is probably user error.

**Comment by Cuphat** [comment]
By default, all 4 d-pad buttons are bound to L. Use the latest gzInjectGUI with the proper settings to have the D-Pad work properly. https://discordapp.com/channels/274180765816848384/476723801032491008/525343041079345152

Yeah, this should be in #setup-support, not in a GitHub issue.

**Comment by TestRunnerSRL** [comment]
Yeah, sounds like not using the proper gzInjectGUI
