### ISSUE TITLE
Python Gui unusable with Dark Theme

### ISSUE THREAD

**Issue by NeoniousDX** [TestRunnerSRL/OoT-Randomizer#702]
![Normal Mode](https://user-images.githubusercontent.com/50808676/57987617-01f12a80-7a52-11e9-8364-2602de683d25.jpg)
![Dark Mode](https://user-images.githubusercontent.com/50808676/57987618-04538480-7a52-11e9-9503-74d25872c878.jpg)

I have noticed that If I am using a Dark Theme on my OS and launch the Python Gui, that the radio boxes are nearly impossible to see the check mark on. The Radio box seems to use a white background and white text while using a Dark Theme, Compared to Normal Theme with white BG, Black text. Because of that, for example, I cant see whether the options for Shuffle Kokiri Sword and Open Door of time are on or off. I notice it doesn't affect the rest of the text boxes (dropdowns) which are readable. Is this some kind of bug with the Gui?

**Comment by darkangel93x** [comment]
The GUI afaik gets a rework "soonish" anyway. I personally can read this all fine though. Wait for the update id say.

**Comment by flagrama** [comment]
What ever you are using to apply that theme is not doing it in a standard way. While I'm curious what your OS is, you can clearly see it is having the same exact issue in the light theme and this has nothing to do with the randomizer.

**Comment by NeoniousDX** [comment]
Arch Linux, KDE Plasma
Breeze Theme
Breeze Dark Theme

It is definitely not doing it in the light theme. In both screenshots the settings are 100% identical. Kokiri Sword, ganons door lock, all locations, and Open door of time are all checked off. The checkmarks in the radio boxes are visible in the light theme and near impossible to see in the dark theme.

**Comment by flagrama** [comment]
![image](https://user-images.githubusercontent.com/634079/57991463-1c8cc900-7a7d-11e9-83ed-ca00c5daf979.png)
Here is Cinnamon's Dark theme. Notice how there is no weird super light grey areas like in your light theme. This is how TkInter is Always supposed to look in its default theme.

**Comment by TestRunnerSRL** [comment]
This is pretty moot since there's a gui rework in the works. Also lol tkinter

**Comment by NeoniousDX** [comment]
I appreciate the input. Thought I would at least ask about it in case it was something with the generator that could be improved, but I can see that it is more likely what Flagrama said about theme weirdness

**Comment by NeoniousDX** [comment]
found the true solution.

In The arch linux/plasma Systems settings, Under "Colors" there is an option for "Apply colors to non-Qt applications"

Turning this off fixed it.

Thank you for the assistance regardless!
