### ISSUE TITLE
Skip minigame shops option

### ISSUE THREAD

**Issue by ryfon** [TestRunnerSRL/OoT-Randomizer#715]
Was playing a new rando last night and thought it would a nice option to add, If you have required items to play minigame when talking with owner, he just gives you reward. It would be a nice speed boost for the normally arbitrary minigame loop.

**Comment by aofengen** [comment]
no. I am 100%, whole-heartedly against this idea. Minigame skill is just as important in this rando as routing or other execution. Personally, I hope this is never implemented

**Comment by LostThePirate** [comment]
Definitely opposed to this.

**Comment by dombarrieau** [comment]
Just disable the location if you don't want to play the minigame.

**Comment by TestRunnerSRL** [comment]
I think if you don't want to play the minigames, you should just disable the location. Not really a fan of adding an option for this
