### ISSUE TITLE
Progression item at disabled location

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#716]
hot bananas Today at 12:50 AM
In the dev build, are  excluded checks only junk?

World 2's DMC bomb scrub had song of storms, despite being excluded

https://cdn.discordapp.com/attachments/438698093354156032/582053029797298188/OoT_D6CE1_C3ORKWZFUT_W5_Spoiler.json

**Comment by Zannick** [comment]
I think this is the culprit:
```python
    worlds[0].distribution.fill(window, worlds, [shop_locations, song_locations, fill_locations], [shopitempool, dungeon_items, songitempool, progitempool, prioitempool, restitempool])
```
as world.distribution is a `WorldDistribution` object, not a `Distribution` object (which would perform the fill on all worlds).
