### ISSUE TITLE
Open Kakariko Option Disappeared?

### ISSUE THREAD

**Issue by TheDylantula** [TestRunnerSRL/OoT-Randomizer#724]
I just recently updated from v4.10.5 to v4.12.1. I went through and configured my settings, and while I was doing my run I realized the gate in Kakariko Village to Death Mountain Trail was closed, even though I usually have it set to be open. I went to update my settings for future use, and I am unable to find the Open Kakariko Setting. Was it removed, did the location change to somewhere I'm not finding it, or is it bugged in this version where it's not showing up as an option? I've attached a screenshot of the settings page where it was located in v4.10.5, and a screenshot of the same page in v4.12.1 where the setting is missing.

![v4.10.5 Settings](https://user-images.githubusercontent.com/51125873/58486866-4b193c80-812c-11e9-9a46-457867eff3e3.png)

![v4.12.1 Settings](https://user-images.githubusercontent.com/51125873/58486887-553b3b00-812c-11e9-8171-1e119be1b5a7.png)

**Comment by aofengen** [comment]
The option was removed in 4.11.7. It will not be returning

**Comment by Nicholas-Steel** [comment]
It's currently an intentional change.

**Comment by dombarrieau** [comment]
When in doubt, ask in the discord support channels first.

**Comment by TheDylantula** [comment]
Alright, thank you guys. Unfortunate that it's been removed. I also feel dumb I didn't think to ask the Discord first, I'd completely forgotten it existed.
