### ISSUE TITLE
Child can drain lake setting not tied to ER in GUI

### ISSUE THREAD

**Issue by dotzo** [TestRunnerSRL/OoT-Randomizer#727]
The symbol for child to be able to controll the lake is set to 0x01 when dungeon ER is turned on, but the individual setting is not dependent on it which is an apparent inconsistency in the GUI.  Should gray out the "Child can control lake" when an ER setting that sets the symbol for child lake control.

**Comment by Roman971** [comment]
Fixed by #720

**Comment by TestRunnerSRL** [comment]
both fixed, and the option removed. double fixed
