### ISSUE TITLE
Water Temple MQ Compass wihtout magic glitchless

### ISSUE THREAD

**Issue by vilhelmen** [TestRunnerSRL/OoT-Randomizer#733]
First time playing and I roll MQ water temple :/

From the v4 online generator:
Seed: `37EQEAKNGM`
Settings String: `B7PCJBBSBAHMAQJQ2RJTSTSU2U2VAWJXAAAJGBZSLA`
https://ootrandomizer.com/seed/get?id=150155

Spoiler log says `Water Temple MQ Compass Chest | Magic Meter` but from what I can tell the first thing you need to do in MQ water temple is din's fire (or maybe fire arrows) but that needs magic.

Semi-related, I can't find 2x magic in my spoiler log, it's just gone?

**Comment by Zannick** [comment]
Your other Magic Meter is the 40 skulls reward.

**Comment by Zannick** [comment]
Logic thinks you can get the MQ Compass chest with Bow... are you missing a lighted torch you can shoot from?

**Comment by BladefangFT** [comment]
And MQ Water Temple Compass chest is the chest behind the two torches on the lowest level east side. Basically, go up to the triforce emblem, play lullaby and shoot arrows through the lit torch on the bottom level.
Same as vanilla water to get into that room really.

**Comment by dombarrieau** [comment]
Ask in the support channels of the discord server before making an issue next time :)

**Comment by vilhelmen** [comment]
How embarrassing, this is extremely my bad, I was relying on the playthrough tab and not the raw log.
