### ISSUE TITLE
Text wrapping issues

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#749]
So I think the recent changes to the message handling might have caused some unwanted side effects. Text is wrapping into additional textboxes weirdly and some items have the wrong icons/no icon at all.

Can be seen in the next few seconds [right here](https://www.twitch.tv/videos/440969192?t=28m59s).
[Beans are pretty hilarious](https://www.twitch.tv/videos/440969192?t=03h27m09s).

Unsure if this is multiworld related or also happens in solo play, we just noticed it a few hours ago during a multiworld.

**Comment by darkangel93x** [comment]
lol
