### ISSUE TITLE
Missing child storms grotto in regions

### ISSUE THREAD

**Issue by TopHatMan** [TestRunnerSRL/OoT-Randomizer#75]
Trying to be more clear and concise. Meadow STorms Grotto Child Access is missing ref somewhere I think in Regions.py. Your clearly working hard and fast and made a oversight. 

As general question logic here. if you can get storms as a kid why need adult check?

`       create_interior_region(
            'Forest Temple Entry Area', 
            ['Sheik Forest Song', 'GS Lost Woods Above Stage', 'GS Sacred Forest Meadow'], 
            ['Adult Meadow Exit', 'Forest Temple Entrance', 'Meadow Storms Grotto Adult Access']),`

**Comment by TestRunnerSRL** [comment]
This was already fixed.
Child needs to be able to fight the deku scrubs, the song is not enough
