### ISSUE TITLE
FAQ Suggestion

### ISSUE THREAD

**Issue by uncleawie** [TestRunnerSRL/OoT-Randomizer#755]
It might be worth noting in the FAQ that the ceiling switch in the entrance to Jabu can be toggled with bombs. 

Love y'all. Feel free to close under butt-hurt-noob.

**Comment by aofengen** [comment]
Maybe not in the FAQ, but certainly on the wiki, if not already there.

**Comment by uncleawie** [comment]
I meant whatever this page is called: https://wiki.ootrandomizer.com/index.php?title=Logic
Learning something new every play through and loving it.

**Comment by aofengen** [comment]
Yeah, that's what I meant too. Some stuff is in there and some stuff is on the Readme here. Never k nm ow what's where anymore lol

**Comment by dombarrieau** [comment]
https://wiki.ootrandomizer.com/index.php?title=Logic 
Added

**Comment by dombarrieau** [comment]
Issue can be closed now :)

**Comment by uncleawie** [comment]
Oh yes. You peeps are awesome.
