### ISSUE TITLE
Fog glitch (and other weirdness) by leaving Spirit hands in ER

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#757]
So we were wrapping up an ER seed and Renoko ran into a fog glitch (and maybe some more) when leaving the Spirit hand.

It looks like it is the following sequence that causes it:
1) enter Kak and trigger Nocturne CS
2) go into BotW entrance (that has Spirit) while rain effect is still active
3) leave through the hand

[full sequence](https://www.twitch.tv/videos/445295318)
[first occurence](https://www.twitch.tv/videos/445295318?t=12m43s)

Here are the files needed to check it out:
[zpf to create the seed, player number 2](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3337898/OoT_3E951_3Q68G2420M_W6.zip)
[2 states, one inside and one outside the load zone](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3337908/save.states.zip)

Crossing the load zone after loading one of the states just crashes bizhawk in colorful spaghetti for me, but loading the `Weirdness.State` shows the fog glitch in action.

I don't know if this is something that can be fixed or if people are maybe interested to play around with the effects of fog glitch, but I thought I'd post it here.

**Comment by Hamsda** [comment]
Oh and here's the spoiler
[OoT_3E951_3Q68G2420M_W6_Spoiler.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3341402/OoT_3E951_3Q68G2420M_W6_Spoiler.zip)

**Comment by rattus128** [comment]
I ran into this myself. Looks like its definately a spirit-on-well thing, and I also have rainstorm on entry. I have directly come from the nocturne warp as adult. I don't think it is nocturne CS related.

Here is my entry:

https://clips.twitch.tv/IntelligentRespectfulLionBatChest

And here is the bug zoning out to the mirror shield check:

https://clips.twitch.tv/CrackyLaconicReubenHassanChop

Playing suns once out in the collossus sends the whole screen foggy grey.

Playing on mupen64plus on Linux. Unlikely to be an emulator issue. Definately not a MW issue.

Seed info:

```
  ":version":              "4.13.13 f.LUM",
  "file_hash":             ["Frog", "Deku Stick", "Boomerang", "SOLD OUT", "Kokiri Tunic"],
  ":seed":                 "KZNOVMDANF",
  ":settings_string":      "AJTGG2X3AREXESBJELEYE8EAF8FAAENABDP6ECHUGBEVTMEFSA",
```

**Comment by TestRunnerSRL** [comment]
Should be fixed now
