### ISSUE TITLE
Freeze/Crash at Escape Sequence

### ISSUE THREAD

**Issue by audstreams** [TestRunnerSRL/OoT-Randomizer#758]
I successfully finished my randomizer run with the escape sequence set to not skip, but upon entering a certain hallway a bit after the stalfos room the game consistently freezes up. I am using the OotModLoader and Bizhawk, as I plan on streaming a four-player randomizer run soon with a different seed and want to get this figured out before then. Attached are both the seed and save files. I have had someone else test this and they have replicated the freeze, though neither of us are sure what exactly is causing it.

https://www.ootrandomizer.com/seed/get?id=169061

[saves.zip](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3346335/saves.zip)

**Comment by aofengen** [comment]
This is a known error related to Ocarina of Time Online, not the randomizer. Please close this issue and direct your issue to their discord
