### ISSUE TITLE
Allow starting with Kokiri Sword

### ISSUE THREAD

**Issue by churnthing** [TestRunnerSRL/OoT-Randomizer#768]
Title. Due to ER, you aren't guaranteed to be able to get Kokiri Sword immediately if iyou leave Kokiri Sword unshuffled.

**Comment by aofengen** [comment]
You will always have access to sticks, which are stronger. However, I can see your point. It's not a bad idea to allow this

**Comment by BladefangFT** [comment]
Dev has plando, which can do exactly what you want with a little bit of extra work. therefore a setting for this is very unlikely to happen

**Comment by TestRunnerSRL** [comment]
Distribution File:
```
{
  "starting_items":   {
    "Kokiri Sword": { }
  }
}
```

Also all the start with option will probably just be removed after the GUI rework. Unlikely to happen in time for 5.0 though. See #634
