### ISSUE TITLE
[Feature Request] include "randomize all" feature in Cosmetics and SFX

### ISSUE THREAD

**Issue by tommaniacal** [TestRunnerSRL/OoT-Randomizer#785]
Just so you don't have to click through everything every time you want to randomize everything (that's a lot of everythings lol)

It would probably be best to have both a "Randomize All" which uses the set color choices, and "Randomize All (Completely Random)" which uses the completely random function.

For SFX, having a "Randomize All" and a "Randomize All (Ear Safe)" would be best

**Comment by Hamsda** [comment]
> Just so you don't have to click through everything every time you want to randomize everything

It saves your last choices on both the GUI and the website, so I'm not sure why this would be needed?

**Comment by tommaniacal** [comment]
Ah, I just updated it so it must have reset my settings, I didn't know it saved them.

**Comment by Hamsda** [comment]
As long as you don't delete the corresponding .sav file, yeah it should keep settings (unless they change in dev, like ganon door/bk).

**Comment by dragonbane0** [comment]
Might still be convenient to switch between a personal configuration and randomize all for some event or something

**Comment by Hamsda** [comment]
Fair, just many people "update" dev by deleting their entire folder, therefore removing their .sav files.

**Comment by TestRunnerSRL** [comment]
This exists now
