### ISSUE TITLE
Plando ignoring shop prices in distro file

### ISSUE THREAD

**Issue by LostThePirate** [TestRunnerSRL/OoT-Randomizer#787]
When using a distribution .json file with Shopsanity enabled in the settings, the Randomizer ignores shop prices as set in the distro file and randomizes them instead.

I don't have first-hand experience with this, as I haven't tried to generate Plandos myself, but documenting it here on the GitHub on behalf of others, as an Issue hadn't been opened yet for this known problem. Hoping that we can get this one sorted out in time for 5.0, and by posting it here, getting it a bit of additional visibility so that perhaps other Contributors might look into it.

**Comment by TestRunnerSRL** [comment]
Should be working now
