### ISSUE TITLE
wrong name for .log files from patch file

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#793]
So with the new GUI we now have the .log files for the patching process.
When creating from a patch file, the corresponding .log file will have a wrong name. This makes it weird for players to figure out which files belong together, especially looking at it from a support perspective.

Example:
patch `OoT_D5813_SH17F04VXV_W3.zpfz`
rom `OoT_D5813_SH17F04VXV_W3P3-comp.z64`
log `OoT_8BD16_ZZEFOOD0GK_W3.log`

Content of the log:
```
Patching ROM.
Compressing ROM.
Starting compression.

Loading Archive.

Detected 4 cores.

1375 files remaining...

1225 files remaining...

1075 files remaining...

 925 files remaining...

 775 files remaining...

 625 files remaining...

 475 files remaining...

 325 files remaining...

 175 files remaining...

  25 files remaining...

Files compressed, writing new ROM.

Compression complete.

Created compessed rom at: D:/Roms/OoTR\OoT_D5813_SH17F04VXV_W3P3-comp.z64
Done. Enjoy.
```

So it's documenting the rom file name, just has the wrong file name itself. 
It probably just pulls the random one that you'd get if you weren't creating from a patch file.

**Comment by TestRunnerSRL** [comment]
Changed the log files to use a timestamp instead of the seed/settings so it should be less confusing now. Also moved the logs to the `Logs` folder so it should stop cluttering up the output folder.

**Comment by Hamsda** [comment]
Oh yeah, that works well!
