### ISSUE TITLE
Error while creating seed (Message Text table is too large)

### ISSUE THREAD

**Issue by Kjelli** [TestRunnerSRL/OoT-Randomizer#8]
Message Text table is too large: 0x3818c written / 0x38130 allowed.

Settings string: BYB36CAACE

![image](https://user-images.githubusercontent.com/6494395/42840198-52736172-8a06-11e8-98f8-cf9159758c54.png)

**Comment by Kjelli** [comment]
Worth mentioning, this no longer occured when I unchecked `Compress Rom`.

**Comment by TestRunnerSRL** [comment]
In a future update, the item message will be shortened so this won't be a problem

**Comment by TestRunnerSRL** [comment]
The update was pushed
