### ISSUE TITLE
Plando Inconsistencies

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#801]
dotzoToday at 5:25 AM

so, plandos either don't respect a seed or there's some element of randomness to filling the world which isn't controllable.  We were trying to recreate a plando'd dev file in #gameplay-support (link to the start-ish of the screwing aroudn: https://discordapp.com/channels/274180765816848384/274186223147417600/604921576747565080 ). i messed with it a little more and the random starting ToD didn't line up. Also they were starting with items that weren't shown in the plando, but even after adding those the shop items varied in quantity.  the file name also seemed dependent on the order in which the tricks were added even though that wouldn't change the settings string.  basically a lot of weirdness which would prevent the sharing of a plando amongst people and have it be identical

**Comment by r0bd0g** [comment]
Order of disable locations (and maybe enabled tricks?) affecting the seed but not the settings string seems to definitely be a real bug. I haven't looked into the rest of this but I did notice some oddities with starting items? I dunno man...

**Comment by TestRunnerSRL** [comment]
Plandos now read the settings from the dist file, including randomized settings. The keys are also sorted so changing the order of the lines in the dist should not affect the seeding. The seed is still not read. Also distributing the dist file is /not/ the recommended way to distribute plando seeds. They will contain the entire spoiler, so if you want to dist these kinds of things to make sure everyone is getting the same thing, use the zpf patches instead
