### ISSUE TITLE
Only beatable seed not beatable on the latest dev version (pulled 1 day ago)

### ISSUE THREAD

**Issue by Kongolan** [TestRunnerSRL/OoT-Randomizer#807]
It's odd and it's the first time it happened for me, but it kinda ruined my fun. I went into forest temple and got stuck.

As you can see in the spoiler logs, forest is a medaillion, but 1 small key is put onto phantom ganon HP, which obviously is unreachable. I have all tricks enabled, but i'm not aware of a glitchless trick to pass the door with the frozen eye spinning room, to get to the falling wall room. Is there any, if yes is there a video of it?

Couldn't attach the spoiler log so here is the link: [https://pastebin.com/WX1UMSP9](url)

**Comment by Cuphat** [comment]
"logic_forest_scarecrow"

You might want to read up on what that does before enabling it.

**Comment by Kongolan** [comment]
Thanks for the link. I was aware of the 2nd entrance, i tried hover boots and scarecrow song and both didn't work for me. But it thought it was possible. Logic is fine so. Thanks.
