### ISSUE TITLE
[Feature] Don't make trials beatable without their respective medaillon

### ISSUE THREAD

**Issue by Kongolan** [TestRunnerSRL/OoT-Randomizer#808]
What's the idea - Ganon's Castle is not used at all

First off this sound stupid, because nobody plays with open bridge or anything. Indeed those have bad sides effects on the actual game content, you barely see any trials beaten and if you do, you will never run into any important items besides light arrows, which can actually be in ganons castle, so basically everyone just go-modes ganon castle.

We could change this, by having the bridge open setting on, but acutally need all medaillons of the trails, which are active (perhaps random).

So **how do we do it**? - The new Logic
I'm not certain if it's possible to remove the core at the end of the trial, which you shoot with the light arrows. But this would be the best option to do so. As long you don't have forest medaillon the green trial can't be completed because the core is missing, but once you have all items for it, you can enter it.

Another way would just to split the flags for the trial beam (which is already handled by the ROM hack) and the shooting of the core in seperate flags. So the core can be gone, but the light beam is still active? So we could let people finish the trial but it will not clear the beam unless you have the medaillon.

Lastly, we could just lock the door in some way and remove the lock if we have the medaillon.

**So how does it change things:** - All Medaillon with ganon bridge open from the start
People could route trials in, once they have like access to at least 2-3 trials and to clear them out to check for items. But they won't detour there when there is too less to check. 

Also it would have different requirements to beating the seed on, sometimes you only need fire, water and shadow medaillon, sometimes you need all, sometimes you need a few. So setting the trial count to random but at least 3, would be a nice option.

Scrubshuffle would make the scrubs easier accessible and you don't need key sanity to actually lock the boss key of ganon somewhere differently. 

Also it will have a similar option like the tournament settings right now, because you basically need all medaillons if set so, else with a open bridge you would only need those items to finish the trails (which are much harder to follow the logic and actually go where you need to go). This strong point of the **ALL MEDAILLION part is actually why it became the meta, everything is random, but you have a straight goal, just finish those temples if you can**. With this new setting, actually it would be very similar just with bridge open and having to complete some or all trials.

**Comment by Cuphat** [comment]
Don't the Ganon's BK options accomplish basically the same thing? You can set it to get the key on Shadow / Spirit medallions, or the 3 stones, or all medallions, or all stones + medallions. It only locks out Ganondorf and Ganon, making it possible for Ganon's Castle to be useful.

**Comment by Kongolan** [comment]
That way, you would just collect medaillons to actually enter the castle and the go-mode to find the BK. It's similar, but having less medaillons required and the option to actually randomize, which trials and medaillons to collect would fall off. As well as having an early chest-rich dungeon, especially if you run scrubsanity and get to the ganon scrubs.

If it's technically hard to code, because you can't find a good way to maintain the trial beams as long you don't have the requirements, then sure than BK shuffle is the only good option. But it means that the seed can randomly be item locked again, but not progression locked, which is a difference for me.

**Comment by KevinPal** [comment]
I believe you could just set bridge to open and put the BK on all medals to achieve this. The only benefit I see would be the routing involved with periodically coming back to GC to clear a few trials after you get some medals.

**Comment by Kongolan** [comment]
As i tested both of what you suggested, it doesn't simulate the feeling of random trails setting up how many and what medaillons to get. Currently open bridge and having ganon key on the light arrow cutscene is the closest to get to, but it always sets 6 medaillons or other stuff and doesn't go well with beatable trials overall, since they are only beaten to get to the inner castle. I still think my idea has something unique, which can be added if possible. No need to have it soonish though.

**Comment by TestRunnerSRL** [comment]
I agree with @KevinPal that the Ganon BK settings accomplish the same thing. If you don't want to have it be 6 dungeons then set the option to spiritual stones or vanilla to make it 2 or 3 dungeons. The important play here is the number of dungeons required to get to ganon. Whether it was Water + Fire or Shadow + Spirit, it's the same thing. The only thing that matters is that dungeons those medallions ended up at, not which medallions they are.
