### ISSUE TITLE
Generating with a blank "Base ROM" path fails if the ROM is located in the root of the installation directory

### ISSUE THREAD

**Issue by Nicholas-Steel** [TestRunnerSRL/OoT-Randomizer#819]
Start of conversation: https://discordapp.com/channels/274180765816848384/512048482677424138/607249006300496074

If the downloadable randomizer is installed to C:\fruit\ and you place ZOOTDEC.z64 in the Fruit folder, the program will fail to find the ROM if Base ROM path is blank.

**Comment by TestRunnerSRL** [comment]
Should be fixed now
