### ISSUE TITLE
Where is the gui executable for windows?

### ISSUE THREAD

**Issue by csharporblfat** [TestRunnerSRL/OoT-Randomizer#82]
I downloaded the zip file extracted everying overwriting ampros version. But no gui update was included for those of us who dont have python. And ampros version did not show any of the new options that this version has. How do I make this work?

**Comment by StenAtBigSkyResort** [comment]
[Please view and read the readme.](https://github.com/TestRunnerSRL/OoT-Randomizer#installation)

You'll need Python. Then click gui.py

**Comment by TestRunnerSRL** [comment]
Soon (TM)

**Comment by scattertv** [comment]
@StenAtBigSkyResort That doesn't need to be edited out, it's true. An executable will be available for releases. There have been no releases of the randomizer since 2.0.

**Comment by TestRunnerSRL** [comment]
The release for 3.0 is available on AA's repo
