### ISSUE TITLE
[Suggestion] Make the new Gerudo card behavior an option

### ISSUE THREAD

**Issue by lurch9229** [TestRunnerSRL/OoT-Randomizer#820]
After playing a few seeds with the changes made with shuffled card, there is now little reason to rescuing the carpenters. I do like the changes made in certain situations but for my play style (vanilla fortress with keysanity) it removes a huge part of the challenge it poses. I think having it as an option in the drop down for the fortress behavior setting would seem more fitting. 

I do like the guard being on the other side of the gate to open it if you reverse wasteland and think that should be applied after rescuing the carpenters, as I have forgotten to open the gate many times in ER and had to take longer routes to get to places, it's just the guards not being hostile with the card that I believe is unbalanced.

**Comment by r0bd0g** [comment]
The guard should be there in ER even if the card isn't shuffled. If it's not then I think somebody screwed up?

**Comment by Nicholas-Steel** [comment]
I see what you mean by balance. Originally rescuing the carpenters unlocked access to 3 item location checks I think? Where as with the new system it's diminished to 1 check (reward from rescuing carpenters) which seems a bit lacking for the amount of effort you go through rescuing them.

**Comment by r0bd0g** [comment]
It would probably have to be forced to be this way in special interior and full OW ER, regardless of if there's an option for it. Non-repeatable access...

**Comment by lurch9229** [comment]
I have not tried ER with non shuffled card with the new changes made so could not say if they are there or not. Its the fact the guards are passive with just the card I think needs rebalancing by way of being an option you can choose. I was just saying about the gate guard being there is a good change made compared to the other one.

**Comment by TestRunnerSRL** [comment]
I not sure I agree with this reasoning. If you want to make that check worthwhile, just make it so you only need to rescue one carpenter. It's fast that it doesn't make any sense to skip. I don't want to add an option for this because it break NRA for ER and I don't like the inconsistency of handling shuffle card differently.
