### ISSUE TITLE
Import Settings GUI Freeze

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#821]
Nicholas Steel (UTC +10)Today at 11:34 AM

Clearing the Settings String and clicking Import seems to place the program in a soft-lock with a perpetual Please Wait and spinning busy symbol. Have to click the X and close the whole program to escape the situation. Windows 10 x64

**Comment by TestRunnerSRL** [comment]
I believe this was fixed
