### ISSUE TITLE
Heat Timer doesn't reset

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#822]
According to dotzo, the heat timer is not resetting when going to a new scene that is still in a heated area? The main problem with this would be the Volvagia boss door...

**Comment by KevinPal** [comment]
Seems to be working for me on 4.15.22, Non ER, and version 4.15.10, ER

**Comment by r0bd0g** [comment]
dotzo Last Sunday at 8:35 PM

Going from the room before Volv into Volv's room with the heat timer doesn't reset it despite it being a different scene.
":version":             "4.15.10 f.LUM",
":seed":                "K5J8JG6HQ4",
  ":settings_string":     "AJWAC2HQHANJX3ZAAA8HEF9JLAA",

**Comment by KevinPal** [comment]
Still seems to be working for me. I noticed Useful cutscenes were enabled, was there some sort of boss key skip involved?

**Comment by dotzo** [comment]
Yea it was a BK skip. Never knew it didn't reset the timer. Close issue.
