### ISSUE TITLE
Buying bombchus (in logic) w. shopsanity to unlock them is nasty

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#825]
Using the most recent build, and ended up needing the spoiler log because I was stuck.

As it turns out, in my shopsanity seed bombchus were on sale in one shop for 175 rupees. I didn't notice this because I'm so used to chus being refill items in packs that I don't cursor over them normally if I don't have them unlocked.

It seems kind of nasty to expect players to cursor over all shop chus to see that they are actually the initial unlock of the chus rather than packs of 5/10. Would it make sense to ensure that the initial chu unlock doesn't appear in stores?

**Comment by aofengen** [comment]
the one-time shop items are the same as finding items in the world. if it's on the left-side of a shop, you can buy it at any time. I don't see the issue, tbh

**Comment by Cuphat** [comment]
"Special Buy" (items from the normal pool buyable with no restrictions besides rupees) are always on the left side of the shop. You should probably check all of those when you are playing shopsanity, yes.

**Comment by joeauty** [comment]
Yeah, I know that the special items are on the left and I know how to not make this mistake again, thanks for the tips!

I just thought that this was kind of a usability issue, but if you disagree, so be it!

**Comment by KevinPal** [comment]
Maybe we should mark these in some way? I've seen it pop up a few times in the support channels, and new players probably won't realize they can buy some chus but not others.

**Comment by joeauty** [comment]
IMO it would be good to always make chus purchasable, but just make them much harder to find in shops so you have to work a little harder to get yourself your first explosives.

**Comment by r0bd0g** [comment]
I want to point out a similar issue occurs here with tunics. Or really with any item that looks the same as another item that appears in a shop? But I think it's mainly the chus and the tunics where they have logical implications but you can't distinguish them from shop items at a glance.

I think we changed bottles in shops to always appear as bottles? But then somebody complained b/c they were supposed to buy a Big Poe Bottle and didn't check what type it was b/c they already had a normal bottle.

**Comment by joeauty** [comment]
Why not just take out tunics, bottles, and chus as special items? Seems like the easiest solve?

Too many confusing behaviors here, I think:

- child Link can't buy normal non-special tunic (AFAICR)
- can't buy the non-special chus, but can buy the special one
- can't buy the non-special bottles
- they all look the same, you have to cursor over all shop items which new players likely won't think to do
- because non-special tunics and chus are always priced the same, all the more reason why people wouldn't cursor over them. If the special tunics/chus/bottles are in the same shop as the non-special ones, this is also confusing

**Comment by r0bd0g** [comment]
I wish we could do something like put the words "special deal" right over the corners of the 1-time items in the shop somehow. I don't know if that can be done. But if nothing is done I think allowing all items to appear in shops is preferable to eliminating this bit of potential confusion...

**Comment by TestRunnerSRL** [comment]
Making the model appear different would be neat, but I wouldn't know how to do that

**Comment by TestRunnerSRL** [comment]
To clarify on this suggestion, there are no plans to change the current behavior of the bombchus in shops. Like all other items in the shop on the left side, they are essentially treated like chests, so any chest item can appear there. This is why there are no buy restrictions (like child/adult) on these spots. In shopsanity, you really just need to hover over them to check if it's a special deal. If you are not doing a random number of items in the shop, you already know that the left X spots are special deals that are treated like chest locations. I think having some visual indication on the model would be awesome, but I don't know how to implement it and is kinda outside of the scope of this request. I think floating text is highly unlikely to happen, but maybe it would be possible to add some kind of glow/flashing or something
