### ISSUE TITLE
Credits Crash

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#828]
dotzo Last Sunday at 8:39 PM

":version":             "4.15.10 f.LUM",
":seed":                "K5J8JG6HQ4",
  ":settings_string":     "AJWAC2HQHANJX3ZAAA8HEF9JLAA",

And same version, the credits still crash.  First textbox after the "Goodbye" when it's on Death Mountain Trail, it crashes when it tries to draw the first character of that box.

I'm going to guess the crash only occurs on n64?

**Comment by TestRunnerSRL** [comment]
isn't this duplicate of #745

**Comment by r0bd0g** [comment]
I guess I assumed that by now this was supposed to have been fixed...

**Comment by r0bd0g** [comment]
Duplicate of #745
