### ISSUE TITLE
does not run (any emulator)

### ISSUE THREAD

**Issue by csharporblfat** [TestRunnerSRL/OoT-Randomizer#83]
Either gets black screen or the emulator crashes as soon as trying to load the file.

I also tried making a seed as close to vanilla as possible thinking maybe I had too many options set or something and same thing

**Comment by TestRunnerSRL** [comment]
Hi, can you ask this question on the Discord server in #questions-setup?

**Comment by csharporblfat** [comment]
how do i do that?
    On Thursday, September 6, 2018, 1:07:01 PM EDT, TestRunnerSRL <notifications@github.com> wrote:  
 
 
Hi, can you ask this question on the Discord server in #questions-setup?

**Comment by TestRunnerSRL** [comment]
You can find the discord here: [OOT Randomizer Discord](https://discordapp.com/invite/qMnX99y)
