### ISSUE TITLE
Can someone explain this logic to me?

### ISSUE THREAD

**Issue by Kongolan** [TestRunnerSRL/OoT-Randomizer#839]
https://pastebin.com/WyLNMpjN

Epona's Song is all dungeons, Longshot is locked by Hammer and Hammer is locked by Boomerang, which was in GTG. So is hookshot extension in logic?? Since the spoiler log doesn't tell me that it's all dungeons, just to get the hover boots / boomerang behind the bridge. So what did the logic want me to do? Epona, Hookshot extension or clip through reverse wasteland (if that is even possible??)?

It also needs 40 Skulls for Strength 2, though i found Strength 2  randomly in Lost Woods Grotto as well.

**Comment by Hamsda** [comment]
Longshot is not locked by hammer, it is locked by strength 2.
Please check with the folks in the #gameplay-support channel first.

**Comment by Kongolan** [comment]
Thanks a lot, and you are right. I didn't had discord ready so github was much easier for me, thanks for the effort.
