### ISSUE TITLE
[Feature Request] Sunken Bottle item check appears in adult link overworld

### ISSUE THREAD

**Issue by tommaniacal** [TestRunnerSRL/OoT-Randomizer#847]
If the player hasn't gotten the sunken bottle item as child link and becomes adult, it would be cool if the item was still there as adult. If there are other items that behave this way (appearing in child overworld but not in adult overworld) it would be cool if those were added as well

**Comment by LostThePirate** [comment]
That would remove the requirement of Scale to get to it, though, since the water level is so low at the Lake as Adult, it would just be sitting on the ground. While Closed Door does get some play, I think that this would be a bad for everyone who plays Open Door, making that item basically free.

**Comment by TestRunnerSRL** [comment]
Yeah this isn't really doable without trivializing this item location
