### ISSUE TITLE
Buying 4th Heart Piece from shop?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#85]
Report from supermario3459 on version 2.16.3: Hmmm... I had three piece of heart and buying [from market bazaar] the fourth one gave me nothing more, but my piece of heart count got back to 1...

**Comment by TestRunnerSRL** [comment]
Hmm, I'll need to test it (later). For the sake of completeness, can you get the seed/settings/platform? Kinda doubt it matters but just in case I guess

**Comment by r0bd0g** [comment]
Settings: BN5A6RP5AAAJEA
Seed: RTK1OQZ2R2
ParaLLEl (retroarch)

**Comment by TestRunnerSRL** [comment]
Wasn't able to reproduce. Seems possible that they had only 0 HP when they bought one and it increased it to 1.
