### ISSUE TITLE
Generating Hints for multiple seeds?

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#86]
Report from dotzo on unspecified old version: this needs to be checked on the current versions, but the hints don't regenerate if you do multiple seeds at once; it just copies from the original over and over

**Comment by TestRunnerSRL** [comment]
Hmm, not sure why that would be the case. I'll look at it later, I'm sure I did something dumb

**Comment by TestRunnerSRL** [comment]
Added hint output to spoiler log, but I didn't notice this happening. Not sure if this is something I've inadvertently fixed, or something else weird was happening.

**Comment by r0bd0g** [comment]
There's a possibility I think that this is specific to the tournament build? They made some changes to hints there and now you can't generate spoiler logs if you don't generate a rom or something and you have to close it between rom generations or something? Weird idk.
