### ISSUE TITLE
SoS Crash

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#868]
TrenteR_TR Today at 12:52 PM

https://www.youtube.com/watch?v=XrLT6yBe9pQ
Ignore the voices of me and my mates. 
Happened 20 minutes ago. 
MW Aug Async1, Patched with most recent version.
https://cdn.discordapp.com/attachments/438698093354156032/614487081095528467/OoT_D5813_Async_Aug_01_W3P1_Cosmetics.txt

--

Shuffled fanfares is currently the suspected culprit...

**Comment by darkangel93x** [comment]
Just Crashes with that specific Combo: 

DC/Dampe Race --> Hyrule Field
Windmillhut --> Lon Lon Ranch
SoS --> Ganondorf Appears

if Windmillhut and DC/Dampe race are switched it does not crash anymore.

Advised to not use Ocarina Songs as Fanfares and you should be save.

**Comment by flagrama** [comment]
Has anybody tried to ensure this doesn't happen on 5.1? This might be solved now.

**Comment by r0bd0g** [comment]
I thought the 5.1 changes fixed the bugs like these and tbh I'm a bit surprised the issue is still open.

**Comment by flagrama** [comment]
I haven't heard of this bug occurring since before 5.1. I believe this is fixed.
