### ISSUE TITLE
Global Retry issue

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#869]
Roman Today at 11:55 AM

from what I know, if the global retry does happen it should either fail during patching or end up with some starting items in the spoiler log duplicated

but even that shouldn't cause any issues in game

for example you would get 1998 rupees at the start instead of 999, which is just capped anyway

same thing with sticks and nuts

and starting with 2 deku shields or 2 serenade/prelude/farores shouldn't do anything either(edited)

all of that is for the "start with" options btw

more than 3 wallets fails to patch but that shouldn't be too much of an issue either, you would just need to generate a new seed I guess

and all of that is extremely unlikely to happen anyway since you both need the "start with" options + a global retry to trigger which very rarely happens due to how robust the ER and fill algorithms are now

**Comment by Zannick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix global retry](https://trello.com/c/hgVxrKUz/32-fix-global-retry)
