### ISSUE TITLE
Wiki suggestion: Mention that Save and Quit/Reset is sometimes necessary

### ISSUE THREAD

**Issue by Ryan1729** [TestRunnerSRL/OoT-Randomizer#870]
Using warp songs at the wrong time or the entrance randomizer can create situations where saving and quitting/resetting the console is necessary to continue.

If you search in the discord for "save quit" you can see that people frequently have to ask about how to get unstuck in those scenarios. 

It seems like it might we worth adding something about how saving and quitting/resetting the console may be required sometimes on the [Logic wiki page](https://wiki.ootrandomizer.com/index.php?title=Logic).

**Comment by flagrama** [comment]
It's vanilla knowledge. Somebody who has access and is willing to fight the wiki to add that certainly can, but you should know the vanilla mechanics before even playing rando. It's the same kind of reason as textrando doesn't count vanilla shop items as "hints" when shuffling everything except hints.

Also github is not the place to make suggestions about things that are not code.

**Comment by Ryan1729** [comment]
> Also github is not the place to make suggestions about things that are not code.

Okay, is there a designated place for wiki suggestions? It might be good idea to have that linked from the README.

Also if misplaced github issues are a recurring problem, [issue templates](https://help.github.com/en/articles/about-issue-and-pull-request-templates#issue-templates) could be helpful.

**Comment by flagrama** [comment]
The Discord which is linked to on the website which is linked to on the README.

We had an issue template once. Tekky killed it :P
