### ISSUE TITLE
Equipment starting items not equipped properly in adult start

### ISSUE THREAD

**Issue by Roman971** [TestRunnerSRL/OoT-Randomizer#874]
When starting as adult, using plando to start with certain equipment items (swords/shields/tunics) is not handled properly and the wrong values seem to be stored in the initial save context, which means the wrong items are auto equipped in game, sometimes even invalid items.
This seems to happen at least with Biggoron Sword, Mirror Shield, and Goron and Zora Tunics.

Pretty minor overall as the player just has to manually equip the items at the beginning of the seed in case it happens. And it never seems to cause any other issues like softlocks/crashes or anything like that.

**Comment by aofengen** [comment]
https://clips.twitch.tv/KathishAbrasiveMonitorCopyThis - just evidence of this (plando'd mirror shield, start as adult). spoiler and patch file available if necessary
