### ISSUE TITLE
More SFX/BGM Issues or is it something with doors? I dunno!

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#877]
BeeLuigi Today at 9:58 PM
So there might still be issues with some BGM/SFX stuff. Conversation starting here: https://discordapp.com/channels/274180765816848384/274186223147417600/615340780529123328 (and quite long cause 5.0 hype). Game freezes at the first door to slingshot room in Deku. Changing SFX settings fixes it. No cosmetics log unfortunately...
Edit: Conversation continues here after a long pause cause repatching: https://discordapp.com/channels/274180765816848384/274186223147417600/615345321618309170

**Comment by mzxrules** [comment]
likely fixed with #900
