### ISSUE TITLE
Black Screen in Kakariko Bazaar

### ISSUE THREAD

**Issue by CrabMustard** [TestRunnerSRL/OoT-Randomizer#881]
For the seed https://ootrandomizer.com/seed/get?id=223704

Entering the bazaar in Kakariko as an adult softlocks the game on a black screen. Reloading the game does not fix the issue.

**Comment by darkangel93x** [comment]
entered both just fine , what emulator are you on ?

**Comment by CrabMustard** [comment]
Yeah that turned out to be it. Didn't happen on older rando versions on that, but changing emulators worked.
