### ISSUE TITLE
Crash on collecting token

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#885]
Classic Reborn Today at 4:45 AM
so it seems whenever i grab the skulltulla in goron city my game freezes, ive recreated it multiple times
https://cdn.discordapp.com/attachments/438698093354156032/616901847323770880/RetroArch_2019.08.30_-_02.46.47.03.mp4

Fanfares are not shuffled.

This is the seed that was used: https://www.ootrandomizer.com/seed/get?id=226019
But I believe the cosmetics have been overwritten, and no cosmetic log was provided. You can tell in the video that shuffle BGM is on, though. He says max randomization on available cosmetic options.

**Comment by r0bd0g** [comment]
Phantom Today at 12:45 AM
So as ive played through the rando, sometimes when grabbing items the game freezes.  This freeze can occur when grabbing an item, but if i restart and come back i may be able to  grab the item that time.  Sometimes, it doesnt work multiple times in a row.  It happens with both normal items, putting things in bottles like blue flame in Ice cavern, and skulls. most of the time in dungeons.  It has occured many times in forest temple, DC, the well, and ice cavern, the only dungeons ive full cleared so far.  Im using RetroArch emulator, and It happens on both Mumen64 and parallel.   I have a screen of one time it froze when grabbing a skull token.  Any support as to how i can fix this issue is greatly appreciated

**Comment by TestRunnerSRL** [comment]
I'm going to go out on a limb and assume it has something to do with fanfares, so this should be stable in latest dev now...

**Comment by mzxrules** [comment]
likely fixed with #900
