### ISSUE TITLE
[Feature Request] Getting both item checks on the first Dampé race

### ISSUE THREAD

**Issue by tommaniacal** [TestRunnerSRL/OoT-Randomizer#886]
If you beat Dampé in under a minute on the first race, you should be able to get both the Chest check and the Heart Piece Check, so you won't always have to do the race twice

**Comment by dotzo** [comment]
https://github.com/TestRunnerSRL/OoT-Randomizer/pull/875

**Comment by aofengen** [comment]
not to mention that this one has been debated in the discord for quite a while

**Comment by tommaniacal** [comment]
What's there to debate? It doesn't take any more skill to do the second race compared to the first, so all it does is remove unnecessary padding

**Comment by aofengen** [comment]
After testing, it's been shown that the two races are not the same, with the second one being somewhat more "difficult". There's a worry about locking both items behind race 2 if someone can't complete it

**Comment by flagrama** [comment]
On Sat, 2019-08-31 at 15:28 -0700, aofengen wrote:
> After testing, it's been shown that the two races are not the same,
> with the second one being somewhat more "difficult". There's a worry
> about locking both items behind race 2 if someone can't complete it

Roman has also said once before in the Discord that there was no change
in the code for Dampe during the second race. I'm not sure if Dom found
anything that was any different other than it checking something every
second (likely checking whether the race is finished and/or whether the
time is under a minute) so it is very possible the perceived
differences by players aren't actual differences, but just confirmation
bias.

**Comment by aofengen** [comment]
entirely possible as well - just pointing out the reason it's been debated for so long

**Comment by tommaniacal** [comment]
Ah okay. Sorry if I sounded condescending, I was just curious why it was a controversial feature
