### ISSUE TITLE
Owls crashing

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#887]
It happens apparently.

It happened somewhere in this vod.
https://www.twitch.tv/videos/474578085

**Comment by r0bd0g** [comment]
flagrama Yesterday at 11:34 PM
I'm of the opinion the place I put the fanfares in RAM is not safe
either the fix should be removed, or the fanfare location should be relocated
I haven't actually tried to examine it at all in a debugger though

Roman Today at 12:13 AM
so what you're saying is owls are broken in general because of your attempt to fix shuffled fanfares 

flagrama Today at 12:15 AM
quite possibly

**Comment by darkangel93x** [comment]
14:00 :)

**Comment by RubikSolver1028** [comment]
The same thing happened to me. Except it happened 2 strange times.

First time, I had talked to Kaepora Gaebora in Lake Hylia, he lifted off and I moved the grave. But the second I jumped in the water, the game froze. I was able to hard reset.

Second time was like what happened in the VOD. The second I talked to him, my game crashed. Again, I was able to reset so I at least saved beforehand.

I don't have video proof. However, I was told that sending in my cosmetic log might help. This also was patched with the Dev build. When patched with the website, it worked fine.

[OoT_C3FCB_RumblingChickens_W7P2_Cosmetics.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3563106/OoT_C3FCB_RumblingChickens_W7P2_Cosmetics.txt)

**Comment by Wiimeiser** [comment]
Seems to be related to the specific track that overrides the main overworld theme. From my experience, it happens with the final boss theme, but not the shooting gallery theme, and even then it worked at night. Haven't gotten Zora's Domain there. Try seeing if it works at night and crashes during the day.

Alternatively, it could be whatever theme plays with the owl, which in my crashing case was Gerudo Valley. Don't know, really. Maybe randomizing fanfares is what does it...

**Comment by darkangel93x** [comment]
i add this here so it doesn't get lost :

[Owlcrash 5.0.3](https://youtu.be/wk8sVdXdoX4)
