### ISSUE TITLE
soft lock in happy mask salesman shop

### ISSUE THREAD

**Issue by emilybrooks** [TestRunnerSRL/OoT-Randomizer#9]
I was stuck in the happy mask salesman's shop menu, no buttons would close out of the menu or select a different mask, and I had to reset.

I had done up to bunny hood in the mask trade quest, traded back for the skull mask to check deku theater. When I went to get the bunny hood back it selected a blank option and displayed the pocket egg item text.

https://clips.twitch.tv/BigDeadSkirretDxCat

[OoT_RESKAS2JCSLA_XHDKRRC44I_Spoiler.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/2237575/OoT_RESKAS2JCSLA_XHDKRRC44I_Spoiler.txt)

Settings used: RESKAS2JCSLA
Seed: XHDKRRC44I

**Comment by TestRunnerSRL** [comment]
Should be fixed now
