### ISSUE TITLE
Fanfares affecting length of cutscenes

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#902]
TrenteR_TR Today at 3:08 AM
Just to make sure because I'm not 100% sure. I had fanfare shuffle on. HBA complete fanfare was long, and it took more time to get the fadeout. Is that linked or am I just seeing things?

--

Apparently if you have a longer fanfare, it takes longer for the HBA game to fade out? If this is true, I think it's actually a fatal flaw with this setting.

**Comment by darkangel93x** [comment]
indeed the first hba fades out after the fanfare got played the 2nd one fades out almost immediately

**Comment by darkangel93x** [comment]
so remove the hba fanfare from the shuffle pool

**Comment by darkangel93x** [comment]
so you cant softlock with a looped fanfare, thats good. the fadeout is weird though, one time it happens in normal time, the other time it takes a bit longer.

**Comment by flagrama** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fanfares Affecting Length of Cutscenes](https://trello.com/c/bzKdaPkJ/19-fanfares-affecting-length-of-cutscenes)
