### ISSUE TITLE
Randomize Main Rules always chooses Default settings for settings under the "World" heading

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#908]
RomanToday at 5:19 AM
for section in disabling.get('setions', []):
disabled sections aren't handled the same as disabled settings
tl;dr randomized settings has been broken for months and it was never relevant until MQ settings were excluded because there was a typo in the key called "sections"

**Comment by Zannick** [comment]
Fixed by #934.
