### ISSUE TITLE
Closed Forest tooltip

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#910]
ToxicOxygenToday at 6:09 AM
the tooltip of Closed Forest states that "The Kokiri Sword and Slingshot are always
available somewhere in the forest." which is not true if you enable the "Deku Tree basement without slingshot" trick. I think describing what is blocked and that you will have the means to enter deku and beat it in the tooltip would work better
(yay minor tooltip mistakes :Keepo: )
also it doen't mention deku shield which I find weird

**Comment by Mast3rGenius** [comment]
To add onto this, what made you put the apostrophes around each of the settings on the tooltips. I think it adds clutter and sometimes does the opposite of what I'm assuming it is meant to do; adds more confusion than clarity.
