### ISSUE TITLE
Can't get 50r for doing Anju's Chickens again if Cucco count is set to 0

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#913]
This may or may not actually be a real thing b/c I haven't ever used this setting to try it myself >_>

**Comment by dotzo** [comment]
It's not a thing. Tested on __version__ = '5.0.45 f.LUM'.  Likely the original report was from PJ64 or because it was 2nd hand flawed in another way.  Tested in Bizhawk.
