### ISSUE TITLE
Hovering over the wall in LLR crashes the game as child

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#917]
Hovering over the wall in LLR crashes the game as child

**Comment by Wiimeiser** [comment]
More details would help. What wall are you talking about? Does this happen in vanilla, in the Randomizer with default settings, or only with overworld entrances randomized?

**Comment by dotzo** [comment]
Needs more testing, but it occurred in a multiworld with random main settings.  ER was off, it was night time, and it was the wall nearest gerudo.  In vanilla the load behaves normally, spawning you in hyrule field. 

Spoiler log for that game: https://pastebin.com/b7zV2XXt

**Comment by flagrama** [comment]
@Wiimeiser just so you're aware, while some discussion happens here, issues r0bd0g makes are usually more reminders and most discussion ends up in the #dev-bug-reports and #dev-public-talk channels on [the Discord](https://discord.gg/ootrandomizer).
He'll usually copy relevant conversation here, but sometimes he won't :laughing:

**Comment by dotzo** [comment]
Tested on VC with weekly settings, no issue, both at night and during the day.  Either bizhawk issue or some other normally unrelated problem.

**Comment by flagrama** [comment]
Reproduction steps seem to be:
1. Enable Quick Epona in generation
2. Obtain Ocarina and Epona's Song
3. Jump over the fence as child

However, there seems to be an instance where this can happen as adult too https://discordapp.com/channels/274180765816848384/438698093354156032/712988272871079977 which I was unable to reproduce.

**Comment by flagrama** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hovering Over Lon Lon Ranch Wall Can Crash](https://trello.com/c/sOdzJPYs/31-hovering-over-lon-lon-ranch-wall-can-crash)
