### ISSUE TITLE
Ruto Zora Sapphire Bug.

### ISSUE THREAD

**Issue by BubbaSWalter** [TestRunnerSRL/OoT-Randomizer#920]
So if you die in the room where ruto gets the zora's saphire.  this can Happen.
when you beat it she stays on the platform and you cant do anything.
https://clips.twitch.tv/SmokyBashfulMonitorBrokeBack

**Comment by Nicholas-Steel** [comment]
It looks like everything worked correctly? Her being there is to prevent soft-locks since you still need her to hit some switches in the dungeon when playing Randomizer.

**Comment by r0bd0g** [comment]
Maybe there's something could be done to make taking ruto back into this room less messy.

**Comment by Zannick** [comment]
This isn't discussing having Ruto available to carry around, this is discussing a visual bug where Ruto still appears on the platform in the Bigocto fight. I don't know if that's related to keeping Ruto around in the earlier part of the dungeon, but it's not really affecting anything in that fight or after.

**Comment by r0bd0g** [comment]
I mean everything that happens when you bring ruto back to big octo is super awkward and maybe something could be done to fix that. We get people that report thing all the time, asking if they're stuck and such...
