### ISSUE TITLE
Something is wrong with vanilla keys and map/compass in MQ Shadow

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#924]
You can tell b/c the Map Chest is in the playthrough as containing a key. I think it's possible the vanilla Shadow chest locations are being used instead? I notice the early gibdo's chest is not being randomized, which is the vanilla shadow compass location.

**Comment by dotzo** [comment]
Just tested with the vanilla MQ file. The two chests "Shadow Temple MQ Map Chest" and "Shadow Temple MQ Early Gibdos Chest" are swapped.  Even correctly labelled in the plando they have the opposite effect. In-game map chest holds a key, gibdo holds the map.
