### ISSUE TITLE
Non-existent Chests

### ISSUE THREAD

**Issue by KingSpilly** [TestRunnerSRL/OoT-Randomizer#926]
The chests labeled as "Ganons Castle Spirit Trial Second Chest" and "Ganons Castle MQ Spirit Trial Second Chest" in the item log don't seem to exist in the game.

**Comment by LostThePirate** [comment]
...You mean the one that's invisible...?

**Comment by totenphal** [comment]
Lens of truth in Spirit Trial. You will find them.
Also, please check in the Discord in #gameplay-support first.
