### ISSUE TITLE
Plandomizer: Hover Boots chest requires Hover Boots?

### ISSUE THREAD

**Issue by aplumafreak500** [TestRunnerSRL/OoT-Randomizer#929]
If Plandomizer is set to give the Hover Boots in its vanilla location, and Logic is set to "Glitchless" (haven't tried with glitched logic), ROMs will not generate. (I also have not tried the Master Quest Hover Boots location yet, but iirc the Hover Boots doesn't require itself in either case.)

**Comment by LostThePirate** [comment]
If your first Hookshot is logically after Hover Boots chest, then yes, this would fail because you ahve no way to get to that chest.

**Comment by aofengen** [comment]
Can almost guarantee it's an item required to reach that chest, not the boots themselves. Check dins, nocturne, magic, or the two hookshots

**Comment by flagrama** [comment]
You need Hover Boots or Hookshot to access Shadow Temple. Try 1) generating a bunch more times, or 2) placing Hookshot in some really early area. One before you'd need to get the Hover Boots.

**Comment by aplumafreak500** [comment]
actually both Hookshots were in their vanilla locations too in my testing...

**Comment by r0bd0g** [comment]
I dunno what's going on in vanilla, but MQ Shadow very likely will require Hovers to reach the Hover Boots chest. Logically that chest requires all keys, so if there are any keys placed later in the dungeon, it's going to fail.

**Comment by flagrama** [comment]
There are various reasons that the Vanilla plando forces No Logic. I recommend keeping No Logic on while using it since you already guarantee all items available.

**Comment by Zannick** [comment]
So, a minimal test case to put Hover Boots at the Hover Boots chest successfully generates a seed, so this is due to some other vanilla configuration that we don't allow with logic on to avoid softlocks (if I recall right, there are some small key locations behind locked doors that you can miss; I don't remember which dungeons).
