### ISSUE TITLE
Entrance randomizer can make Talon's cucco game unplayable

### ISSUE THREAD

**Issue by Nemitis** [TestRunnerSRL/OoT-Randomizer#930]
If the entrance to Talon's house is set to a door that is locked during the day then it becomes impossible to play the game because you can't wake him up at night when the door is unlocked. There might also be other rooms that break in this way, but this is the one I ran into.

**Comment by Cuphat** [comment]
Play Sun's Song.

**Comment by LostThePirate** [comment]
Logic will guarantee you Ocarina and Sun's if it is behind a night-only door before you need whatever his reward is.

**Comment by Nemitis** [comment]
I know I can get in at night, the problem is that he's sleeping the same way as when you first see him at Hyrule Castle.

**Comment by Nemitis** [comment]
![OoT A534B KRO4W85NED-comp 2019-11-20 02 29 02](https://user-images.githubusercontent.com/6497549/69217973-c7ba3000-0b3d-11ea-97b4-e383324c95d1.png)

**Comment by Nemitis** [comment]
lol, I just realized I can play the song inside. Sorry!
