### ISSUE TITLE
Escape doesn't skip if you die to Ganon

### ISSUE THREAD

**Issue by sydwys8** [TestRunnerSRL/OoT-Randomizer#94]
Death to Ganon reverts save to just after Ganondorf kill but before escape, so setting the skip_escape flag will not skip escape if there is a death to Ganon. I do not know if this is fixable without reverting the save to a state prior to the Ganondorf kill.

**Comment by TestRunnerSRL** [comment]
Yeah this is known, but not really sure how to realistically fix this, personally.

**Comment by sydwys8** [comment]
I'm surprised there isn't a known issue section like there is on the main branch. That would be enough in my opinion.

**Comment by TestRunnerSRL** [comment]
This place is as good as any
