### ISSUE TITLE
Archery Game - Light Arrow Reward bypassed without Bow

### ISSUE THREAD

**Issue by RickDanwiches** [TestRunnerSRL/OoT-Randomizer#943]
Playing the seed listed below the light Arrows are on Adult Archery. If you go to the archery game before you have bow the light arrows reward is skipped and the 50 rupee reward is given as if you already have beaten the mini game (you can do this indefinitely without the bow and the 50 reward is given).  If you then go and collect the bow and replay the game the light arrow reward will be given. 

Seed Details: 
https://ootrandomizer.com/seed/get?id=304170
Generation Date 12/14/2019, 5:18:06 PM UTC -- Seed PV553XFKBO -- Settings String AJFSTK4RZJAQRLH97A5S5A8S8AABETFTKLAAAUK2FUCA

Light Arrows: Adult Archery 

Details on getting the bow: 
Spirit Small Key: Vanilla Fairy Ocarina Location
Bomb Bag: 20 Rupees in Bombchu Shop
Spirit Temple Entrance: Dodongos Cavern  
Song of Storms: GS Spirit Temple Bomb for Light Room
Open Well with Song of Storms
Gerudo Training Grounds Entrance: Bottom of the Well 
Bow: Gerudo Training Grounds MQ Maze Path First Chest

**Comment by flagrama** [comment]
Intended.

**Comment by aofengen** [comment]
This is vanilla behavior. No bug at all.

**Comment by RickDanwiches** [comment]
yeah my mistake i was thinking that both that and slingshot game were opened to give the reward withtout checking for the source of either the bow or slingshot

**Comment by Cuphat** [comment]
The slingshot game being like that is also vanilla, they just assume you have a slingshot if you made it out of the forest.
