### ISSUE TITLE
Sometimes hint not being duplicated

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#950]
dotzoToday at 11:41 AM
":version":            "5.1.0 Release",
  "file_hash":           ["Gold Scale", "Compass", "Saw", "Hover Boots", "Bow"],
  ":seed":               "33GWNQN9GP",
  ":settings_string":    "AJWYAJARB2BCAAJWAAJBASAGJBHNTHA3EA2UTVAFAA",

Sometimes hints generating 6 unique hints, 4 of which are duplicated as normal, 2 other unique not duplicated.
Possibly double checking for reachability of the duplicate?
Tested both in the online build and offline build for 5.1.0

The sometimes hints from the seed: 
"Death Mountain Trail (Biggoron)":       {"text": "They say that spinning #Goron pottery# contains #a Strength Upgrade#.", "colors": ["Green", "Red"]},
"Desert Colossus (Spirit Temple)":       {"text": "They say that spinning #Goron pottery# contains #a Strength Upgrade#.", "colors": ["Green", "Red"]},
"Goron City (Maze)":                     {"text": "They say that Sheik waits at a #monument to time# to teach #the Bolero of Fire#.", "colors": ["Green", "Red"]},
"Zoras Domain (Mweep)":                  {"text": "They say that Sheik waits at a #monument to time# to teach #the Bolero of Fire#.", "colors": ["Green", "Red"]},
"Hyrule Castle (Rock Wall)":             {"text": "They say that #Darunia's dance# leads to #Arrows (10 pieces)#.", "colors": ["Green", "Red"]},
"Lake Hylia (Southeast Corner)":         {"text": "They say that #Darunia's dance# leads to #Arrows (10 pieces)#.", "colors": ["Green", "Red"]},
"Sacred Forest Meadow (Maze Upper)":     {"text": "They say that the #crater's melody# is #the Song of Time#.", "colors": ["Green", "Red"]},
"Zoras River (Waterfall)":               {"text": "They say that the #crater's melody# is #the Song of Time#.", "colors": ["Green", "Red"]}
"Graveyard (Shadow Temple)":             {"text": "They say that playing #Sun's Song# in a grave spawns #a Piece of Heart#.", "colors": ["Green", "Red"]},
"Kakariko (Potion Grotto)":              {"text": "They say that in #Goron City# the hammer unlocks #the Hover Boots#.", "colors": ["Green", "Red"]},

---

I know that there have been some changes with how hints are placed? So I don't know for sure that it still occurs.

**Comment by Zannick** [comment]
I've determined what happened here is that the Graveyard and Kak Grotto stones were the last two in the shuffle, and a hint was generated for the GC Leftmost Maze Chest (Hover Boots). The Graveyard failed its reachability check without the Hover Boots, and so was skipped. The hint was placed at the Kak Grotto stone and there were no more stones to place any duplicates, after that, the Graveyard stone received a different hint.

The simple fix for this is to pull duplicate stones from the list of stones that failed this criteria. We can prefer those stones to bias duplicates toward unreachable stones, or use them last to bias away from it. (This will only matter when `count > 1`.)

A more thorough fix to rewrite `add_hint` would take a sufficiently subset of the remaining stones, confirm that one matches the strict condition and the rest match the looser condition.
