### ISSUE TITLE
[Feature Request] Option to include chest mini-game keys in item pool 

### ISSUE THREAD

**Issue by tommaniacal** [TestRunnerSRL/OoT-Randomizer#953]
For the chest mini-game that uses the mask of truth, it would be cool if the keys were added to the item pool. Then the key the clerk gives you can be a random item, as well as the chests in each room. 

Since this also adds a lot of green rupees to the pool, I could see it being optional. 

I'm not sure if this is even possible since the mini-game chests probably function differently than normal chests. If it is would you be able to see the randomized items with the mask of truth? Could this be applied to every chest to make the mask of truth more useful?

**Comment by aofengen** [comment]
No. Gotta be honest, this one sounds extremely tedious and just not very fun. 5 keys required for 1 or 2 checks? Just a hard no from me.

**Comment by flagrama** [comment]
All of the checks would also require Lens of Truth by logic, but it would remove any real-life reason to actually use the Lens of Truth since the game would not be able to reset if this was done, meaning more lens logic for racers to hate.

It's just not really feasible without way more work than anyone wants to put in, and I'm not even sure the devs would even approve of such a "feature."

**Comment by tommaniacal** [comment]
> No. Gotta be honest, this one sounds extremely tedious and just not very fun. 5 keys required for 1 or 2 checks? Just a hard no from me.

I think you misunderstand. Every chest would be a new check, so there would be 11 chest checks, and the clerk check. So it would be 10 rupees for a new check, and 11 item checks for 5 keys. Dunno how that's any different than the gerudo thief keys

**Comment by tommaniacal** [comment]
> All of the checks would also require Lens of Truth by logic, but it would remove any real-life reason to actually use the Lens of Truth since the game would not be able to reset if this was done, meaning more lens logic for racers to hate.
> 
> It's just not really feasible without way more work than anyone wants to put in, and I'm not even sure the devs would even approve of such a "feature."

How would this be any different than the gerudo thief keys? You need 4 keys to unlock the bridge and one item check.

This needs 5 keys for 11 item checks, and a 10 rupee check right away. It honestly sounds more rewarding

**Comment by Zannick** [comment]
If I understand right, this would involve changing the mechanics of the Treasure Chest mini-game to be merely a sequence of rooms with chests in them, disabling the auto-open of the second chest in each room, and turning off the reset on leaving. The logic would no longer require lens, making lens less useful in this mode.

It's an interesting idea to add more key-shuffle options, but adding 11 checks will make this interior on par with most dungeons, and more check-dense than any other interior (Mido's House has 4, shops have 4 plus refills, Skulltula House has 5... if 50 skulls isn't disabled). That's enough to be concerned a little bit about balance.

As for tedium, each key found would be used simply to unlock another 2 chests (1 for the last) without any additional challenge or puzzle, unlike every other set of keys in the game (even GTG's central maze has options like an alternate route or weirdshot). As a change on top of existing behavior, one might see that as delaying one check to get two later, which might be interesting but not thrilling.

So I don't think shuffling in the chest mini-game keys will be all that worth it, based on those factors.

Making lens be more useful by allowing it to peek inside normal chests is an interesting idea, but mostly cosmetic when fast chests is on, except for chests you can see before you unlock them (like Ganon's Boss Key Chest). I don't know whether we would take that either, but if you're interested in that, or any other new feature, please gather feedback in #suggestions on [our Discord server](https://discord.gg/y6nhg4r) first.
