### ISSUE TITLE
Token Bridge logically requires all 100

### ISSUE THREAD

**Issue by r0bd0g** [TestRunnerSRL/OoT-Randomizer#965]
https://cdn.discordapp.com/attachments/291655374644183041/664007728821174302/OoT_61F5C_VV3MB7ERF5_Spoiler.json

Either this did not occur on 5.1 or I didn't try the right combination of settings.

(Even if you were to say that this is intentional for some reason (don't say that), the term "way of the hero" should not be used for hints at the least.)

**Comment by Roman971** [comment]
Fixed with #968
