### ISSUE TITLE
deku stick as adult question

### ISSUE THREAD

**Issue by tommaniacal** [TestRunnerSRL/OoT-Randomizer#983]
I know that in some versions, equip swapping deku stick as adult link crashes the game, and in others it doesn't. Trying to use it in rando crashes for me (I use Parallel in Retroarch in case that makes a difference). Would it be possible to make deku sticks usable in all versions of the randomizer?

**Comment by aofengen** [comment]
no. that's a vanilla issue. adult cannot use sticks. Even doing so on VC requires equip swap, and glitches are not coded into the randomizer.

**Comment by tommaniacal** [comment]
> no. that's a vanilla issue. adult cannot use sticks on anything but VC. Even doing so on VC requires equip swap, and glitches are not coded into the randomizer.
> 
> Additionally, allowing adult to use child items and vice versa destroys the core mechanic of the game - travelling through time. At that point, it's no longer OoT with randomized stuff. Just another bad romhack.

No, I'm saying that you'd still need to use equip swap, the only difference being that all versions would have the VC affect of being able to use deku sticks

**Comment by aofengen** [comment]
That's outside the scope of this project, imo. And still a bad idea.

**Comment by Zannick** [comment]
I'm not opposed to fixing the crash from equip swap, but outside of luck (we accidentally fix it while fixing another issue), it seems unlikely to happen; someone would have to volunteer to look into it and figure out a fix.
