### ISSUE TITLE
Starting items fixes

### ISSUE THREAD

**Issue by Zannick** [TestRunnerSRL/OoT-Randomizer#996]
Leftover todos from the starting items PR @rlbond86:

1.  The list should be forwarded to the plandomizer's starting items list so that Plandomizer handles the pool changes. At the moment, it's being done in Patches.py.
2.  Bow, Bomb Bag, and Slingshot should always give full ammo when starting with them; remove from `start_with_consumables`.
3.  Revert the removal of "Wallet upgrades fill wallet." from the tooltip of "Start with Max Rupees" (that behavior wasn't changed).
4.  "Magic Beans" is an item in the GUI, which makes you start with 10 beans, but it leaves the magic bean pack in the pool when bean shuffle is enabled.
5.  The readme now says to set "Gerudo Fortress" to "Open Fortress" in order to start with the gerudo card, but that's only true if "Shuffle Gerudo Card" is disabled. (This is my fault, I'll rework that.)
6.  "Start with Consumables" incorrectly gives a deku shield when shopsanity is off, which is a leftover of "Start with Deku Equipment".

**Comment by rlbond86** [comment]
Oh nice, I actually was planning on this but went on vacation.

One thing not addressed here: it was agreed in the discord that "Bombchus" should start with 20 instead of 50 and that Start with Consumables should just give sticks and nuts.

**Comment by rlbond86** [comment]
I think I have a working branch now
