### ISSUE TITLE
Dungeon Entrance Shuffle Issue: Water Temple was in BotW, so Adult Link couldn’t access it. I had Glitchless logic on.

### ISSUE THREAD

**Issue by Warri0rlink** [TestRunnerSRL/OoT-Randomizer#998]
Is there any way that child and adult dungeon entrances could be shuffled separately?

**Comment by Cuphat** [comment]
Use the discord support channels next time, this is not a bug. You can access BotW entrance as adult if you open it as child in entrance randomizer.

**Comment by Warri0rlink** [comment]
I was unaware of this. Thank you so much!

**Comment by flagrama** [comment]
We have several wiki pages with important, must-know information while playing randomizer.

[Glitchless Logic Must-Know Information](https://wiki.ootrandomizer.com/index.php?title=Logic)
[Entrance Randomizer Must-Know Information](https://wiki.ootrandomizer.com/index.php?title=Entrance_Randomizer)
[Glitched Logic Must-Know Information](https://wiki.ootrandomizer.com/index.php?title=Glitched_Logic)
